#!/bin/bash
# Generated by OrchestKit Claude Plugin
# Created: 2026-06-06

# Security Tests: Dependency-Confusion Package References
# Fails if any authored source references an unclaimed/non-existent npm package
# name under a trusted scope. Copy-pasting such an install command would let an
# attacker who publishes the unclaimed name run arbitrary code on a user's box.
#
# Origin: Blue Bear Security report (2026-06-04) — knowledge-evaluation.md cited
#   `npm install @anthropic-ai/claude@latest`. That package does not exist; the
#   real CLI is `@anthropic-ai/claude-code`. The bare `@anthropic-ai/claude`
#   name was unclaimed under Anthropic's npm org scope.
#
# Strategy: offline denylist (no network → no CI flake). Known-unclaimed names
# under trusted scopes are hard failures. Valid packages (claude-code,
# claude-agent-sdk, …) are unaffected because the denylist matches the exact
# bare token only, never a longer `-suffix` package.
#
# Priority: HIGH
# Reference: OWASP A06:2021 (Vulnerable & Outdated Components) / supply-chain

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

TESTS_PASSED=0
TESTS_FAILED=0
log_pass() { echo -e "  ${GREEN}✓${NC} $1"; TESTS_PASSED=$((TESTS_PASSED + 1)); }
log_fail() { echo -e "  ${RED}✗${NC} $1"; TESTS_FAILED=$((TESTS_FAILED + 1)); }

cd "$PROJECT_ROOT"

# Denylist of unclaimed / non-existent package names under trusted scopes.
# Each pattern is a POSIX ERE (portable across BSD/macOS + GNU/Linux grep — no
# `-P`/lookahead). It matches the EXACT bare package token by requiring the name
# to be followed by end-of-line or a non-package character, so
# `@anthropic-ai/claude` (and `…claude@latest`, `…claude"`) is flagged but
# `@anthropic-ai/claude-code` / `@anthropic-ai/claude-agent-sdk` are not.
DENY_PATTERNS=(
  '@anthropic-ai/claude($|[^-[:alnum:]_.])'
)

# Authored surfaces only. `plugins/` is generated (covered transitively because
# its source is scanned). `shared/cc-snapshots/` is verbatim upstream CC
# changelog text and `node_modules/` is third-party — both excluded.
SCAN_DIRS=(src docs/site/content tests/integration tests/security)

echo "╔══════════════════════════════════════════════════════════════════╗"
echo "║   Dependency-Confusion Package Reference Tests (supply-chain)     ║"
echo "╚══════════════════════════════════════════════════════════════════╝"

# --- Self-test: the denylist must actually catch the known-bad string --------
echo -e "\n${YELLOW}Self-test: denylist regex catches the known-bad pattern${NC}"
SELF_BAD='npm install @anthropic-ai/claude@latest'
SELF_OK='npm install @anthropic-ai/claude-code@latest'
# Here-strings, not `echo | grep -q`: grep -q early-exits on the first match and
# SIGPIPEs the producer, which under `set -o pipefail` propagates exit 141 and
# flips this `if` FALSE non-deterministically under load (#603). Both payloads
# are ~40 bytes, far under the 512B PIPE_BUF that makes here-strings unsafe.
if grep -qE "${DENY_PATTERNS[0]}" <<<"$SELF_BAD"; then
  log_pass "regex flags bare @anthropic-ai/claude"
else
  log_fail "regex FAILED to flag bare @anthropic-ai/claude (guard is broken)"
fi
if grep -qE "${DENY_PATTERNS[0]}" <<<"$SELF_OK"; then
  log_fail "regex false-positives on valid @anthropic-ai/claude-code"
else
  log_pass "regex allows valid @anthropic-ai/claude-code"
fi

# --- Scan surface must exist: a silently-narrowed scan is a blind scan --------
# This used to filter SCAN_DIRS down to whatever happened to exist. A renamed or
# moved directory therefore shrank coverage with no signal, and the section still
# reported "no references" — the static-test equivalent of grepping a deleted
# path. A missing scan dir is now a hard failure that names itself.
echo -e "\n${YELLOW}Scan surface: every declared directory is present${NC}"
missing_dirs=0
for d in "${SCAN_DIRS[@]}"; do
  if [ -d "$d" ]; then
    log_pass "scan dir present: $d"
  else
    log_fail "scan dir MISSING: $d — coverage silently lost, fix SCAN_DIRS"
    missing_dirs=$((missing_dirs + 1))
  fi
done

# --- Repo scan: no authored file may reference a denied package --------------
echo -e "\n${YELLOW}Repo scan: no source references an unclaimed package${NC}"
if [ "$missing_dirs" -gt 0 ]; then
  log_fail "skipping repo scan: $missing_dirs declared scan dir(s) missing"
else
  for pat in "${DENY_PATTERNS[@]}"; do
    # Exclusions:
    #  - node_modules / dist: third-party + generated (dist sourcemaps embed the
    #    scanner's own detection pattern; source is the authored surface).
    #  - this script + the scanner hook/test: they hold the denied literal on
    #    purpose (as documentation, a detection regex, and test fixtures).
    #
    # grep's exit code is load-bearing and must NOT be flattened with `|| true`:
    #   0 = matches found (violation), 1 = clean (the answer we want),
    #   >1 = grep itself failed (unreadable dir, bad pattern) — which the old
    #   `2>/dev/null || true` turned into an indistinguishable "clean".
    rc=0
    hits=$(grep -rnE \
      --exclude-dir=node_modules --exclude-dir=dist \
      --exclude="test-dependency-confusion.sh" \
      --exclude="dependency-confusion-scanner.*" \
      "$pat" "${SCAN_DIRS[@]}") || rc=$?
    if [ "$rc" -gt 1 ]; then
      log_fail "grep failed (exit $rc) scanning for: $pat — result is unknown, not clean"
    elif [ "$rc" -eq 0 ]; then
      log_fail "denied package pattern found: $pat"
      echo "$hits" | sed 's/^/      /'
    else
      log_pass "no references to denied pattern: $pat"
    fi
  done
fi

echo ""
echo "=========================================="
echo "  Results: $TESTS_PASSED passed, $TESTS_FAILED failed"
echo "=========================================="

if [ "$TESTS_FAILED" -gt 0 ]; then
  echo -e "${RED}FAIL: dependency-confusion references detected${NC}"
  echo "  Fix: use the real package name (e.g. @anthropic-ai/claude-code),"
  echo "  or if intentionally illustrative, use an explicit local path (./pkg)."
  exit 1
else
  echo -e "${GREEN}SUCCESS: All tests passed${NC}"
  exit 0
fi
