#!/bin/bash
# Generated by OrchestKit Claude Plugin
# Created: 2026-09-17

# Security Tests: Public Surface Names
# This repo is public. Value-shaped scanners (gitleaks, content-secret-scanner)
# never fire on a NAME, yet a deployment-specific 1Password path or a real home
# directory is still a disclosure: it tells a reader which vault, which item and
# which machine to aim at. Both classes have already landed here once (#2814,
# #4167). This test greps tracked files for the two shapes and fails on any hit
# that is not a documented placeholder.
#
# Allowed:
#   - op://<vault>/<item>/...   and any vault or item that reads as a placeholder
#     (starts with "<", "$", "{", or is one of VAULT, vault, your, my, example)
#   - /Users/<name> where <name> is a documentation stand-in (me, foo, john,
#     test, dev, someone, probe, alice, bob, you, testuser, op, env, ...)
#
# Test Count: 2
# Priority: HIGH
# Reference: audit 2026-09-17 finding SC-2 (docs/security/audit-2026-09-17.md)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
cd "$PROJECT_ROOT"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

TESTS_PASSED=0
TESTS_FAILED=0

log_pass() { echo -e "  ${GREEN}✓${NC} $1"; TESTS_PASSED=$((TESTS_PASSED + 1)); }
log_fail() { echo -e "  ${RED}✗${NC} $1"; TESTS_FAILED=$((TESTS_FAILED + 1)); }
log_section() { echo -e "\n${YELLOW}$1${NC}"; }

# Tracked files only, NUL-delimited so non-ASCII paths are not escaped away.
# This file is excluded from its own scan (it documents the patterns).
tracked() {
  git ls-files -z | tr '\0' '\n' | grep -v '^tests/security/test-public-surface-names.sh$'
}

log_section "Public surface: deployment-specific 1Password paths"

# op://<vault>/<item>/... where neither segment is placeholder-shaped.
OP_HITS="$(tracked | tr '\n' '\0' | xargs -0 grep -noE 'op://[^/ "'"'"'<>`)]+/[^/ "'"'"'<>`)]+' 2>/dev/null \
  | awk -F: '{
      split($0, a, "op://"); path = a[2]; n = split(path, seg, "/"); v = seg[1]; i = seg[2];
      ph = "^(<|&lt;|\\$|\\{|VAULT|vault|Vault|your|Your|my|My|example|Example|ITEM|item)";
      if (v ~ ph || i ~ ph) next;
      print $1 ":" $2 ": op://" v "/" i
    }' || true)"

if [[ -z "$OP_HITS" ]]; then
  log_pass "no op:// path with a real vault and item name in tracked files"
else
  log_fail "op:// paths with real vault or item names (use op://<vault>/<item>/...):"
  echo "$OP_HITS" | head -20 | sed 's/^/      /'
fi

log_section "Public surface: real home directories"

# /Users/<name> where <name> is not a documentation stand-in.
HOME_HITS="$(tracked | tr '\n' '\0' | xargs -0 grep -noE '/Users/[A-Za-z0-9_.-]+' 2>/dev/null \
  | awk -F: '{
      split($0, a, "/Users/"); name = a[2];
      if (name ~ /^(me|foo|john|jane|test|testuser|dev|someone|probe|alice|bob|you|op|env|user|username|example|name|secret-user|yo|\.\.\.)$/) next;
      print $1 ":" $2 ": /Users/" name
    }' || true)"

if [[ -z "$HOME_HITS" ]]; then
  log_pass "no real home directory path in tracked files"
else
  log_fail "home directory paths that are not documentation stand-ins (use /Users/me):"
  echo "$HOME_HITS" | head -20 | sed 's/^/      /'
fi

echo ""
echo "Passed: $TESTS_PASSED  Failed: $TESTS_FAILED"
if [[ $TESTS_FAILED -gt 0 ]]; then
  exit 1
fi
exit 0
