// Generated by OrchestKit Claude Plugin
// Created: 2026-06-08

// Content-negotiated 404s. A genuinely-unknown path is served as the HTML
// not-found page to browsers, but as a structured RFC 9457-shaped JSON body
// (application/json) to agents — so a programmatic client gets a parseable
// error instead of scraping HTML.
//
// Why: orank's "JSON error responses" check + its agent reviewer both probed
// root-level conventional paths (/checkout_sessions, /.well-known/oauth-*) and
// got HTML 404s. The /api/* catch-all already returns the JSON error; this
// widens the same guarantee to the whole origin without fabricating any
// endpoint — a 404 is the honest answer, just made machine-readable.

// Real top-level paths we serve. Anything outside this set is a true 404, so it
// is safe to answer agents with JSON. Kept in sync with the route tree by
// agent-404.test.ts, which derives the actual routes from app/ and fails if one
// is missing here.
import { INDEXNOW_KEY_PATH } from "./indexnow";

export const SERVED_EXACT: ReadonlySet<string> = new Set([
	"/",
	"/about",
	"/alternatives",
	"/best-claude-code-plugins",
	"/changelog",
	"/community",
	"/claude-agent-sdk-vs-claude-code-plugins",
	"/compare",
	"/factory-ride",
	"/contact",
	"/developers",
	"/mcp-server",
	"/openapi",
	"/pricing",
	"/sdk",
	"/privacy",
	"/status",
	"/terms",
	"/yonyon",
	"/api-policy",
	// Top-level route files (markdown twins, feeds, sitemaps, OG image).
	"/auth.md",
	"/api-policy.md",
	"/pricing.md",
	// Markdown twins of the two name-queried pages (rewritten by middleware to
	// app/api/page-md; listed so the allowlist reads as the full served surface).
	"/developers.md",
	"/developers/llms.txt",
	"/yonyon.md",
	INDEXNOW_KEY_PATH,
	"/llms.txt",
	"/llms-full.txt",
	"/rss.xml",
	"/schema-map.xml",
	"/robots.txt",
	"/sitemap.xml",
	"/opengraph-image",
	"/favicon.svg",
	// next.config rewrites that land on real handlers. Middleware runs BEFORE
	// rewrites, so a rewrite source missing here is answered with a JSON 404 (and
	// an agent:not-found event) before the rewrite ever fires. /mcp shipped that
	// way: POST /mcp returned 404 while POST /api/mcp worked.
	"/ask",
	"/mcp",
	"/mcp.json",
	"/openapi.json",
	// The auth.md identity endpoint (app/agent/identity/route.ts). /agent is
	// not a served prefix, so the exact path has to be listed or middleware
	// answers it with a JSON 404 before the route ever runs.
	"/agent/identity",
	// Specific /.well-known/* paths we actually rewrite to handlers. Listed
	// individually (not as a prefix) so UNKNOWN well-known probes (say
	// /.well-known/openid-configuration, which we don't serve) still get a
	// structured JSON 404 for agents instead of an HTML page. Kept in sync
	// with next.config.mjs by agent-404.test.ts.
	"/.well-known/ard.json",
	"/.well-known/ai-catalog.json",
	"/.well-known/did.json",
	"/.well-known/agent-skills/index.json",
	"/.well-known/oauth-protected-resource",
	"/.well-known/oauth-authorization-server",
	"/.well-known/http-message-signatures-directory",
	"/.well-known/api-catalog",
	"/.well-known/agent-card.json",
	"/.well-known/mcp",
	"/.well-known/mcp/server-card.json",
	"/.well-known/mcp.json",
	"/.well-known/mcp/manifest.json",
	// Actions MCP server card and discovery paths
	"/.well-known/mcp/actions-server-card.json",
	"/.well-known/mcp/actions",
]);

// Prefix-served namespaces (their own routing decides 200 vs structured 404).
export const SERVED_PREFIXES: readonly string[] = [
	"/docs",
	"/api",
	"/_next",
	"/thumbnails",
	// PostHog same-origin proxy (next.config.mjs rewrites /ingest/* to
	// eu.i.posthog.com). This MUST be a prefix, not a set of exact paths.
	// Middleware runs BEFORE rewrites, and PostHog's ingestion endpoints are
	// extensionless — /decide, /flags, /e/, /s/ — so the "has a file extension"
	// escape hatch below does not cover them. Without this entry every captured
	// event 404s here and never reaches PostHog, while /ingest/static/array.js
	// still loads (it has an extension), leaving a site that looks instrumented
	// and records nothing.
	"/ingest",
];

export function isServedPath(pathname: string): boolean {
	if (SERVED_EXACT.has(pathname)) return true;
	for (const prefix of SERVED_PREFIXES) {
		if (pathname === prefix || pathname.startsWith(`${prefix}/`)) return true;
	}
	// Static assets (anything with a file extension) — let Next serve or 404 them
	// natively rather than synthesizing a JSON error for a missing image/font.
	// EXCEPTIONS, in AGENT_DATA_EXTENSIONS below: extensions that are agent data
	// formats rather than binary assets. An unknown one should get a structured,
	// machine-readable 404, not an HTML page. Every such file we actually serve is
	// in SERVED_EXACT / SERVED_PREFIXES above, so excluding them here only
	// reroutes genuine 404s to the machine-readable answer.
	const ext = pathname.match(/\.([a-z0-9]+)$/i)?.[1]?.toLowerCase();
	if (ext && !AGENT_DATA_EXTENSIONS.has(ext)) return true;
	return false;
}

// File extensions that name an agent-readable data format. `.md` matters most:
// the docs tell agents to "append .md to any page URL", so an agent following
// that instruction onto a page without a Markdown twin used to receive the HTML
// not-found page, the exact scrape-the-markup failure the JSON 404 exists to
// prevent. public/ IndexNow key file is listed in SERVED_EXACT. Other unknown
// .txt/.md/.json still get a structured 404.
const AGENT_DATA_EXTENSIONS: ReadonlySet<string> = new Set(["json", "md", "txt"]);

// A request prefers a JSON error unless it is a browser explicitly asking for
// HTML. `*/*` (curl, most SDKs) and JSON-typed Accepts both get JSON.
export function prefersJsonError(accept: string): boolean {
	return !accept.includes("text/html");
}

// Whether middleware should answer this request with a structured JSON 404
// instead of letting it fall through to the HTML not-found page.
export function shouldJsonError(
	method: string,
	pathname: string,
	accept: string,
): boolean {
	if (method === "OPTIONS") return false; // never hijack a CORS preflight
	return !isServedPath(pathname) && prefersJsonError(accept);
}

// A request prefers a Markdown error when it asked for Markdown by any of the
// three routes the site documents: the Accept header, a `.md` suffix, or
// ?mode=agent. Checked BEFORE prefersJsonError so an explicit `text/markdown`
// wins over the JSON default.
export function prefersMarkdownError(
	pathname: string,
	accept: string,
	mode?: string | null,
): boolean {
	return (
		accept.includes("text/markdown") || pathname.endsWith(".md") || mode === "agent"
	);
}
