// Generated by OrchestKit Claude Plugin
// Created: 2026-07-31

// Pure classifiers for server-side agent telemetry. Everything here is a total
// function of the request line + headers, so the whole surface taxonomy is unit
// testable without a request, a runtime, or a network.
//
// The point of the bounded enums: these values become analytics property values.
// An unbounded value (a raw User-Agent, a raw Accept) is a cardinality bomb in
// the properties JSONB and useless as a group-by. Every classifier below maps an
// unbounded input onto a small, closed set.

/** Agent-facing request surfaces worth counting. `null` = not an agent surface. */
export type AgentSurface =
	| "well-known"
	| "openapi"
	| "llms"
	| "md"
	| "search"
	| "ask"
	| "mcp";

/**
 * Classify a pathname onto an agent surface, or `null` for everything else
 * (docs HTML, static assets, the PostHog proxy, Next internals).
 *
 * `null` is the volume gate: middleware runs on nearly every request, and
 * emitting an event for each one would triple first-party ingest volume for no
 * added signal. Only the surfaces an agent actually probes are counted.
 */
export function classifyAgentSurface(pathname: string): AgentSurface | null {
	// MCP first: its discovery documents live under /.well-known, and grouping
	// them with the transport is what makes "did anyone find AND use the MCP
	// server" answerable from one property.
	if (
		pathname === "/mcp" ||
		pathname === "/mcp.json" ||
		pathname === "/api/mcp" ||
		pathname === "/.well-known/mcp" ||
		pathname.startsWith("/.well-known/mcp/") ||
		pathname === "/.well-known/mcp.json"
	) {
		return "mcp";
	}
	if (pathname === "/.well-known" || pathname.startsWith("/.well-known/")) {
		return "well-known";
	}
	if (
		pathname === "/openapi.json" ||
		pathname === "/api/openapi" ||
		pathname === "/api/openapi.json" ||
		pathname === "/api/openapi.yaml" ||
		pathname === "/api/openapi-yaml"
	) {
		return "openapi";
	}
	if (pathname.includes("llms.txt") || pathname.includes("llms-full.txt")) {
		return "llms";
	}
	if (
		pathname === "/api/md" ||
		pathname.startsWith("/api/md/") ||
		pathname.endsWith(".md")
	) {
		return "md";
	}
	if (pathname === "/api/search") return "search";
	if (pathname === "/ask" || pathname === "/api/ask") return "ask";
	// Deliberately NO `/api/*` catch-all. It used to return "api" for every
	// remaining route, which swept in /api/analytics — our own first-party sink.
	// navigator.sendBeacon sends `Accept: */*`, so every search and web-vital
	// beacon the browser fired minted an extra agent:api-request, roughly
	// doubling ingest volume and filing human traffic under the `agent:`
	// namespace this feature exists to isolate. An allowlist of genuinely
	// agent-probed surfaces is the honest gate; a new agent route has to be
	// added here on purpose, which is the same fail-closed shape the playground
	// CI gate uses.
	return null;
}

/** Bounded Accept-header families. */
export type AcceptFamily =
	| "event-stream"
	| "markdown"
	| "html"
	| "json"
	| "wildcard"
	| "none"
	| "other";

export function acceptFamily(accept: string): AcceptFamily {
	const value = accept.trim().toLowerCase();
	if (!value) return "none";
	if (value.includes("text/event-stream")) return "event-stream";
	if (value.includes("text/markdown")) return "markdown";
	// html is checked before json deliberately: a browser Accept lists text/html
	// first and may also carry application/*, so json-first would label browsers
	// as agents.
	if (value.includes("text/html")) return "html";
	if (value.includes("application/json") || value.includes("+json")) {
		return "json";
	}
	if (value === "*/*") return "wildcard";
	return "other";
}

// Ordered longest/most-specific first. A UA that matches nothing collapses to
// "other" rather than leaking the raw string.
const UA_FAMILIES: ReadonlyArray<readonly [string, string]> = [
	["oai-searchbot", "oai-searchbot"],
	["chatgpt-user", "chatgpt-user"],
	["gptbot", "gptbot"],
	["claudebot", "claudebot"],
	["claude-user", "claude-user"],
	["claude-web", "claude-web"],
	["anthropic", "anthropic"],
	["perplexity", "perplexity"],
	["google-extended", "google-extended"],
	["googlebot", "googlebot"],
	["bingbot", "bingbot"],
	["applebot", "applebot"],
	["amazonbot", "amazonbot"],
	["meta-externalagent", "meta-externalagent"],
	["bytespider", "bytespider"],
	["ccbot", "ccbot"],
	["curl", "curl"],
	["wget", "wget"],
	["postman", "postman"],
	["python", "python"],
	["httpx", "python"],
	["aiohttp", "python"],
	["node-fetch", "node"],
	["undici", "node"],
	["axios", "node"],
	["go-http-client", "go"],
	["okhttp", "java"],
	["java/", "java"],
	["ruby", "ruby"],
	["mozilla", "browser-ua"],
];

/** Map a raw User-Agent onto a bounded family name. */
export function uaFamily(userAgent: string | null | undefined): string {
	const value = (userAgent ?? "").trim().toLowerCase();
	if (!value) return "none";
	for (const [needle, family] of UA_FAMILIES) {
		if (value.includes(needle)) return family;
	}
	return "other";
}
