// Generated by OrchestKit Claude Plugin
// Created: 2026-09-19
//
// Shared TypeSafe System One (jev-latest) re-rank helper. One POST evaluates a
// Choice question whose options are the candidate keys; the returned
// probability distribution reorders the whole shortlist in a single request.
//
// Callers gate on jevRerankEnabled(env) + a TYPESAFE_API_KEY; every failure
// mode (no key, timeout, HTTP error, malformed answer) returns null so the
// caller keeps its deterministic order. Never logs the request or the key.

export const JEV_ENDPOINT = "https://api.typesafe.ai/v1/systemone";
export const JEV_TIMEOUT_MS = 3000;

/** ORK_SITE_JEV_RERANK truthy values: "1" | "true" | "yes" | "on". */
export function jevRerankEnabled(env: NodeJS.ProcessEnv = process.env): boolean {
	return ["1", "true", "yes", "on"].includes(
		String(env.ORK_SITE_JEV_RERANK ?? "").toLowerCase(),
	);
}

export type JevRerankDeps = {
	fetchImpl?: typeof fetch;
	apiKey?: string;
	timeoutMs?: number;
};

/**
 * Re-rank `candidates` by one Choice judgment. `context` is merged into the
 * request `state` next to the candidate list so the question sees the same
 * facts the deterministic ranker used. Returns candidate keys ordered by
 * probability desc, or null on ANY failure (caller keeps deterministic order).
 */
export async function jevChoiceOrder(
	opts: {
		instructions: string;
		context: Record<string, unknown>;
		candidates: readonly { key: string; label: string }[];
	},
	deps: JevRerankDeps = {},
): Promise<string[] | null> {
	const fetchImpl = deps.fetchImpl ?? fetch;
	const apiKey = deps.apiKey ?? process.env.TYPESAFE_API_KEY;
	if (!apiKey) return null;

	const body = {
		state: {
			...opts.context,
			candidates: opts.candidates.map((c) => ({ key: c.key, label: c.label })),
		},
		model: "jev-latest",
		questions: {
			pick: {
				type: "choice",
				instructions: opts.instructions,
				criteria: Object.fromEntries(
					opts.candidates.map((c) => [c.key, c.label]),
				),
			},
		},
	};

	let json: unknown;
	try {
		const res = await fetchImpl(JEV_ENDPOINT, {
			method: "POST",
			headers: {
				Authorization: `Bearer ${apiKey}`,
				"Content-Type": "application/json",
			},
			body: JSON.stringify(body),
			signal: AbortSignal.timeout(deps.timeoutMs ?? JEV_TIMEOUT_MS),
		});
		if (!res.ok) return null;
		json = await res.json();
	} catch {
		return null;
	}

	const answer = (json as { answers?: { pick?: unknown } })?.answers?.pick;
	const probs = (answer as { type?: string; probabilities?: Record<string, unknown> })
		?.probabilities;
	if (
		(answer as { type?: string })?.type !== "choice" ||
		!probs ||
		typeof probs !== "object"
	) {
		return null;
	}
	const order = opts.candidates
		.map((c) => ({ key: c.key, p: probs[c.key] }))
		.filter((x): x is { key: string; p: number } => typeof x.p === "number");
	if (order.length !== opts.candidates.length) return null; // missing options = malformed
	return order.sort((a, b) => b.p - a.p).map((x) => x.key);
}
