#!/usr/bin/env bash
# Generated by OrchestKit Claude Plugin
# Created: 2026-05-25

# Test: Every Agent(<name>) declared in an agent's tools: frontmatter must
# resolve to a real agent file in src/agents/.
#
# Why this exists (CC 2.1.147 regression guard, #1942):
#   Pre-2.1.147, plugin agents declaring MORE THAN ONE Agent(...) type in
#   tools: had all but the LAST entry silently dropped during frontmatter
#   parsing — quietly breaking multi-agent dispatch. The fix landed in
#   2.1.147 (repo floor is now 2.1.170). This test pins the expectation:
#   all declared Agent(...) types — especially on multi-Agent agents — are
#   present and resolvable, so a future parser regression OR a stale/typo'd
#   reference fails CI instead of failing silently at dispatch time.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
AGENTS_DIR="$REPO_ROOT/src/agents"

FAILED=0
MULTI_AGENT_COUNT=0

echo "=== Agent multi-Agent tools: retention test (CC 2.1.147 / #1942) ==="
echo ""

for agent_file in "$AGENTS_DIR"/*.md; do
  agent_name=$(basename "$agent_file" .md)

  case "$agent_name" in
    README|INDEX|CONTRIBUTING) continue ;;
  esac

  # All Agent(<name>) references declared in this agent.
  mapfile -t refs < <(grep -oE 'Agent\([a-zA-Z0-9_-]+\)' "$agent_file" \
    | sed -E 's/Agent\(([^)]+)\)/\1/' | sort -u)

  [ "${#refs[@]}" -eq 0 ] && continue

  if [ "${#refs[@]}" -gt 1 ]; then
    MULTI_AGENT_COUNT=$((MULTI_AGENT_COUNT + 1))
    echo "• $agent_name declares ${#refs[@]} Agent() types: ${refs[*]}"
  fi

  for ref in "${refs[@]}"; do
    if [ ! -f "$AGENTS_DIR/$ref.md" ]; then
      echo "FAIL: $agent_name references Agent($ref) but $ref.md does not exist in src/agents/"
      FAILED=1
    fi
  done
done

echo ""
echo "Multi-Agent agents checked: $MULTI_AGENT_COUNT"

if [ "$FAILED" -ne 0 ]; then
  echo "FAIL: one or more Agent(...) references do not resolve"
  exit 1
fi

echo "PASS: all Agent(...) references resolve to real agent files"
exit 0
