// Generated by OrchestKit Claude Plugin
// Created: 2026-05-22

/**
 * Worktree Enter Registrar — WorktreeCreate hook (M168 Phase 4, #1914)
 *
 * When the parent session creates a worktree, record the link in the
 * SQLite registry so the parent can later query child worktree status,
 * and initialize the advisory `children/` bus directory inside the new
 * worktree so the child session can drop progress payloads as it works.
 *
 * The `worktree_links` row uses the worktree_path as the (synthetic)
 * child_sid placeholder until the actual child Claude Code session
 * starts up and registers itself. The exit-finalizer resolves the row
 * by joining `sessions.worktree_path → worktree_links.child_sid` via
 * the placeholder pattern.
 *
 * Hook event: WorktreeCreate (async, timeout: 5s).
 */

import type { HookContext, HookInput, HookResult } from '../types.js';
import { outputSilentSuccess } from '../lib/common.js';
import { NOOP_CTX } from '../lib/context.js';
import { childrenDir } from '../lib/children-bus.js';
import { atomicWriteSync } from '../lib/atomic-write.js';
import { safeIdentifier } from '../lib/safe-fs.js';
import { existsSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';

const HOOK_NAME = 'worktree/enter-registrar';

/**
 * Resolve the (presumed) worktree root path that CC will create.
 * Mirrors the path convention used by worktree-lifecycle-logger.
 */
function resolveWorktreePath(projectDir: string, name: string): string {
  return join(projectDir, '.worktrees', name);
}

export function enterRegistrar(
  input: HookInput,
  ctx: HookContext = NOOP_CTX,
): HookResult {
  const parentSid = input.session_id;
  if (!parentSid) return outputSilentSuccess();

  // Resolve worktree slug + projected path. safeIdentifier() guards against
  // envelope-corrupt names per #1826 / #1250.
  const name = safeIdentifier(input.name, 'unknown');
  const projectDir = input.project_dir || process.cwd();
  const worktreePath = resolveWorktreePath(projectDir, name);

  // Initialize the children/ directory in the new worktree so the child
  // session has a write target ready on first heartbeat. We can't INSERT
  // into worktree_links yet because child_sid is FK to sessions(sid) and
  // the child session does not yet exist — we stash a pending marker that
  // the child's session-registrar (Phase 2 hook) will resolve later, and
  // we drop a .gitkeep into the children/ dir so it survives `git clean`.
  try {
    const dir = childrenDir(worktreePath);
    if (!existsSync(dir)) mkdirSync(dir, { recursive: true, mode: 0o700 });
    const gitkeep = join(dir, '.gitkeep');
    if (!existsSync(gitkeep)) atomicWriteSync(gitkeep, '');
  } catch (err) {
    ctx.log(HOOK_NAME, `children-bus init failed: ${(err as Error).message}`);
  }

  // Stash a pending-link marker under the PARENT project_dir so the child's
  // session-registrar (when it starts up inside <worktreePath>) can read
  // the marker and INSERT the worktree_links row with the real child sid.
  try {
    const pendingDir = join(projectDir, '.claude', 'state', 'worktree-pending');
    const pendingPath = join(pendingDir, `${name}.json`);
    const payload = JSON.stringify({
      parent_sid: parentSid,
      worktree_path: worktreePath,
      name,
      created_at: Math.floor(Date.now() / 1000),
    });
    atomicWriteSync(pendingPath, payload);
  } catch (err) {
    ctx.log(HOOK_NAME, `pending marker write failed: ${(err as Error).message}`);
  }

  // NOTE (#2016): the runner (run-hook.mjs emitHookResult/silentExit, #1990)
  // suppresses this envelope for WorktreeCreate and emits EMPTY stdout — CC
  // reads a WorktreeCreate hook's stdout as the worktree path. Don't change
  // this to emit empty here; suppression is centralized in the runner.
  return outputSilentSuccess();
}
