// Generated by OrchestKit Claude Plugin
// Created: 2026-03-29

/**
 * Agent Attribution Types
 * Issue #1195: Shared types for the branch activity ledger system.
 */

export interface SessionState {
  commit_base: string;
  agent_counter: number;
  agent_starts: Record<string, number>; // agent_id → start timestamp
}

export interface LedgerEntry {
  ts: string;
  agent: string;
  agent_name?: string;
  stage: number; // 0=lead, 1=parallel, 2=follow-up
  duration_ms: number;
  success: boolean;
  summary: string;
  prompt?: string;
  commit_base: string;
  orchestrator?: string;
  background?: boolean;
  /** Path to subagent transcript file (CC 2.1.69+) for post-mortem analysis */
  transcript_path?: string;
}

/** Strip the ork: prefix from agent names if present, to avoid double-prefixing. */
export function normalizeAgentName(agent: string): string {
  return agent.startsWith('ork:') ? agent.slice(4) : agent;
}

export function formatDuration(ms: number): string {
  const secs = Math.round(ms / 1000);
  return `${Math.floor(secs / 60)}m${String(secs % 60).padStart(2, '0')}s`;
}

export const AGENT_ICONS: Record<string, string> = {
  'backend-system-architect': '\u{1f3d7}\ufe0f', 'security-auditor': '\u{1f6e1}\ufe0f',
  'test-generator': '\u{1f9ea}', 'frontend-ui-developer': '\u{1f3a8}',
  'ci-cd-engineer': '\u2699\ufe0f', 'code-quality-reviewer': '\u{1f50d}',
  'database-engineer': '\u{1f4be}', 'accessibility-specialist': '\u267f',
  'workflow-architect': '\u{1f4d0}', 'debug-investigator': '\u{1f52c}',
  'git-operations-engineer': '\u{1f500}', 'deployment-manager': '\u{1f680}',
  'Explore': '\u{1f9ed}', 'general-purpose': '\u{1f916}',
  'product-strategist': '\u{1f4ca}', 'market-intelligence': '\u{1f4c8}',
  'data-pipeline-engineer': '\u{1f527}', 'llm-integrator': '\u{1f9e0}',
  'infrastructure-architect': '\u{1f3db}\ufe0f', 'monitoring-engineer': '\u{1f4e1}',
  'release-engineer': '\u{1f4e6}', 'demo-producer': '\u{1f3ac}',
  'design-system-architect': '\u{1f3a8}', 'component-curator': '\u{1f9e9}',
  'multimodal-specialist': '\u{1f5bc}\ufe0f', 'event-driven-architect': '\u26a1',
  'python-performance-engineer': '\u{1f40d}', 'genui-architect': '\u{1f5a5}\ufe0f',
};

export function getAgentIcon(agent: string): string {
  return AGENT_ICONS[normalizeAgentName(agent)] || '\u{1f916}';
}

export const STAGE_LABELS = ['Lead', '\u26a1 Parallel', 'Follow-up'];
