// Generated by OrchestKit Claude Plugin
// Created: 2026-02-09

/**
 * Cross-Project Analytics — User-Scoped JSONL
 *
 * Writes local-only analytics to ~/.claude/analytics/.
 * Privacy-by-design: no PII, no prompts, no code, no raw paths.
 * Project paths are hashed (12-char SHA256) for irreversible anonymity.
 *
 * Issue #459: Local Cross-Project Analytics System
 */

import { appendFileSync, mkdirSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { getHomeDir, joinPath } from './paths.js';

function getAnalyticsDir(): string {
  return joinPath(getHomeDir(), '.claude', 'analytics');
}

/** Hash project path for privacy — irreversible, 12-char hex */
export function hashProject(projectDir: string): string {
  return createHash('sha256').update(projectDir).digest('hex').slice(0, 12);
}

/** Append a JSONL entry to ~/.claude/analytics/<file>. Fire-and-forget. */
export function appendAnalytics(file: string, entry: Record<string, unknown>): void {
  try {
    const dir = getAnalyticsDir();
    mkdirSync(dir, { recursive: true });
    appendFileSync(joinPath(dir, file), JSON.stringify(entry) + '\n');
  } catch {
    // Never block hooks
  }
}
