// Generated by OrchestKit Claude Plugin
// Created: 2026-03-03

/**
 * Atomic File Write Utility
 *
 * Provides crash-safe file writes using the temp-file + rename pattern
 * (atomic on POSIX) and directory-based locking via mkdir (also atomic on POSIX).
 *
 * Problem: 80+ writeFileSync callsites with zero crash safety. If the process
 * crashes mid-write, the target file is left corrupted/truncated.
 *
 * Solution: Write to a .tmp file first, then rename. If crash happens mid-write,
 * only the .tmp file is corrupted — the original is untouched.
 */

import { writeFileSync, renameSync, mkdirSync, rmdirSync, unlinkSync } from 'node:fs';
import { dirname } from 'node:path';
import { logHook } from './common.js';

const LOCK_TIMEOUT_MS = 5000;
const LOCK_POLL_MS = 50;

/**
 * Atomic write: write to temp file, then rename (atomic on POSIX).
 * If crash happens mid-write, only the .tmp file is corrupted, never the original.
 */
export function atomicWriteSync(filePath: string, data: string, encoding: BufferEncoding = 'utf8'): void {
  const tmpPath = `${filePath}.tmp.${process.pid}`;
  const dir = dirname(filePath);

  // Ensure directory exists — recursive:true is idempotent, no TOCTOU race
  mkdirSync(dir, { recursive: true });

  try {
    writeFileSync(tmpPath, data, encoding);
    renameSync(tmpPath, filePath);  // Atomic on POSIX
  } catch (err) {
    // Clean up temp file on failure
    try { unlinkSync(tmpPath); } catch { /* ignore */ }
    throw err;
  }
}

/**
 * Acquire a directory-based lock (mkdir is atomic on POSIX).
 * Returns true if acquired, false if timeout.
 */
export function acquireLock(lockPath: string, timeoutMs: number = LOCK_TIMEOUT_MS): boolean {
  const deadline = Date.now() + timeoutMs;

  while (Date.now() < deadline) {
    try {
      mkdirSync(lockPath);
      return true;  // Lock acquired
    } catch (err: unknown) {
      if (err instanceof Error && (err as NodeJS.ErrnoException).code === 'EEXIST') {
        // Lock held by someone else — spin wait
        const start = Date.now();
        while (Date.now() - start < LOCK_POLL_MS) { /* busy wait */ }
        continue;
      }
      throw err;  // Unexpected error
    }
  }

  // Timeout — try to break stale lock
  logHook('atomic-write', `Lock timeout on ${lockPath}, breaking stale lock`, 'warn');
  try { rmdirSync(lockPath); } catch { /* ignore */ }
  try {
    mkdirSync(lockPath);
    return true;
  } catch {
    return false;
  }
}

/**
 * Release a directory-based lock.
 */
export function releaseLock(lockPath: string): void {
  try {
    rmdirSync(lockPath);
  } catch {
    // Lock already released or never acquired
  }
}

/**
 * Write with lock: acquire lock, atomic write, release lock.
 * Convenience wrapper for critical sections.
 */
export function lockedAtomicWriteSync(
  filePath: string,
  data: string,
  lockPath?: string,
  encoding: BufferEncoding = 'utf8',
): boolean {
  const effectiveLockPath = lockPath || `${filePath}.lock`;

  if (!acquireLock(effectiveLockPath)) {
    logHook('atomic-write', `Failed to acquire lock for ${filePath}`, 'warn');
    return false;
  }

  try {
    atomicWriteSync(filePath, data, encoding);
    return true;
  } finally {
    releaseLock(effectiveLockPath);
  }
}
