// Generated by OrchestKit Claude Plugin
// Created: 2026-08-24

/**
 * Deferred-debt ledger cache (#3708).
 *
 * The session-start surfacer used to grep the entire project on every
 * instructions-loaded event. That cost multiplies by SESSION COUNT (there is
 * no interval to rate-limit), and a panic reboot restarts every session at
 * once, so the scans land together on a cold machine. Measured at 28.2% CPU
 * per hook process on a box at load 107.
 *
 * This module turns the surfacer into a reader: one `git rev-parse HEAD`, one
 * file read, O(1) per session. A ledger keyed on a HEAD that is no longer
 * current is served anyway, because a session-start banner is advisory and a
 * HEAD-old ledger is correct behaviour, not a bug. When the ledger is missing
 * or keyed on a different HEAD, exactly ONE process on the machine rebuilds it
 * (pidfile lock); the others serve whatever ledger exists, or stay silent.
 *
 * The rebuild itself uses `git grep` (index-aware, skips ignored trees for
 * free) with a plain `grep -r` fallback outside a repository.
 */

import { execFileSync } from 'node:child_process';
import { mkdirSync, readFileSync, renameSync, writeFileSync } from 'node:fs';
import { dirname, isAbsolute, join, relative, resolve } from 'node:path';
import { getCacheDir } from './paths.js';
import { acquirePidLock, releasePidLock } from './pidlock.js';
import { DEBT_SCAN_EXTENSIONS, DEBT_TOKEN, parseDebtComment } from './debt-markers.js';

export const LEDGER_VERSION = 1;
// Total scan hits kept (backstop for huge repos).
export const SCAN_CAP = 50;
const SCAN_TIMEOUT_MS = 5000;
const SCAN_MAX_BUFFER = 4 * 1024 * 1024;
// A rebuild takes seconds; a lock older than this belongs to a crashed holder.
const LOCK_STALE_MS = 2 * 60_000;
// Outside a git repo there is no HEAD to key on; fall back to a daily TTL.
const NO_GIT_HEAD = 'no-git';
const NO_GIT_TTL_MS = 24 * 60 * 60_000;

const EXCLUDE_DIRS = ['node_modules', 'dist', '.git', '.worktrees', 'build', 'vendor', '__tests__'];

export interface LedgerEntry {
  file: string;
  line: number;
  choice: string;
  upgrade?: string;
  trigger?: string;
}

export interface DebtLedger {
  version: number;
  head: string;
  generated_at: string;
  entries: LedgerEntry[];
}

export type LedgerSource = 'cache' | 'scan' | 'stale' | 'locked' | 'error';

export function ledgerPath(): string {
  return join(getCacheDir(), 'debt-ledger.json');
}

function lockPath(): string {
  return `${ledgerPath()}.lock`;
}

/** Current HEAD, or null outside a git repository. */
export function resolveHead(projectDir: string): string | null {
  try {
    const out = execFileSync('git', ['rev-parse', 'HEAD'], {
      cwd: projectDir,
      encoding: 'utf8',
      timeout: 2000,
      stdio: ['ignore', 'pipe', 'ignore'],
      windowsHide: true,
    }).trim();
    return /^[0-9a-f]{40}$/.test(out) ? out : null;
  } catch {
    return null;
  }
}

export function readLedger(): DebtLedger | null {
  try {
    const parsed = JSON.parse(readFileSync(ledgerPath(), 'utf8')) as Partial<DebtLedger>;
    if (
      parsed.version !== LEDGER_VERSION ||
      typeof parsed.head !== 'string' ||
      typeof parsed.generated_at !== 'string' ||
      !Array.isArray(parsed.entries)
    ) {
      return null;
    }
    return parsed as DebtLedger;
  } catch {
    return null;
  }
}

/** Atomic write: temp file + rename, so a reader never sees a torn ledger. */
export function writeLedger(ledger: DebtLedger): void {
  const target = ledgerPath();
  mkdirSync(dirname(target), { recursive: true });
  const tmp = `${target}.${process.pid}.tmp`;
  writeFileSync(tmp, JSON.stringify(ledger, null, 2));
  renameSync(tmp, target);
}

/** Parse `file:line:content` scan lines into entries, relative to projectDir. */
export function parseScanOutput(out: string, projectDir: string): LedgerEntry[] {
  const entries: LedgerEntry[] = [];
  for (const raw of out.split('\n').filter(Boolean).slice(0, SCAN_CAP + 1)) {
    const m = raw.match(/^(.+?):(\d+):(.*)$/);
    if (!m) continue;
    const parsed = parseDebtComment(m[3]);
    if (!parsed) continue;
    const file = isAbsolute(m[1]) ? relative(projectDir, m[1]) || m[1] : m[1];
    entries.push({
      file,
      line: Number.parseInt(m[2], 10),
      choice: parsed.choice,
      upgrade: parsed.upgrade,
      trigger: parsed.trigger,
    });
  }
  return entries;
}

function scanWithGitGrep(projectDir: string): string {
  const pathspecs = [
    ...DEBT_SCAN_EXTENSIONS.map((ext) => `*.${ext}`),
    ...EXCLUDE_DIRS.map((d) => `:(exclude,glob)**/${d}/**`),
  ];
  try {
    return execFileSync(
      'git',
      ['grep', '-n', '-E', '-I', '--untracked', '-e', `${DEBT_TOKEN}:`, '--', ...pathspecs],
      {
        cwd: projectDir,
        encoding: 'utf8',
        timeout: SCAN_TIMEOUT_MS,
        maxBuffer: SCAN_MAX_BUFFER,
        stdio: ['ignore', 'pipe', 'ignore'],
        windowsHide: true,
      }
    );
  } catch (error: unknown) {
    // git grep exits 1 for "no matches", which is a valid empty result.
    if ((error as { status?: number }).status === 1) return '';
    throw error;
  }
}

function scanWithGrep(projectDir: string): string {
  const args = [
    '-rnE',
    ...DEBT_SCAN_EXTENSIONS.map((ext) => `--include=*.${ext}`),
    ...EXCLUDE_DIRS.map((d) => `--exclude-dir=${d}`),
    '--',
    `${DEBT_TOKEN}:`,
    projectDir,
  ];
  try {
    return execFileSync('grep', args, {
      encoding: 'utf8',
      timeout: SCAN_TIMEOUT_MS,
      maxBuffer: SCAN_MAX_BUFFER,
      stdio: ['ignore', 'pipe', 'ignore'],
      windowsHide: true,
    });
  } catch (error: unknown) {
    if ((error as { status?: number }).status === 1) return '';
    throw error;
  }
}

/** Full-project scan. Throws on tool failure; callers treat that as "no ledger". */
export function scanProject(projectDir: string, inGitRepo: boolean): LedgerEntry[] {
  const out = inGitRepo ? scanWithGitGrep(projectDir) : scanWithGrep(projectDir);
  return parseScanOutput(out, projectDir);
}

function isFresh(ledger: DebtLedger, head: string): boolean {
  if (ledger.head !== head) return false;
  if (head !== NO_GIT_HEAD) return true;
  return Date.now() - Date.parse(ledger.generated_at) < NO_GIT_TTL_MS;
}

/**
 * The O(1) read path with a single-flight rebuild. Never throws.
 * `stale` means a HEAD-old ledger was served because a rebuild was not
 * possible right now (lock held by another session, or the scan failed).
 */
export function loadOrBuildLedger(projectDir: string): { ledger: DebtLedger | null; source: LedgerSource } {
  const resolved = resolveHead(projectDir);
  const head = resolved ?? NO_GIT_HEAD;
  const cached = readLedger();
  if (cached && isFresh(cached, head)) {
    return { ledger: cached, source: 'cache' };
  }

  const lock = lockPath();
  let locked = false;
  try {
    mkdirSync(dirname(lock), { recursive: true });
    locked = acquirePidLock(lock, LOCK_STALE_MS);
  } catch {
    locked = false;
  }
  if (!locked) {
    return { ledger: cached, source: cached ? 'stale' : 'locked' };
  }

  try {
    const entries = scanProject(projectDir, resolved !== null);
    const ledger: DebtLedger = {
      version: LEDGER_VERSION,
      head,
      generated_at: new Date().toISOString(),
      entries,
    };
    writeLedger(ledger);
    return { ledger, source: 'scan' };
  } catch {
    return { ledger: cached, source: cached ? 'stale' : 'error' };
  } finally {
    releasePidLock(lock);
  }
}

/**
 * O(1) producer for the write path: replace one file's entries after it was
 * written. Best-effort and silent; a missing ledger is left missing (the next
 * session start rebuilds it under the lock).
 */
export function updateLedgerForFile(projectDir: string, filePath: string, text: string): void {
  try {
    const ledger = readLedger();
    if (!ledger) return;
    const abs = isAbsolute(filePath) ? filePath : resolve(projectDir, filePath);
    const file = relative(projectDir, abs) || abs;
    const fresh: LedgerEntry[] = [];
    text.split('\n').forEach((line, i) => {
      const parsed = parseDebtComment(line);
      if (!parsed) return;
      fresh.push({ file, line: i + 1, choice: parsed.choice, upgrade: parsed.upgrade, trigger: parsed.trigger });
    });
    const kept = ledger.entries.filter((e) => e.file !== file);
    if (kept.length === ledger.entries.length && fresh.length === 0) return;
    writeLedger({ ...ledger, entries: [...kept, ...fresh] });
  } catch {
    // best-effort
  }
}
