// Generated by OrchestKit Claude Plugin
// Created: 2026-07-15

/**
 * Learned-patterns distilled cache (P4-B3)
 *
 * The PermissionRequest hot path (<10ms budget) must not parse the full
 * learned-patterns.json on every request. Instead, an async SessionStart hook
 * (lifecycle/pattern-sync-pull — the owner of learned-patterns.json) distills
 * the file into a tiny (<2KB) versioned cache that the permission hook reads
 * with a single small readFileSync.
 *
 * Contract:
 * - Writer: distillLearnedPatterns() — SessionStart only. Recomputes the cache
 *   from learned-patterns.json, or REMOVES it when the source is missing /
 *   unreadable / oversized (a stale cache must never outlive its source —
 *   these are auto-approve patterns, staleness is security-relevant).
 * - Reader: readDistilledPatterns() — permission hot path. Single readFileSync
 *   of the tiny file; returns null on ANY problem so the caller can fall back
 *   to legacy behavior once (fail-open, advisory).
 *
 * SEC: Both source and cache are UNTRUSTED on read. Every entry is re-validated
 * (string, 1..200 chars) on both sides; no regex construction from file data.
 */

import { existsSync, readFileSync, rmSync, statSync } from 'node:fs';
import { join } from 'node:path';
import { getPluginRoot } from './paths.js';
import { atomicWriteSync } from './atomic-write.js';

/** Versioned schema key — bump when the cache shape changes. */
export const LEARNED_PATTERNS_CACHE_SCHEMA = 'ork.learned-patterns-cache.v1';

/** Hard ceiling on the serialized cache payload. */
export const LEARNED_PATTERNS_CACHE_MAX_BYTES = 2048;

/** Refuse to hot-path-parse a cache file bigger than this (tampering guard). */
const CACHE_READ_MAX_BYTES = 8192;

/** Top-N patterns kept in the distilled cache. */
const MAX_CACHED_PATTERNS = 50;

/** Per-pattern validity bounds — mirrors learning-tracker's match-time checks. */
const MAX_PATTERN_LENGTH = 200;

/** Refuse to parse a source file bigger than this at SessionStart. */
const SOURCE_MAX_BYTES = 1024 * 1024; // 1MB — matches pattern-sync-pull guard

/**
 * Full learned-patterns file — the same path learning-tracker historically read.
 */
export function getLearnedPatternsFile(): string {
  return join(getPluginRoot(), '.claude', 'feedback', 'learned-patterns.json');
}

/**
 * Tiny distilled cache, co-located with the source file.
 * NOTE: filename deliberately does NOT contain the substring
 * "learned-patterns.json" (tests key on that substring for the source file).
 */
export function getLearnedPatternsCacheFile(): string {
  return join(getPluginRoot(), '.claude', 'feedback', 'learned-patterns-cache.json');
}

/** Validate one pattern entry (shared by writer and reader). */
function isValidPattern(p: unknown): p is string {
  return typeof p === 'string' && p.trim().length > 0 && p.length <= MAX_PATTERN_LENGTH;
}

/** Remove the cache file; never throws (fs may even be partially mocked). */
function invalidateCache(cacheFile: string): void {
  try {
    rmSync(cacheFile, { force: true });
  } catch {
    // Ignore — worst case the reader's schema check rejects a stale cache
  }
}

/**
 * Distill learned-patterns.json into the tiny cache file.
 * Call from an async SessionStart hook only (parses the full source file).
 *
 * @returns true when a fresh cache was written, false when the cache was
 *          invalidated instead (source missing/unreadable/oversized).
 */
export function distillLearnedPatterns(): boolean {
  const sourceFile = getLearnedPatternsFile();
  const cacheFile = getLearnedPatternsCacheFile();

  try {
    if (!existsSync(sourceFile)) {
      invalidateCache(cacheFile);
      return false;
    }
    // SEC: untrusted input — never parse an oversized source
    const stats = statSync(sourceFile);
    if (stats.size > SOURCE_MAX_BYTES) {
      invalidateCache(cacheFile);
      return false;
    }

    const data = JSON.parse(readFileSync(sourceFile, 'utf8')) as {
      autoApprovePatterns?: unknown;
    };
    const raw = Array.isArray(data.autoApprovePatterns) ? data.autoApprovePatterns : [];

    // Validate, dedupe, cap count, then cap serialized size
    const seen = new Set<string>();
    const valid: string[] = [];
    for (const p of raw) {
      if (!isValidPattern(p)) continue;
      const trimmed = p.trim();
      if (seen.has(trimmed)) continue;
      seen.add(trimmed);
      valid.push(trimmed);
      if (valid.length >= MAX_CACHED_PATTERNS) break;
    }

    const serialize = (patterns: string[]): string =>
      JSON.stringify({
        schema: LEARNED_PATTERNS_CACHE_SCHEMA,
        generated_at: new Date().toISOString(),
        autoApprovePatterns: patterns,
      });

    let kept = valid;
    while (kept.length > 0 && Buffer.byteLength(serialize(kept), 'utf8') > LEARNED_PATTERNS_CACHE_MAX_BYTES) {
      kept = kept.slice(0, kept.length - 1);
    }

    atomicWriteSync(cacheFile, serialize(kept));
    return true;
  } catch {
    // Fail-safe: no cache beats a wrong cache — reader falls back to source
    invalidateCache(cacheFile);
    return false;
  }
}

/**
 * Read the distilled cache. Hot-path safe: exactly one small readFileSync,
 * no existsSync (ENOENT is the fast bail).
 *
 * @returns validated patterns, or null when the cache is absent/invalid so
 *          the caller can fall back to legacy behavior (fail-open).
 */
export function readDistilledPatterns(): string[] | null {
  try {
    const raw = readFileSync(getLearnedPatternsCacheFile(), 'utf8');
    // SEC: cache is untrusted too — refuse oversized/tampered files
    if (typeof raw !== 'string' || raw.length > CACHE_READ_MAX_BYTES) return null;

    const parsed = JSON.parse(raw) as { schema?: unknown; autoApprovePatterns?: unknown };
    if (parsed?.schema !== LEARNED_PATTERNS_CACHE_SCHEMA) return null;
    if (!Array.isArray(parsed.autoApprovePatterns)) return null;

    return parsed.autoApprovePatterns.filter(isValidPattern).map((p) => p.trim());
  } catch {
    return null;
  }
}
