// Generated by OrchestKit Claude Plugin
// Created: 2026-05-22

/**
 * Session Registry — M168 Layer 1 (#1912). Coordination DB at
 * ~/.local/state/orchestkit/sessions.db, shared across all CC sessions.
 * Tables (sqlite-migrations/001-initial.sql): sessions, locks,
 * settings_overrides, worktree_links. Reads are lock-free (WAL); writes
 * serialize via BEGIN IMMEDIATE + writeWithRetry on SQLITE_BUSY.
 *
 * Engine (#2003/#2005): hooks ship as esbuild bundles WITHOUT node_modules, so
 * this MUST NOT use a native npm dep — the old top-level `better-sqlite3` import
 * threw ERR_MODULE_NOT_FOUND at load and killed every hook in the bundle. Uses
 * the built-in `node:sqlite` (Node >=22.5, no flag), loaded lazily + guarded so
 * the bundle still loads on older Node (registry no-ops there).
 */

// TYPE-ONLY import — erased by esbuild. Value loaded lazily in newDatabase().
import type { DatabaseSync } from 'node:sqlite';
import { createRequire } from 'node:module';
import { existsSync, mkdirSync, renameSync, statSync } from 'node:fs';
import { join } from 'node:path';
import { getHomeDir } from './paths.js';
import { runMigrations } from './sqlite-migrations/index.js';

const _require = createRequire(import.meta.url);

// Drop the one-time "SQLite is an experimental feature" warning (stderr noise);
// we pin to the stable exec/prepare surface. Every other warning passes through.
const _emitWarning = process.emitWarning.bind(process);
(process as { emitWarning: typeof process.emitWarning }).emitWarning = ((w: string | Error, ...a: unknown[]) => {
  const msg = typeof w === 'string' ? w : w?.message;
  if (msg?.includes('SQLite is an experimental feature')) return;
  (_emitWarning as (w: string | Error, ...a: unknown[]) => void)(w, ...a);
}) as typeof process.emitWarning;

/**
 * Raised when `node:sqlite` can't be loaded (Node < 22.5). Callers treat it as
 * "registry unavailable" and no-op rather than crash, so the bundle still loads.
 */
export class SqliteUnavailableError extends Error {
  constructor(cause: unknown) {
    super('SQLite engine unavailable (node:sqlite requires Node >= 22.5)');
    this.name = 'SqliteUnavailableError';
    (this as { cause?: unknown }).cause = cause;
  }
}

/** Lazily construct a DB via built-in node:sqlite (dynamic require → not bundled). */
function newDatabase(dbPath: string): DatabaseSync {
  try {
    const { DatabaseSync: DB } = _require('node:sqlite') as {
      DatabaseSync: new (path: string) => DatabaseSync;
    };
    return new DB(dbPath);
  } catch (err) {
    throw new SqliteUnavailableError(err);
  }
}

/** Per-row types matching the schema in 001-initial.sql. */
export interface SessionRow {
  sid: string;
  pid: number;
  cwd: string;
  repo_hash: string;
  repo_path: string;
  worktree_path: string | null;
  branch: string | null;
  parent_sid: string | null;
  status: string;
  started_at: number;
  last_heartbeat: number;
  ended_at: number | null;
  cc_version: string | null;
  ork_version: string | null;
}

export interface LockRow {
  name: string;
  holder_sid: string;
  acquired_at: number;
  expires_at: number;
}

export interface SettingsOverrideRow {
  sid: string;
  key: string;
  value: string;
  set_at: number;
}

export interface WorktreeLinkRow {
  child_sid: string;
  parent_sid: string;
  purpose: string | null;
  created_at: number;
  result_status: string | null;
  result_payload: string | null;
}

// Path constants — exported for tests + hooks that need to override.
export const DB_DIR = join(getHomeDir(), '.local', 'state', 'orchestkit');
export const DB_PATH = join(DB_DIR, 'sessions.db');

/** Resolve the active DB path. Respects ORK_SESSION_DB env override (tests). */
function resolveDbPath(): string {
  return process.env.ORK_SESSION_DB || DB_PATH;
}

/** Resolve the active DB directory based on the (possibly overridden) DB path. */
function resolveDbDir(dbPath: string): string {
  const idx = dbPath.lastIndexOf('/');
  if (idx === -1) return '.';
  return dbPath.slice(0, idx) || '/';
}

/** Apply the canonical pragma set. node:sqlite has no .pragma() — use exec(). */
function applyPragmas(db: DatabaseSync): void {
  // busy_timeout MUST be set first: unlike better-sqlite3, node:sqlite has no
  // default busy handling, so switching journal_mode=WAL under concurrency
  // throws "database is locked" immediately unless a timeout is already armed.
  db.exec('PRAGMA busy_timeout = 5000');
  db.exec('PRAGMA journal_mode = WAL');
  db.exec('PRAGMA synchronous = NORMAL');
  db.exec('PRAGMA foreign_keys = ON');
  db.exec('PRAGMA temp_store = MEMORY');
  db.exec('PRAGMA cache_size = -16000');
  db.exec('PRAGMA wal_autocheckpoint = 100');
  db.exec('PRAGMA mmap_size = 268435456');
}

/**
 * Run PRAGMA integrity_check; quarantine the DB if it returns anything other
 * than the single-row "ok" result. Returns true if quarantined (caller reopens).
 */
function checkIntegrityOrQuarantine(db: DatabaseSync, dbPath: string): boolean {
  let rows: unknown[];
  try {
    // node:sqlite reads a pragma result via a prepared statement, not .pragma().
    rows = db.prepare('PRAGMA integrity_check').all() as unknown[];
  } catch {
    rows = []; // integrity check itself crashed — treat as corrupt
  }
  const ok = rows.length === 1
    && typeof rows[0] === 'object'
    && rows[0] !== null
    && (rows[0] as { integrity_check?: string }).integrity_check === 'ok';
  if (ok) return false;

  try {
    db.close();
  } catch {
    /* ignore */
  }
  const corrupt = `${dbPath}.corrupt-${Date.now()}`;
  try {
    if (existsSync(dbPath)) renameSync(dbPath, corrupt);
    for (const sfx of ['-wal', '-shm']) { // WAL + SHM sidecars may also be hosed
      const side = dbPath + sfx;
      if (existsSync(side)) renameSync(side, corrupt + sfx);
    }
  } catch {
    /* best-effort — if rename fails the next open will retry */
  }
  return true;
}

/**
 * Open (or create) the session DB, apply pragmas, run integrity check (with
 * auto-quarantine), and run pending migrations. Prefer getOrCreateDb().
 */
export function openDb(): DatabaseSync {
  const dbPath = resolveDbPath();
  const dbDir = resolveDbDir(dbPath);
  if (!existsSync(dbDir)) {
    mkdirSync(dbDir, { recursive: true, mode: 0o700 });
  }

  let db = newDatabase(dbPath);
  applyPragmas(db);

  // Skip integrity check on a brand-new (zero-byte) DB — nothing to corrupt.
  let isFresh = true;
  try {
    isFresh = statSync(dbPath).size === 0;
  } catch {
    isFresh = true;
  }
  if (!isFresh && checkIntegrityOrQuarantine(db, dbPath)) {
    db = newDatabase(dbPath); // re-open on a fresh file
    applyPragmas(db);
  }

  runMigrations(db);
  return db;
}

// Module-scoped singleton — opened lazily, reused within a (short-lived) hook
// process, so no long-term GC concern.
let _db: DatabaseSync | null = null;

/** Lazily open + cache the DB handle for the current process. */
export function getOrCreateDb(): DatabaseSync {
  if (_db === null) {
    _db = openDb();
  }
  return _db;
}

/** Reset the cached handle (tests only). */
export function __resetDbForTests(): void {
  if (_db !== null) {
    try {
      _db.close();
    } catch {
      /* ignore */
    }
    _db = null;
  }
}

/** SQLITE_BUSY extended result codes that mean "retry the write". */
const SQLITE_BUSY = 5;
const SQLITE_BUSY_SNAPSHOT = 261;

/** True if `err` is a transient SQLITE_BUSY worth retrying. */
function isBusyError(err: unknown): boolean {
  // node:sqlite throws with numeric .errcode; keep legacy string .code too.
  const e = err as { errcode?: number; code?: string };
  if (e?.errcode === SQLITE_BUSY || e?.errcode === SQLITE_BUSY_SNAPSHOT) return true;
  return e?.code === 'SQLITE_BUSY' || e?.code === 'SQLITE_BUSY_SNAPSHOT';
}

/**
 * Wrap a write in BEGIN IMMEDIATE with jittered backoff on SQLITE_BUSY (15
 * retries, 20-150ms each, ~1.3s worst case). Non-busy errors re-throw.
 * BEGIN IMMEDIATE takes the RESERVED lock up front so busy surfaces at BEGIN.
 */
export function writeWithRetry<T>(fn: (db: DatabaseSync) => T): T {
  const db = getOrCreateDb();
  const MAX_RETRIES = 15;
  let lastErr: unknown;
  for (let attempt = 0; attempt < MAX_RETRIES; attempt++) {
    try {
      db.exec('BEGIN IMMEDIATE');
      try {
        const result = fn(db);
        db.exec('COMMIT');
        return result;
      } catch (err) {
        try { db.exec('ROLLBACK'); } catch { /* ignore */ }
        throw err;
      }
    } catch (err) {
      lastErr = err;
      if (!isBusyError(err)) throw err;
      // Synchronous jittered backoff (20-150ms) — hooks + DatabaseSync are sync.
      const end = Date.now() + 20 + Math.floor(Math.random() * 130);
      while (Date.now() < end) {
        /* spin */
      }
    }
  }
  throw lastErr instanceof Error ? lastErr : new Error('writeWithRetry: exhausted retries');
}

/**
 * Record a skill invocation for usage analytics (#2010). Best-effort: every
 * failure is swallowed — SqliteUnavailableError on Node < 22.5, a missing
 * sessions row (FK), or exhausted retries — so a hook never crashes because
 * analytics couldn't write. No-ops on an empty sessionId/skill.
 */
export function recordInvocation(sessionId: string, skill: string, invokedAt: number = Date.now()): void {
  if (!sessionId || !skill) return;
  try {
    writeWithRetry(db =>
      db
        .prepare('INSERT INTO skill_invocation (session_id, skill, invoked_at) VALUES (?, ?, ?)')
        .run(sessionId, skill, invokedAt),
    );
  } catch {
    /* best-effort analytics — never propagate */
  }
}

/** Exposed for tests. */
export const __internals = {
  applyPragmas,
  checkIntegrityOrQuarantine,
  isBusyError,
  resolveDbPath,
  resolveDbDir,
};
