// Generated by OrchestKit Claude Plugin
// Created: 2026-06-12

/**
 * Session Identity (state) — per-session lifecycle for the haiku auto-rename
 * + auto-color flow. Called from prompt/unified-dispatcher every turn.
 *
 * Flow:
 *   turn 1: append deterministic hash-based agent-color record (instant
 *           visual distinction), spawn the detached haiku generator, then
 *           OPTIONALLY block briefly for its result (RC1, opt-in — see below)
 *   turn N: when the generator's JSON lands, adopt its title (prompt bar)
 *           and upgrade the color record if haiku chose a different one
 *
 * RC1 (harvest-miss): the title is normally pulled on the NEXT turn, but the
 * detached child finishes ~6-7s later and short sessions never send another
 * prompt in time (only 7.3% of sessions adopted the title before this fix).
 * Set ORK_SESSION_IDENTITY_WAIT_MS=<ms> to make turn 1 block up to that long
 * for the result so it lands on the first turn. Default 0 (off) — 6-7s is too
 * slow to block every first prompt; with the RC2 child fix the lazy next-turn
 * pull now succeeds reliably on its own for multi-turn sessions.
 *
 * Everything fails open: a dead `claude` binary, auth failure, malformed
 * JSON, or unwritable transcript only means the session keeps its branch
 * title and hash color.
 */

import {
  appendFileSync,
  existsSync,
  mkdirSync,
  readFileSync,
  rmSync,
  statSync,
  writeFileSync,
} from 'node:fs';
import { join } from 'node:path';
import { homedir } from 'node:os';
import type { HookContext, HookInput } from '../types.js';
import {
  CHILD_ENV_MARKER,
  hashColor,
  parseIdentityOutput,
  spawnIdentityGenerator,
  titleWithColor,
  type SessionColor,
  type SessionIdentity,
} from './session-identity.js';

/** Env kill-switch. Set ORK_SESSION_IDENTITY=0 to disable entirely. */
const ENV_KILL_SWITCH = 'ORK_SESSION_IDENTITY';

/**
 * Opt-in inline wait (RC1). Set to a millisecond budget to block turn 1 for the
 * generator so the title lands on the FIRST prompt instead of a later one.
 * Default 0/unset = no wait. Capped at INLINE_WAIT_CEILING_MS to stay under the
 * dispatcher's hook timeout.
 */
const ENV_INLINE_WAIT_MS = 'ORK_SESSION_IDENTITY_WAIT_MS';

/** Hard ceiling for the opt-in inline wait, below the dispatcher hook timeout. */
const INLINE_WAIT_CEILING_MS = 10_000;

/** Poll interval while inline-waiting for the generator's output. */
const INLINE_WAIT_POLL_MS = 250;

/** Give the generator this long before declaring its output unusable. */
const GENERATOR_STALE_MS = 120_000;

const FILE_RAW = 'session-identity.raw';
const FILE_PARSED = 'session-identity.json';
const FILE_SPAWNED = 'session-identity.spawned';
const FILE_COLOR_APPLIED = 'session-identity.color';
const FILE_TOMBSTONE = 'session-identity.failed';
/** Regeneration baseline: the branch the current title was generated on, plus a
 *  per-prompt turn counter, so we can detect a direction change. */
const FILE_META = 'session-identity.meta';

/**
 * Turns-based refresh (opt-in). Set ORK_SESSION_IDENTITY_REFRESH_TURNS=<n> to
 * regenerate the topic every <n> prompts even without a branch change — catches
 * a long single-branch session whose work drifts across topics. Default unset =
 * off (branch change is the only always-on trigger). A regenerate re-runs the
 * detached haiku generator; it never blocks, and the new title still flows
 * through the dispatcher's /rename guard, so an explicit /rename always wins.
 */
const ENV_REFRESH_TURNS = 'ORK_SESSION_IDENTITY_REFRESH_TURNS';

/**
 * Resolve the session transcript path. Prefer the envelope's transcript_path;
 * fall back to the documented layout ~/.claude/projects/<cwd-slug>/<id>.jsonl
 * (slug = cwd with every non-alphanumeric char mapped to '-').
 */
export function resolveTranscriptPath(
  input: HookInput,
  projectDir: string | undefined,
): string | null {
  if (input.transcript_path && existsSync(input.transcript_path)) {
    return input.transcript_path;
  }
  if (!projectDir || !input.session_id) return null;
  const slug = projectDir.replace(/[^a-zA-Z0-9]/g, '-');
  const candidate = join(homedir(), '.claude', 'projects', slug, `${input.session_id}.jsonl`);
  return existsSync(candidate) ? candidate : null;
}

/**
 * Append the exact record `/color` writes (verified against the CC 2.1.175
 * binary: `{type:"agent-color",agentColor,sessionId}`; the session-list
 * reader takes the last record per sessionId). Single-line O_APPEND write —
 * atomic at this size, safe to interleave with CC's own appends.
 */
export function appendAgentColorRecord(
  transcriptPath: string,
  sessionId: string,
  color: SessionColor,
): boolean {
  try {
    const record = `${JSON.stringify({ type: 'agent-color', agentColor: color, sessionId })}\n`;
    appendFileSync(transcriptPath, record, 'utf8');
    return true;
  } catch {
    return false;
  }
}

/**
 * Drive the identity lifecycle for this turn. Returns the AI title once it's
 * available (the dispatcher merges it into sessionTitle), else null.
 *
 * State files live in the per-session storage dir the dispatcher already
 * uses (same tree as once-flags / last-session-title.txt).
 */
export function manageSessionIdentity(
  input: HookInput,
  ctx: HookContext,
  sessionDir: string,
  projectDir: string | undefined,
): string | null {
  try {
    if (process.env[ENV_KILL_SWITCH] === '0') return null;
    if (process.env[CHILD_ENV_MARKER] === '1') return null;
    if (!input.session_id) return null;

    const parsedPath = join(sessionDir, FILE_PARSED);
    const rawPath = join(sessionDir, FILE_RAW);
    const spawnedPath = join(sessionDir, FILE_SPAWNED);
    const colorAppliedPath = join(sessionDir, FILE_COLOR_APPLIED);
    const tombstonePath = join(sessionDir, FILE_TOMBSTONE);

    // 0. Regeneration: has the session's direction changed since the title was
    //    generated? If so, drop the cached identity so the flow below re-spawns
    //    the generator with the current branch + prompt. Never touches the color
    //    file (color stays stable for the session). The regenerated title still
    //    passes through the dispatcher's /rename guard, so a manual rename wins.
    if (shouldRegenerateIdentity(sessionDir, ctx.branch || '')) {
      for (const p of [parsedPath, rawPath, spawnedPath, tombstonePath]) {
        try {
          if (existsSync(p)) rmSync(p);
        } catch {
          /* fail open — a leftover file just delays regeneration one turn */
        }
      }
      ctx.log('session-identity', `direction changed → regenerating title (branch=${ctx.branch})`);
    }

    // 1. Identity already parsed → ensure color upgrade applied, return title.
    if (existsSync(parsedPath)) {
      const identity = parseIdentityOutput(readFileSync(parsedPath, 'utf8'));
      if (!identity) return null;
      applyColorOnce(input, projectDir, identity.color, colorAppliedPath, ctx);
      return titleWithColor(identity);
    }

    if (existsSync(tombstonePath)) return null;

    // 2. Generator spawned earlier → try to harvest its output.
    if (existsSync(spawnedPath)) {
      if (!existsSync(rawPath)) return null;
      const raw = readFileSync(rawPath, 'utf8');
      const identity = parseIdentityOutput(raw);
      if (identity) {
        writeFileSync(parsedPath, JSON.stringify(identity), 'utf8');
        applyColorOnce(input, projectDir, identity.color, colorAppliedPath, ctx);
        ctx.log('session-identity', `haiku identity ready: "${identity.title}" (${identity.color})`);
        return titleWithColor(identity);
      }
      // Unparseable + stale → stop checking every turn.
      try {
        const age = Date.now() - statSync(rawPath).mtimeMs;
        if (age > GENERATOR_STALE_MS && raw.length > 0) {
          writeFileSync(tombstonePath, raw.slice(0, 500), 'utf8');
          ctx.log('session-identity', 'generator output unparseable — giving up for this session', 'warn');
        }
      } catch {
        /* stat raced — retry next turn */
      }
      return null;
    }

    // 3. First turn: instant hash color + kick off the generator.
    if (!existsSync(sessionDir)) mkdirSync(sessionDir, { recursive: true });
    const fallback = hashColor(input.session_id);
    applyColorOnce(input, projectDir, fallback, colorAppliedPath, ctx);
    if (input.prompt && spawnIdentityGenerator(input.prompt, ctx.branch || '', rawPath, projectDir, ctx)) {
      writeFileSync(spawnedPath, new Date().toISOString(), 'utf8');
      // RC1 (opt-in): block briefly so the title can land on THIS turn.
      const inline = inlineHarvest(rawPath, parsedPath, colorAppliedPath, input, projectDir, ctx);
      if (inline) return inline;
    }
    return null;
  } catch (error) {
    ctx.log('session-identity', `failed open: ${error}`, 'warn');
    return null;
  }
}

interface IdentityMeta {
  /** branch the current title was generated on */
  branch: string;
  /** total prompts seen this session (incremented every call) */
  turns: number;
  /** turns value at the last generation, for the turns-based refresh */
  genTurn: number;
}

/**
 * Decide whether to regenerate the session title, and advance the per-session
 * meta baseline. Called once per prompt BEFORE the cached-identity short-circuit.
 *
 * Triggers (either fires):
 *   - branch changed since the title was generated (always on) — a new branch is
 *     a new piece of work. Ignores the 'unknown'/empty git fallback so a
 *     momentarily-unavailable branch never forces a spurious regenerate.
 *   - ORK_SESSION_IDENTITY_REFRESH_TURNS=n set and n prompts elapsed since the
 *     last generation (opt-in) — catches topic drift on a long single-branch
 *     session.
 *
 * Fail-open: any I/O error returns false (keep the current title). The meta file
 * is best-effort; a missing baseline just seeds from the current turn.
 */
function shouldRegenerateIdentity(sessionDir: string, liveBranch: string): boolean {
  try {
    const metaPath = join(sessionDir, FILE_META);
    let meta: IdentityMeta | null = null;
    if (existsSync(metaPath)) {
      try {
        meta = JSON.parse(readFileSync(metaPath, 'utf8')) as IdentityMeta;
      } catch {
        meta = null; // corrupt → reseed below
      }
    }

    const branch = (liveBranch || '').trim();
    const branchKnown = branch !== '' && branch !== 'unknown';

    // First time (or corrupt meta): seed the baseline, never regenerate now.
    if (!meta || typeof meta.turns !== 'number') {
      writeMeta(metaPath, { branch: branchKnown ? branch : '', turns: 1, genTurn: 1 });
      return false;
    }

    const turns = meta.turns + 1;
    let regen = false;

    // Branch change (only when both old and new are real branches).
    if (branchKnown && meta.branch && meta.branch !== '' && branch !== meta.branch) {
      regen = true;
    }

    // Turns-based refresh (opt-in).
    const refreshTurns = Number(process.env[ENV_REFRESH_TURNS] ?? '0');
    if (!regen && Number.isFinite(refreshTurns) && refreshTurns > 0) {
      if (turns - meta.genTurn >= refreshTurns) regen = true;
    }

    writeMeta(metaPath, {
      // Adopt the live branch as the new baseline once it's known; otherwise keep
      // the old one so a transient 'unknown' doesn't reset branch tracking.
      branch: branchKnown ? branch : meta.branch,
      turns,
      genTurn: regen ? turns : meta.genTurn,
    });
    return regen;
  } catch {
    return false; // fail-open: keep the current title
  }
}

function writeMeta(metaPath: string, meta: IdentityMeta): void {
  try {
    writeFileSync(metaPath, JSON.stringify(meta), 'utf8');
  } catch {
    /* best-effort — a missing baseline just reseeds next turn */
  }
}

/**
 * Synchronous sleep (no busy-loop) — the hook process does nothing else while
 * waiting, so blocking is fine. Uses Atomics.wait on a throwaway buffer.
 */
function sleepSync(ms: number): void {
  Atomics.wait(new Int32Array(new SharedArrayBuffer(4)), 0, 0, ms);
}

/**
 * Opt-in (RC1): poll the generator's raw output for up to
 * ORK_SESSION_IDENTITY_WAIT_MS (capped) and adopt the identity on turn 1 if it
 * lands. Returns the emoji-prefixed title, or null when disabled / timed out
 * (the caller then falls back to the lazy next-turn pull). Fail-open.
 */
function inlineHarvest(
  rawPath: string,
  parsedPath: string,
  colorAppliedPath: string,
  input: HookInput,
  projectDir: string | undefined,
  ctx: HookContext,
): string | null {
  const requested = Number(process.env[ENV_INLINE_WAIT_MS] ?? '0');
  if (!Number.isFinite(requested) || requested <= 0) return null;
  const deadline = Date.now() + Math.min(requested, INLINE_WAIT_CEILING_MS);
  try {
    while (Date.now() < deadline) {
      sleepSync(INLINE_WAIT_POLL_MS);
      if (!existsSync(rawPath)) continue;
      const identity: SessionIdentity | null = parseIdentityOutput(readFileSync(rawPath, 'utf8'));
      if (!identity) continue;
      writeFileSync(parsedPath, JSON.stringify(identity), 'utf8');
      applyColorOnce(input, projectDir, identity.color, colorAppliedPath, ctx);
      ctx.log('session-identity', `haiku identity ready (inline): "${identity.title}" (${identity.color})`);
      return titleWithColor(identity);
    }
  } catch {
    /* fail open — fall back to the lazy next-turn pull */
  }
  return null;
}

/**
 * Append the agent-color record at most once per distinct color value
 * (hash color on turn 1, possibly upgraded once by the haiku pick).
 */
function applyColorOnce(
  input: HookInput,
  projectDir: string | undefined,
  color: SessionColor,
  colorAppliedPath: string,
  ctx: HookContext,
): void {
  try {
    if (existsSync(colorAppliedPath) && readFileSync(colorAppliedPath, 'utf8').trim() === color) {
      return;
    }
    const transcript = resolveTranscriptPath(input, projectDir);
    if (!transcript) return;
    if (appendAgentColorRecord(transcript, input.session_id, color)) {
      writeFileSync(colorAppliedPath, color, 'utf8');
      ctx.log('session-identity', `session color set: ${color}`);
    }
  } catch {
    /* fail open */
  }
}
