// Generated by OrchestKit Claude Plugin
// Created: 2026-08-29

/**
 * Session staleness + model-switch payload readers (CC 2.1.251, #3789).
 *
 * CC 2.1.251 added two things ork reads here:
 *
 * 1. SessionStart on `source: "resume"` now carries the session's staleness and
 *    the estimated cost of re-warming its prompt cache. Measured on 2.1.251 with
 *    a stdin-dumping hook (2026-08-29), the fields are:
 *      seconds_since_last_response, context_tokens, prompt_cache_likely_expired,
 *      estimated_cache_write_usd, session_title
 *    (not the `staleness_ms` that the binary's string table suggests; that key
 *    belongs to the device bridge). `startup` payloads carry none of them.
 *
 * 2. PreModelSwitch / PostModelSwitch carry the same measured shape:
 *      from_model, to_model, requested_model, source, context_tokens,
 *      prompt_cache_warm, cache_ttl, estimated_cache_write_usd, pricing
 *    `source` was "command" for `/model`; the binary also names the picker and
 *    `set_model`. `pricing` is "catalog" (list price), "configured" (managed
 *    modelPricing) or "default" (to_model unknown, default tier assumed).
 *
 * Every reader here is total: a missing or malformed field yields the neutral
 * value (0 / false / ''), never a throw, because these hooks run on the
 * SessionStart and model-switch hot paths and a crash there is worse than a
 * skipped optimization.
 */

import type { HookInput } from '../types.js';

type Raw = Record<string, unknown>;

function num(v: unknown): number {
  return typeof v === 'number' && Number.isFinite(v) ? v : 0;
}
function str(v: unknown): string {
  return typeof v === 'string' ? v : '';
}

export interface ResumeStaleness {
  /** true only when CC reported source === 'resume' */
  isResume: boolean;
  secondsSinceLastResponse: number;
  contextTokens: number;
  /** CC's own estimate; false on a warm cache, true when the TTL has lapsed */
  promptCacheLikelyExpired: boolean;
  estimatedCacheWriteUsd: number;
  sessionTitle: string;
  /**
   * A resume that came back quickly onto a cache CC still believes is warm.
   * Context is intact and the model needs no re-orientation, so loaders that
   * exist to re-orient a cold session (handoff injection) can stay quiet.
   */
  isWarmRecentResume: boolean;
}

/** Idle window under which a warm resume counts as "recent" (30 minutes). */
export const WARM_RESUME_MAX_IDLE_SECONDS = 30 * 60;

export function readResumeStaleness(input: HookInput): ResumeStaleness {
  const raw = input as unknown as Raw;
  const isResume = raw.source === 'resume';
  const secondsSinceLastResponse = num(raw.seconds_since_last_response);
  const promptCacheLikelyExpired = raw.prompt_cache_likely_expired === true;
  return {
    isResume,
    secondsSinceLastResponse,
    contextTokens: num(raw.context_tokens),
    promptCacheLikelyExpired,
    estimatedCacheWriteUsd: num(raw.estimated_cache_write_usd),
    sessionTitle: str(raw.session_title),
    isWarmRecentResume:
      isResume &&
      !promptCacheLikelyExpired &&
      // CC omits the field entirely on older versions; 0 means "unknown", and
      // unknown must not read as "recent".
      secondsSinceLastResponse > 0 &&
      secondsSinceLastResponse <= WARM_RESUME_MAX_IDLE_SECONDS,
  };
}

export interface ModelSwitchPayload {
  fromModel: string;
  toModel: string;
  requestedModel: string;
  /** "command" for /model; the binary also names the picker and set_model */
  source: string;
  contextTokens: number;
  promptCacheWarm: boolean;
  cacheTtl: string;
  estimatedCacheWriteUsd: number;
  /** "catalog" | "configured" | "default" */
  pricing: string;
}

export function readModelSwitch(input: HookInput): ModelSwitchPayload {
  const raw = input as unknown as Raw;
  const toModel = str(raw.to_model);
  return {
    fromModel: str(raw.from_model),
    toModel,
    requestedModel: str(raw.requested_model) || toModel,
    source: str(raw.source),
    contextTokens: num(raw.context_tokens),
    promptCacheWarm: raw.prompt_cache_warm === true,
    cacheTtl: str(raw.cache_ttl),
    estimatedCacheWriteUsd: num(raw.estimated_cache_write_usd),
    pricing: str(raw.pricing),
  };
}

/**
 * Premium-tier ids that bill above Opus. Mirrors fable-spend-consent's
 * isFablePin (short or full id, so `claude-fable-5[1m]` matches) and adds the
 * Mythos family, which shares Fable's model and pricing tier.
 */
export function isPremiumTierModel(model: string): boolean {
  const m = model.toLowerCase();
  return (
    m === 'fable' ||
    m === 'mythos' ||
    m.startsWith('claude-fable') ||
    m.startsWith('claude-mythos')
  );
}
