// Generated by OrchestKit Claude Plugin
// Created: 2026-08-11

/**
 * Linked-worktree enumeration by reading git's own metadata — no subprocess.
 *
 * LEAF MODULE BY DESIGN: imports ONLY `node:fs` and `node:path`, for the same
 * structural reason as `git-head.ts` — a leaf cannot participate in an import
 * cycle, so the constraint holds without anyone having to remember it (#2970).
 *
 * Why parsing beats `git worktree list --porcelain`: this runs on the
 * PreToolUse/Bash deny path inside a fresh process. `git worktree list` takes
 * the same locks that made branch resolution stall for seconds under
 * concurrent-session fork pressure (#2948). The metadata it would print is
 * three small files per worktree, so we read them directly.
 *
 * Layout git guarantees, for a linked worktree registered as <name>:
 *   <common-git-dir>/worktrees/<name>/gitdir  -> absolute path of the
 *                                                worktree's own `.git` FILE
 *   <common-git-dir>/worktrees/<name>/HEAD    -> the worktree's HEAD symref
 * The worktree's checkout root is the directory containing that `.git` file.
 */

import { readFileSync, readdirSync, statSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';

/** One linked worktree, as read off disk. */
export interface LinkedWorktree {
  /** Absolute path of the worktree's checkout root. */
  path: string;
  /** Branch name, or '' when the worktree is on a detached HEAD. */
  branch: string;
  /**
   * Most recent mtime across the worktree's HEAD and index, in epoch ms.
   * A proxy for "the operator is working here right now": git rewrites HEAD
   * on checkout and the index on `git add`. 0 when neither is readable.
   */
  activityMs: number;
}

/**
 * Resolve the common git directory for a checkout root.
 *
 * `<dir>/.git` is a directory in the primary tree and a FILE containing
 * `gitdir: <path>` inside a linked worktree or submodule. In the linked case
 * that path is the worktree's PRIVATE dir (`…/.git/worktrees/<name>`), whose
 * parent's parent is the common dir — so we walk up when we land there.
 *
 * Throws when there is no readable `.git`, matching `readBranchFromHead`:
 * callers map that to their own fallback.
 */
export function resolveCommonGitDir(dir: string): string {
  let gitDir = join(dir, '.git');
  if (statSync(gitDir).isFile()) {
    const pointer = readFileSync(gitDir, 'utf8');
    const m = pointer.match(/^gitdir:\s*(.+)\s*$/m);
    if (!m) throw new Error('malformed .git pointer file');
    gitDir = resolve(dir, m[1].trim());
  }
  // Inside a linked worktree's private dir: …/<common>/worktrees/<name>
  const parent = dirname(gitDir);
  if (dirname(parent).endsWith('/worktrees') || parent.endsWith('/worktrees')) {
    return dirname(parent);
  }
  return gitDir;
}

/** Parse a HEAD file's contents into a branch name ('' when detached). */
function branchFromHeadContents(contents: string): string {
  const ref = contents.trim().match(/^ref:\s*refs\/heads\/(.+)$/);
  return ref ? ref[1] : '';
}

/** Newest mtime among the given paths, in epoch ms; 0 when none are readable. */
function newestMtimeMs(paths: string[]): number {
  let newest = 0;
  for (const p of paths) {
    try {
      const { mtimeMs } = statSync(p);
      if (mtimeMs > newest) newest = mtimeMs;
    } catch {
      // A worktree need not have an index yet; absence is not an error here.
      // silent: best-effort
    }
  }
  return newest;
}

/**
 * Every linked worktree of the repo containing `dir`, newest activity first.
 *
 * Excludes the primary tree (git does not register it under `worktrees/`) and
 * any registration whose checkout root has gone away — a stale entry git has
 * not pruned yet would otherwise produce a `git -C <path>` suggestion that
 * cannot run.
 *
 * Returns [] rather than throwing on any read failure: the sole caller is a
 * message-enrichment path that must degrade to a plain deny, never to a crash.
 */
export function listLinkedWorktrees(dir: string): LinkedWorktree[] {
  let entries: string[];
  let commonDir: string;
  try {
    commonDir = resolveCommonGitDir(dir);
    entries = readdirSync(join(commonDir, 'worktrees'));
  } catch {
    return []; // silent: best-effort — no repo, or no linked worktrees
  }

  const found: LinkedWorktree[] = [];
  for (const name of entries) {
    const privateDir = join(commonDir, 'worktrees', name);
    try {
      const gitdirPointer = readFileSync(join(privateDir, 'gitdir'), 'utf8').trim();
      const worktreePath = dirname(gitdirPointer);
      // Stale registration: the checkout is gone but git has not pruned it.
      if (!statSync(worktreePath).isDirectory()) continue;
      found.push({
        path: worktreePath,
        branch: branchFromHeadContents(readFileSync(join(privateDir, 'HEAD'), 'utf8')),
        activityMs: newestMtimeMs([join(privateDir, 'HEAD'), join(privateDir, 'index')]),
      });
    } catch {
      // silent: best-effort — skip an unreadable registration, keep its siblings
    }
  }

  return found.sort((a, b) => b.activityMs - a.activityMs);
}
