// Generated by OrchestKit Claude Plugin
// Created: 2026-04-01

/**
 * Cache-Break Detector — UserPromptSubmit Hook (Analytics Only)
 * Issue #1238: Detect when OrchestKit's prompt injections change shape between
 * turns, signaling a potential prompt cache break (full re-tokenization).
 *
 * CC's promptCacheBreakDetection.ts tracks 14 cache-break vectors internally.
 * This hook adds visibility into OrchestKit's own contribution to cache breaks
 * by tracking the "shape" of context injections across turns.
 *
 * Design:
 * - Hashes the set of active context injection keys (hook names, section markers)
 * - Compares to previous turn's shape hash (persisted via CLAUDE_ENV_FILE)
 * - On shape change, logs a cache-break signal to ~/.claude/analytics/cache-breaks.jsonl
 * - Never modifies Claude's behavior — analytics only
 *
 * Performance: FNV-1a hash + string comparison, < 5ms budget.
 * Privacy: logs only hashed project ID, shape hash, and delta summary.
 */

import type { HookInput, HookResult , HookContext} from '../types.js';
import { outputSilentSuccess, fnv1aHash } from '../lib/common.js';
// v7.30.0 (#1266): Removed appendAnalytics — cache break data goes via emit path
import { getSessionStorageDir } from '../lib/paths.js';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { NOOP_CTX } from '../lib/context.js';

// =============================================================================
// CONSTANTS
// =============================================================================

const HOOK_NAME = 'cache-break-detector';

/**
 * Markers that indicate context injection sections in the prompt.
 * These are the boundaries OrchestKit hooks use when injecting additionalContext.
 * When the set of active markers changes between turns, it signals a shape change.
 */
const SECTION_MARKERS = [
  // System reminder tags (injected by hooks via additionalContext)
  '<system-reminder>',
  '</system-reminder>',
  // OrchestKit-specific markers
  '[TLDR]',
  '[Cross-project context:',
  '# currentDate',
  '# claudeMd',
  // Skill/agent context markers
  '<skill-format>',
  '<command-name>',
  '<command-message>',
  // Hook-injected context patterns
  'HANDOFF.md',
  'agent-memory',
  'context-exhaustion',
  'pipeline-detector',
] as const;

/** State file name within session storage */
const STATE_FILE = 'cache-break-state.json';

// =============================================================================
// SHAPE EXTRACTION
// =============================================================================

/**
 * Extract the "shape" of prompt context injections.
 * Returns a sorted list of which section markers are present.
 * The shape captures WHAT is injected, not the content — so we detect
 * structural changes (new hook added, hook removed) not content edits.
 */
export function extractPromptShape(prompt: string): string[] {
  const activeMarkers: string[] = [];
  for (const marker of SECTION_MARKERS) {
    if (prompt.includes(marker)) {
      activeMarkers.push(marker);
    }
  }
  return activeMarkers.sort();
}

/**
 * Compute a stable hash of the prompt shape for cheap comparison.
 */
export function hashShape(markers: string[]): string {
  return fnv1aHash(markers.join('|'));
}

// =============================================================================
// STATE PERSISTENCE
// =============================================================================

interface CacheBreakState {
  /** Shape hash from the previous turn */
  lastShapeHash: string;
  /** Sorted marker list from the previous turn */
  lastMarkers: string[];
  /** Turn counter within session */
  turnCount: number;
}

/**
 * Get state file path within session storage.
 * Uses CLAUDE_PLUGIN_DATA-backed session storage for persistence.
 */
function getStateFilePath(sessionId: string): string {
  const sessionDir = join(getSessionStorageDir(), sessionId);
  return join(sessionDir, STATE_FILE);
}

/**
 * Load previous turn's state. Returns null on first turn or read failure.
 */
function loadState(sessionId: string): CacheBreakState | null {
  try {
    const filePath = getStateFilePath(sessionId);
    if (!existsSync(filePath)) return null;
    const raw = readFileSync(filePath, 'utf8');
    return JSON.parse(raw) as CacheBreakState;
  } catch {
    return null;
  }
}

/**
 * Persist current turn's state for next-turn comparison.
 */
function saveState(sessionId: string, state: CacheBreakState): void {
  try {
    const filePath = getStateFilePath(sessionId);
    const dir = join(filePath, '..');
    if (!existsSync(dir)) {
      mkdirSync(dir, { recursive: true });
    }
    writeFileSync(filePath, JSON.stringify(state), 'utf8');
  } catch {
    // Never block the hook chain on I/O failure
  }
}

// =============================================================================
// DELTA ANALYSIS
// =============================================================================

interface ShapeDelta {
  added: string[];
  removed: string[];
}

/**
 * Compute the delta between two sorted marker arrays.
 * Returns which markers were added and which were removed.
 */
export function computeDelta(prev: string[], curr: string[]): ShapeDelta {
  const prevSet = new Set(prev);
  const currSet = new Set(curr);

  const added = curr.filter(m => !prevSet.has(m));
  const removed = prev.filter(m => !currSet.has(m));

  return { added, removed };
}

// =============================================================================
// MAIN HOOK
// =============================================================================

/**
 * Cache-break detector hook.
 *
 * Extracts the prompt injection shape, compares to previous turn,
 * and logs a cache-break signal when the shape changes.
 * Never produces context output — analytics only.
 */
export function cacheBreakDetector(input: HookInput, ctx: HookContext = NOOP_CTX): HookResult {
  const prompt = input.prompt || '';

  // Skip empty/trivial prompts (no injections to detect)
  if (prompt.length < 50) {
    return outputSilentSuccess();
  }

  const sessionId = input.session_id;
  if (!sessionId) {
    return outputSilentSuccess();
  }

  try {
    // Extract current shape
    const currentMarkers = extractPromptShape(prompt);
    const currentHash = hashShape(currentMarkers);

    // Load previous state
    const prevState = loadState(sessionId);
    const turnCount = (prevState?.turnCount ?? 0) + 1;

    // Save current state for next turn
    saveState(sessionId, {
      lastShapeHash: currentHash,
      lastMarkers: currentMarkers,
      turnCount,
    });

    // First turn: no comparison possible — just record baseline
    if (!prevState) {
      ctx.log(HOOK_NAME, `Baseline shape recorded: ${currentMarkers.length} markers, hash=${currentHash}`);
      return outputSilentSuccess();
    }

    // Same shape: no cache break signal
    if (prevState.lastShapeHash === currentHash) {
      return outputSilentSuccess();
    }

    // Shape changed — potential cache break
    const delta = computeDelta(prevState.lastMarkers, currentMarkers);

    ctx.log(HOOK_NAME, `Shape change detected at turn ${turnCount}: +${delta.added.length}/-${delta.removed.length} markers`);

    // Estimate token cost of re-tokenization
    // Rough heuristic: each marker indicates ~200-500 tokens of injected context
    const estimatedTokenCost = (delta.added.length + delta.removed.length) * 350;

    // Cache break data flows to yonatan-hq via emit() on UserPromptSubmit event
    ctx.log(HOOK_NAME, `Cache break: +${delta.added.length}/-${delta.removed.length} markers, ~${estimatedTokenCost}t cost`);
  } catch (error) {
    // Never crash the hook chain
    ctx.log(HOOK_NAME, `Error: ${error}`, 'warn');
  }

  return outputSilentSuccess();
}
