// Generated by OrchestKit Claude Plugin
// Created: 2026-02-16

/**
 * Unit tests for file-guard file size gate
 * Tests file line limits, test file detection, bloat pattern detection,
 * and env var overrides.
 */

import { describe, it, expect, beforeEach, afterEach, vi } from 'vitest';
import type { HookInput } from '../../../types.js';

// Helper to generate N lines of code content
function generateLines(n: number, prefix = 'const x'): string {
  return Array.from({ length: n }, (_, i) => `${prefix}${i} = ${i};`).join('\n');
}

function generateExports(n: number): string {
  return Array.from({ length: n }, (_, i) => `export function fn${i}() { return ${i}; }`).join('\n');
}

function createWriteInput(file_path: string, content: string): HookInput {
  return {
    tool_name: 'Write',
    session_id: 'test-session-123',
    project_dir: '/test/project',
    tool_input: { file_path, content },
  };
}

function createEditInput(file_path: string): HookInput {
  return {
    tool_name: 'Edit',
    session_id: 'test-session-123',
    project_dir: '/test/project',
    tool_input: {
      file_path,
      old_string: 'old',
      new_string: 'new',
    },
  };
}

// We need to re-import fileGuard for each env var test group
// so the module-level parseInt picks up the changed env vars.

describe('file-guard size gate', () => {
  describe('with default limits', () => {
    let fileGuard: (input: HookInput) => import('../../../types.js').HookResult;

    beforeEach(async () => {
      delete process.env.ORCHESTKIT_MAX_FILE_LINES;
      delete process.env.ORCHESTKIT_MAX_TEST_FILE_LINES;
      vi.resetModules();
      const mod = await import('../../../pretool/write-edit/file-guard.js');
      fileGuard = mod.fileGuard;
    });

    afterEach(() => {
      vi.restoreAllMocks();
    });

    it('allows short source file (200 lines .ts)', () => {
      const input = createWriteInput('/src/app.ts', generateLines(200));
      const result = fileGuard(input);
      expect(result.continue).toBe(true);
    });

    it('blocks long source file (400 lines .ts)', () => {
      const input = createWriteInput('/src/big.ts', generateLines(400));
      const result = fileGuard(input);
      expect(result.continue).toBe(false);
      expect(result.stopReason).toContain('400 lines');
      expect(result.stopReason).toContain('limit: 300');
      expect(result.stopReason).toContain('source files');
    });

    it('allows long test file under test limit (400 lines .test.ts)', () => {
      const input = createWriteInput('/src/app.test.ts', generateLines(400));
      const result = fileGuard(input);
      expect(result.continue).toBe(true);
    });

    it('blocks over-limit test file (600 lines .test.ts)', () => {
      const input = createWriteInput('/src/app.test.ts', generateLines(600));
      const result = fileGuard(input);
      expect(result.continue).toBe(false);
      expect(result.stopReason).toContain('600 lines');
      expect(result.stopReason).toContain('limit: 500');
      expect(result.stopReason).toContain('test files');
    });

    it('allows JSON file of any length', () => {
      const input = createWriteInput('/config/data.json', generateLines(500));
      const result = fileGuard(input);
      expect(result.continue).toBe(true);
    });

    it('allows markdown file of any length', () => {
      const input = createWriteInput('/docs/guide.md', generateLines(500));
      const result = fileGuard(input);
      expect(result.continue).toBe(true);
    });

    it('skips Edit operations (no full content)', () => {
      const input = createEditInput('/src/huge.ts');
      const result = fileGuard(input);
      expect(result.continue).toBe(true);
    });

    // Test file detection patterns
    describe('test file detection', () => {
      it('detects .spec.ts as test file', () => {
        const input = createWriteInput('/src/app.spec.ts', generateLines(400));
        const result = fileGuard(input);
        expect(result.continue).toBe(true);
      });

      it('detects __tests__/ path as test file', () => {
        const input = createWriteInput('/src/__tests__/foo.ts', generateLines(400));
        const result = fileGuard(input);
        expect(result.continue).toBe(true);
      });

      it('detects test_ prefix as test file', () => {
        const input = createWriteInput('/tests/test_foo.py', generateLines(400));
        const result = fileGuard(input);
        expect(result.continue).toBe(true);
      });

      it('detects _test suffix as test file', () => {
        const input = createWriteInput('/src/app_test.go', generateLines(400));
        const result = fileGuard(input);
        expect(result.continue).toBe(true);
      });
    });

    // Bloat pattern detection
    describe('bloat patterns', () => {
      it('includes god-file detail when over limit with many exports', () => {
        const exports = generateExports(25);
        const padding = generateLines(400 - 25);
        const input = createWriteInput('/src/god.ts', `${exports}\n${padding}`);
        const result = fileGuard(input);
        expect(result.continue).toBe(false);
        expect(result.stopReason).toContain('god-file');
        expect(result.stopReason).toContain('25 exports');
      });

      it('allows god file under line limit (bloat noted, not blocked)', () => {
        const exports = generateExports(25);
        // 25 exports + enough padding to stay under 300
        const padding = generateLines(250 - 25);
        const input = createWriteInput('/src/god.ts', `${exports}\n${padding}`);
        const result = fileGuard(input);
        expect(result.continue).toBe(true);
      });

      it('includes mixed-concerns detail when types + logic over limit', () => {
        const types = 'export interface Foo { bar: string; }\n';
        const logic = 'export function doStuff() { return 1; }\n';
        const padding = generateLines(350);
        const input = createWriteInput('/src/mixed.ts', types + logic + padding);
        const result = fileGuard(input);
        expect(result.continue).toBe(false);
        expect(result.stopReason).toContain('mixed-concerns');
        expect(result.stopReason).toContain('extract types');
      });

      it('shows override instructions in block message', () => {
        const input = createWriteInput('/src/big.ts', generateLines(400));
        const result = fileGuard(input);
        expect(result.continue).toBe(false);
        expect(result.stopReason).toContain('ORCHESTKIT_MAX_FILE_LINES');
        expect(result.stopReason).toContain('ORCHESTKIT_MAX_TEST_FILE_LINES');
      });
    });

    // Code extension coverage
    describe('code extensions', () => {
      const extensions = ['py', 'ts', 'tsx', 'js', 'jsx', 'go', 'rs', 'java'];
      for (const ext of extensions) {
        it(`blocks oversized .${ext} file`, () => {
          const input = createWriteInput(`/src/big.${ext}`, generateLines(400));
          const result = fileGuard(input);
          expect(result.continue).toBe(false);
        });
      }

      const nonCodeExts = ['json', 'md', 'yaml', 'yml', 'toml', 'css', 'html', 'sql'];
      for (const ext of nonCodeExts) {
        it(`allows oversized .${ext} file (non-code)`, () => {
          const input = createWriteInput(`/src/big.${ext}`, generateLines(400));
          const result = fileGuard(input);
          expect(result.continue).toBe(true);
        });
      }
    });
  });

  describe('with env var overrides', () => {
    let fileGuard: (input: HookInput) => import('../../../types.js').HookResult;

    beforeEach(async () => {
      process.env.ORCHESTKIT_MAX_FILE_LINES = '600';
      process.env.ORCHESTKIT_MAX_TEST_FILE_LINES = '800';
      vi.resetModules();
      const mod = await import('../../../pretool/write-edit/file-guard.js');
      fileGuard = mod.fileGuard;
    });

    afterEach(() => {
      delete process.env.ORCHESTKIT_MAX_FILE_LINES;
      delete process.env.ORCHESTKIT_MAX_TEST_FILE_LINES;
      vi.restoreAllMocks();
    });

    it('allows 500-line source file with raised limit', () => {
      const input = createWriteInput('/src/big.ts', generateLines(500));
      const result = fileGuard(input);
      expect(result.continue).toBe(true);
    });

    it('blocks source file over raised limit', () => {
      const input = createWriteInput('/src/huge.ts', generateLines(700));
      const result = fileGuard(input);
      expect(result.continue).toBe(false);
      expect(result.stopReason).toContain('limit: 600');
    });

    it('allows 700-line test file with raised test limit', () => {
      const input = createWriteInput('/src/app.test.ts', generateLines(700));
      const result = fileGuard(input);
      expect(result.continue).toBe(true);
    });

    it('blocks test file over raised test limit', () => {
      const input = createWriteInput('/src/app.test.ts', generateLines(900));
      const result = fileGuard(input);
      expect(result.continue).toBe(false);
      expect(result.stopReason).toContain('limit: 800');
    });
  });
});
