#!/usr/bin/env bash
# Generated by OrchestKit Claude Plugin
# Created: 2026-10-03

# Test: no skill or agent source may instruct `agent-browser close --all`
# (#4520)
#
# On a shared machine several Claude sessions own separate agent-browser
# sessions. A forked expect agent ran `agent-browser close --all` at cleanup
# and killed three other sessions' browsers mid-work. No source file carried
# the flag; the agent improvised it from a vague cleanup line. This lint
# fails if any skill or agent text ever names the flag, so the rule has a
# gate and not just guidance.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"

FAILED=0

# `close --all` and the `-a` short form, with or without the agent-browser
# prefix. Scoped to src/ prose (skills, agents, rules); tests and fixtures
# carry the literal by necessity and are excluded by directory choice.
while IFS= read -r hit; do
  [[ -z "$hit" ]] && continue
  echo "FAIL: ${hit#"$REPO_ROOT"/} — instructs 'close --all'; close only the session the run opened (#4520)"
  FAILED=1
done < <(grep -rnoE 'agent-browser[[:space:]]+close[[:space:]]+(-a|--all)\b|(^|[[:space:]"`'"'"'])close[[:space:]]+--all\b' \
  "$REPO_ROOT/src/skills" "$REPO_ROOT/src/agents" 2>/dev/null || true)

echo ""
if [[ $FAILED -eq 0 ]]; then
  echo "OK: no skill or agent source instructs 'close --all'"
fi

exit "$FAILED"
