#!/usr/bin/env bash
# Generated by OrchestKit Claude Plugin
# Created: 2026-07-31

# test-skill-delta.sh: ratchet gate over check-skill-delta.mjs
#
# Named test-*.sh so scripts/ci/run-tests.sh discovers it (a prior .mjs gate in this
# repo sat dead because the runner globbed only test-*.sh: naming is what makes it live).
#
# Three deterministic checks, $0, no network:
#   ORPHAN       skill sub-file whose stem appears nowhere else in src/ + manifests/
#   RESTATEMENT  >150-line file with zero ork anchors (upstream tutorial restated)
#   OVERLAP      file on a topic a first-party skill now covers (first-party-registry.mjs)
#
# Ratchet contract: fails only when a count INCREASES over the committed baseline
# (skill-delta-baseline.json). Run --update-baseline only when findings are genuinely
# resolved, never to silence a regression.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"

echo "=== Skill Delta Ratchet ==="
node "$REPO_ROOT/scripts/check-skill-delta.mjs" --check
