// Generated by OrchestKit Claude Plugin
// Created: 2026-05-18

/**
 * @orchestkit/hook-contract — barrel export.
 *
 * Public surface for M141-1:
 *   import { HookEvent, HOOK_EVENT_NAMES, validateHookEvent } from '@orchestkit/hook-contract';
 *
 * Sub-path imports for tree-shaking-conscious consumers:
 *   import { HOOK_EVENT_NAMES } from '@orchestkit/hook-contract/events';
 *   import { HOOK_EVENT_SCHEMAS } from '@orchestkit/hook-contract/schemas';
 *   import { validateHookEvent } from '@orchestkit/hook-contract/validate';
 */

export * from './events.js';
export * from './schemas.js';
export * from './validate.js';
export * from './signing.js';

export const HOOK_CONTRACT_VERSION = '0.1.1' as const;
