// Generated by OrchestKit Claude Plugin
// Created: 2026-05-18

/**
 * JSON Schema (draft-07) for hook events.
 *
 * M141-1 ships a minimal envelope schema per event — enough for the parity
 * gate to assert "the npm side knows about event X" without committing to
 * field-level shape yet. M141-2 expands these to full per-event schemas
 * derived from the shared spec.
 */

import { HOOK_EVENT_NAMES, type HookEventName } from './events.js';

/** JSON Schema document, narrowed to the subset we emit. */
export interface JsonSchema {
  $schema?: string;
  $id?: string;
  title?: string;
  type?: 'object' | 'string' | 'number' | 'boolean' | 'array' | 'null';
  properties?: Record<string, JsonSchema>;
  required?: string[];
  additionalProperties?: boolean | JsonSchema;
  const?: string;
  enum?: readonly string[];
  description?: string;
  // Allow arbitrary extension fields without losing type safety.
  [key: string]: unknown;
}

const SCHEMA_DRAFT = 'https://json-schema.org/draft-07/schema#';

function envelopeSchema(event: HookEventName): JsonSchema {
  return {
    $schema: SCHEMA_DRAFT,
    $id: `https://orchestkit.dev/schemas/hook-contract/${event}.json`,
    title: `${event} hook event`,
    type: 'object',
    properties: {
      event: { type: 'string', const: event },
      timestamp: { type: 'string', description: 'ISO-8601 UTC timestamp' },
      session_id: { type: 'string' },
      cwd: { type: 'string' },
      payload: { type: 'object', additionalProperties: true },
    },
    required: ['event'],
    additionalProperties: true,
  };
}

/**
 * Per-event JSON schemas keyed by event name. Frozen at module load.
 */
export const HOOK_EVENT_SCHEMAS: Readonly<Record<HookEventName, JsonSchema>> = Object.freeze(
  Object.fromEntries(HOOK_EVENT_NAMES.map((name) => [name, envelopeSchema(name)])) as Record<
    HookEventName,
    JsonSchema
  >
);

/**
 * Aggregate schema — oneOf union of all per-event schemas. Useful for
 * "this object is some HookEvent" validation in a single call.
 */
export const HOOK_EVENT_SCHEMA: JsonSchema = {
  $schema: SCHEMA_DRAFT,
  $id: 'https://orchestkit.dev/schemas/hook-contract/HookEvent.json',
  title: 'HookEvent',
  oneOf: HOOK_EVENT_NAMES.map((name) => HOOK_EVENT_SCHEMAS[name]),
};
