// Generated by OrchestKit Claude Plugin
// Created: 2026-03-02

/**
 * Unit tests for sync-bash-dispatcher hook
 *
 * Tests the consolidated Bash PreToolUse dispatcher:
 * - Short-circuit behavior on first block
 * - Context merging across passing hooks
 * - updatedInput propagation
 * - Error isolation per hook
 * - Phase ordering: Phase 1 (security) → Phase 2 (git/GH) → Phase 3 (advisory)
 */

import { describe, it, expect, vi, beforeEach } from 'vitest';
import type { HookInput, HookResult } from '../../types.js';

// ---------------------------------------------------------------------------
// Mocks — mock all sub-hooks to isolate dispatcher logic
// ---------------------------------------------------------------------------

vi.mock('../../lib/common.js', async () => {
  const actual = await vi.importActual<typeof import('../../lib/common.js')>('../../lib/common.js');
  return {
    ...actual,
    logHook: vi.fn(),
    outputSilentSuccess: vi.fn(() => ({ continue: true, suppressOutput: true })),
    outputWithUpdatedInput: vi.fn((updatedInput: Record<string, unknown>) => ({
      continue: true,
      suppressOutput: true,
      hookSpecificOutput: { hookEventName: 'PreToolUse', updatedInput },
    })),
    extractContext: vi.fn((result: HookResult) => {
      return result.hookSpecificOutput?.additionalContext as string | undefined ?? null;
    }),
  };
});


vi.mock('../../pretool/bash/unified-advisory-dispatcher.js', () => ({
  unifiedBashAdvisoryDispatcher: vi.fn(() => ({ continue: true, suppressOutput: true })),
}));

vi.mock('../../pretool/bash/issue-reference-checker.js', () => ({
  issueReferenceChecker: vi.fn(() => ({ continue: true, suppressOutput: true })),
}));

vi.mock('../../pretool/bash/gh-label-enforcer.js', () => ({
  ghLabelEnforcer: vi.fn(() => ({ continue: true, suppressOutput: true })),
}));

vi.mock('../../pretool/bash/gh-milestone-enforcer.js', () => ({
  ghMilestoneEnforcer: vi.fn(() => ({ continue: true, suppressOutput: true })),
}));

import { syncBashDispatcher } from '../../pretool/bash/sync-bash-dispatcher.js';
import { unifiedBashAdvisoryDispatcher } from '../../pretool/bash/unified-advisory-dispatcher.js';
import { issueReferenceChecker } from '../../pretool/bash/issue-reference-checker.js';
import { ghLabelEnforcer } from '../../pretool/bash/gh-label-enforcer.js';
import { ghMilestoneEnforcer } from '../../pretool/bash/gh-milestone-enforcer.js';
import { createTestContext } from '../fixtures/test-context.js';

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function createBashInput(command: string, overrides: Partial<HookInput> = {}): HookInput {
  return {
    tool_name: 'Bash',
    session_id: 'test-session-123',
    project_dir: '/test/project',
    tool_input: { command },
    ...overrides,
  };
}

function makeBlockResult(reason: string): HookResult {
  return {
    continue: false,
    stopReason: reason,
    hookSpecificOutput: {
      hookEventName: 'PreToolUse',
      permissionDecision: 'deny',
      permissionDecisionReason: reason,
    },
  };
}

function makeContextResult(context: string): HookResult {
  return {
    continue: true,
    suppressOutput: true,
    hookSpecificOutput: { additionalContext: context, hookEventName: 'PreToolUse' },
  };
}

function makeUpdatedInputResult(updatedInput: Record<string, unknown>): HookResult {
  return {
    continue: true,
    suppressOutput: true,
    hookSpecificOutput: { hookEventName: 'PreToolUse', updatedInput },
  };
}

/**
 * An advisory hook: continue:true + systemMessage, no permission decision
 * and no additionalContext. This is what outputWarning() produces.
 */
function makeWarningResult(message: string): HookResult {
  return { continue: true, systemMessage: message };
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

let testCtx: ReturnType<typeof createTestContext>;
describe('sync-bash-dispatcher', () => {
  beforeEach(() => {
    testCtx = createTestContext();
    // resetAllMocks resets mock implementations back to their vi.mock() defaults,
    // preventing bleed-over from tests that override implementations (e.g., block scenarios)
    vi.resetAllMocks();
    // Re-establish default passing implementations after reset
    vi.mocked(issueReferenceChecker).mockReturnValue({ continue: true, suppressOutput: true });
    vi.mocked(ghLabelEnforcer).mockReturnValue({ continue: true, suppressOutput: true });
    vi.mocked(ghMilestoneEnforcer).mockReturnValue({ continue: true, suppressOutput: true });
    vi.mocked(unifiedBashAdvisoryDispatcher).mockReturnValue({ continue: true, suppressOutput: true });
  });

  // -------------------------------------------------------------------------
  // All hooks pass — silent result
  // -------------------------------------------------------------------------

  describe('all hooks pass silently', () => {
    it('returns silent success when all hooks are silent', () => {
      const input = createBashInput('git status');
      const result = syncBashDispatcher(input, testCtx);

      expect(result.continue).toBe(true);
      expect(result.suppressOutput).toBe(true);
    });

    it('calls every registered hook exactly once', () => {
      const input = createBashInput('npm run build');
      syncBashDispatcher(input, testCtx);

      expect(issueReferenceChecker).toHaveBeenCalled();
      expect(vi.mocked(issueReferenceChecker).mock.calls[0][0]).toEqual(input);
      expect(ghLabelEnforcer).toHaveBeenCalled();
      expect(vi.mocked(ghLabelEnforcer).mock.calls[0][0]).toEqual(input);
      expect(ghMilestoneEnforcer).toHaveBeenCalled();
      expect(vi.mocked(ghMilestoneEnforcer).mock.calls[0][0]).toEqual(input);
      expect(unifiedBashAdvisoryDispatcher).toHaveBeenCalled();
      expect(vi.mocked(unifiedBashAdvisoryDispatcher).mock.calls[0][0]).toEqual(input);
    });
  });

  // -------------------------------------------------------------------------
  // Short-circuit on block
  // -------------------------------------------------------------------------

  describe('short-circuit on ask (#3098 — the ask tier was swallowed)', () => {
    // An ask is {continue:true, permissionDecision:'ask'}. It survived the
    // !continue check and the merge then dropped hookSpecificOutput, so every
    // ask-tier prompt (sudo/kill "Are you sure?", here-strings) reached CC as
    // a silent allow. These pin the propagation.
    const makeAskResult = (reason: string) => ({
      continue: true,
      hookSpecificOutput: {
        hookEventName: 'PreToolUse' as const,
        permissionDecision: 'ask' as const,
        permissionDecisionReason: reason,
      },
    });

    // #3835: the blocker's ask sites are retired; gh-label-enforcer is the
    // mocked Phase 2 ask site. The property under test is unchanged.
    it('propagates an ask from a Phase 2 hook verbatim', () => {
      vi.mocked(ghLabelEnforcer).mockReturnValue(makeAskResult('label required'));
      const result = syncBashDispatcher(createBashInput('gh issue create --title x'), testCtx);
      expect(result.hookSpecificOutput?.permissionDecision).toBe('ask');
      expect(result.hookSpecificOutput?.permissionDecisionReason).toBe('label required');
    });
  });

  describe('short-circuit on first block', () => {
    // #3835: the blockers are retired; issue-reference-checker is the mocked block site.
    it('does not call later hooks after a block', () => {
      vi.mocked(issueReferenceChecker).mockReturnValue(makeBlockResult('blocked'));
      syncBashDispatcher(createBashInput('git commit -m x'), testCtx);
      expect(ghLabelEnforcer).not.toHaveBeenCalled();
      expect(unifiedBashAdvisoryDispatcher).not.toHaveBeenCalled();
    });

    it('logs short-circuit message when block occurs', () => {
      vi.mocked(issueReferenceChecker).mockReturnValue(makeBlockResult('blocked'));
      syncBashDispatcher(createBashInput('git commit -m x'), testCtx);
      expect(testCtx.log).toHaveBeenCalledWith('sync-bash-dispatcher', expect.stringContaining('short-circuiting'));
    });

    it('does not call later hooks after an ask', () => {
      vi.mocked(ghLabelEnforcer).mockReturnValue({ continue: true, suppressOutput: true, hookSpecificOutput: { hookEventName: 'PreToolUse', permissionDecision: 'ask' as const, permissionDecisionReason: 'ask' } });
      syncBashDispatcher(createBashInput('gh issue create --title x'), testCtx);
      expect(ghMilestoneEnforcer).not.toHaveBeenCalled();
      expect(unifiedBashAdvisoryDispatcher).not.toHaveBeenCalled();
    });




  });

  // -------------------------------------------------------------------------
  // Context merging
  // -------------------------------------------------------------------------

  describe('context merging', () => {
    it('merges context from multiple passing hooks', () => {
      vi.mocked(ghLabelEnforcer).mockReturnValue(makeContextResult('Add a --label flag'));
      vi.mocked(ghMilestoneEnforcer).mockReturnValue(makeContextResult('Consider --milestone'));

      const input = createBashInput('gh issue create --title "Test"');
      const result = syncBashDispatcher(input, testCtx);

      expect(result.continue).toBe(true);
      const ctx = result.hookSpecificOutput?.additionalContext as string;
      expect(ctx).toContain('Add a --label flag');
      expect(ctx).toContain('Consider --milestone');
    });

    it('separates merged contexts with ---', () => {
      vi.mocked(ghLabelEnforcer).mockReturnValue(makeContextResult('Context A'));
      vi.mocked(ghMilestoneEnforcer).mockReturnValue(makeContextResult('Context B'));

      const input = createBashInput('gh issue create --title "Test"');
      const result = syncBashDispatcher(input, testCtx);

      const ctx = result.hookSpecificOutput?.additionalContext as string;
      expect(ctx).toContain('---');
    });

    it('returns single context without separator when only one hook has context', () => {
      vi.mocked(ghLabelEnforcer).mockReturnValue(makeContextResult('Only this advice'));

      const input = createBashInput('gh issue create --title "Test"');
      const result = syncBashDispatcher(input, testCtx);

      const ctx = result.hookSpecificOutput?.additionalContext as string;
      expect(ctx).toContain('Only this advice');
    });

    it('returns silent success when no hooks produce context', () => {
      const input = createBashInput('git status');
      const result = syncBashDispatcher(input, testCtx);

      expect(result.continue).toBe(true);
      expect(result.suppressOutput).toBe(true);
      expect(result.hookSpecificOutput?.additionalContext).toBeUndefined();
    });
  });

  // -------------------------------------------------------------------------
  // Advisory systemMessage propagation (#2947)
  //
  // A hook returning outputWarning() carries continue:true + systemMessage and
  // NOTHING else: no permissionDecision, no additionalContext. The loop
  // short-circuits only on !continue and otherwise collected additionalContext
  // alone, so such a hook was silently dropped and behaved as a no-op. Caught
  // when display-lint moved from deny to advisory.
  // -------------------------------------------------------------------------

  describe('advisory systemMessage propagation', () => {
    it('propagates a lone advisory warning to the caller', () => {
      vi.mocked(ghLabelEnforcer).mockReturnValue(makeWarningResult('[display-lint] 250 chars / 4 stages'));

      const input = createBashInput('git status');
      const result = syncBashDispatcher(input, testCtx);

      expect(result.continue).toBe(true);
      expect(result.systemMessage).toContain('[display-lint]');
    });

    // Per CC's hook reference, suppressOutput hides hook STDOUT from the
    // transcript and does not affect systemMessage, which CC renders as its
    // own field. So an advisory must NOT flip suppressOutput off: doing that
    // would surface the dispatcher's raw JSON envelope instead.
    it('leaves suppressOutput alone on the context path when an advisory rides along', () => {
      vi.mocked(ghLabelEnforcer).mockReturnValue(makeContextResult('some context'));
      vi.mocked(ghMilestoneEnforcer).mockReturnValue(makeWarningResult('[display-lint] noisy'));

      const input = createBashInput('gh issue create --title "Test"');
      const result = syncBashDispatcher(input, testCtx);

      expect(result.suppressOutput).toBe(true);
      expect(result.systemMessage).toContain('[display-lint]');
    });

    it('merges multiple advisories', () => {
      vi.mocked(ghLabelEnforcer).mockReturnValue(makeWarningResult('warning one'));
      vi.mocked(ghMilestoneEnforcer).mockReturnValue(makeWarningResult('warning two'));

      const input = createBashInput('git status');
      const result = syncBashDispatcher(input, testCtx);

      expect(result.systemMessage).toContain('warning one');
      expect(result.systemMessage).toContain('warning two');
    });

    it('carries an advisory alongside additionalContext from another hook', () => {
      vi.mocked(ghLabelEnforcer).mockReturnValue(makeContextResult('Add a --label flag'));
      vi.mocked(ghMilestoneEnforcer).mockReturnValue(makeWarningResult('[display-lint] noisy'));

      const input = createBashInput('gh issue create --title "Test"');
      const result = syncBashDispatcher(input, testCtx);

      expect(result.hookSpecificOutput?.additionalContext).toContain('Add a --label flag');
      expect(result.systemMessage).toContain('[display-lint]');
    });

    it('an advisory never blocks and never decides permission', () => {
      vi.mocked(ghLabelEnforcer).mockReturnValue(makeWarningResult('[display-lint] noisy'));

      const input = createBashInput('git status');
      const result = syncBashDispatcher(input, testCtx);

      expect(result.continue).toBe(true);
      expect(result.hookSpecificOutput?.permissionDecision).toBeUndefined();
    });
  });

  // -------------------------------------------------------------------------
  // updatedInput propagation
  // -------------------------------------------------------------------------

  describe('updatedInput propagation', () => {
    it('propagates updatedInput from a passing hook', () => {
      vi.mocked(unifiedBashAdvisoryDispatcher).mockReturnValue(
        makeUpdatedInputResult({ command: 'git status', timeout: 30000 }),
      );

      const input = createBashInput('git status');
      const result = syncBashDispatcher(input, testCtx);

      expect(result.hookSpecificOutput?.updatedInput).toEqual({ command: 'git status', timeout: 30000 });
    });

    it('merges updatedInput + context together when both present', () => {
      vi.mocked(ghLabelEnforcer).mockReturnValue(makeContextResult('Label advice'));
      vi.mocked(unifiedBashAdvisoryDispatcher).mockReturnValue(
        makeUpdatedInputResult({ command: 'gh issue create', timeout: 5000 }),
      );

      const input = createBashInput('gh issue create --title "Test" --label bug');
      const result = syncBashDispatcher(input, testCtx);

      expect(result.hookSpecificOutput?.updatedInput).toBeDefined();
      const ctx = result.hookSpecificOutput?.additionalContext as string;
      expect(ctx).toContain('Label advice');
    });
  });

  // -------------------------------------------------------------------------
  // Error isolation
  // -------------------------------------------------------------------------

  describe('error isolation', () => {
    it('continues when a non-blocking hook throws', () => {
      vi.mocked(ghLabelEnforcer).mockImplementation(() => {
        throw new Error('unexpected crash in gh-label-enforcer');
      });

      const input = createBashInput('git status');
      const result = syncBashDispatcher(input, testCtx);

      // Dispatcher should not crash
      expect(result).toBeDefined();
      expect(result.continue).toBe(true);
    });

    it('logs warning when a hook throws', () => {
      vi.mocked(ghMilestoneEnforcer).mockImplementation(() => {
        throw new Error('crash');
      });

      const input = createBashInput('git status');
      syncBashDispatcher(input, testCtx);

      expect(testCtx.log).toHaveBeenCalledWith(
        'sync-bash-dispatcher',
        expect.stringContaining('gh-milestone-enforcer failed'),
        'warn',
      );
    });

    it('continues calling subsequent hooks after one throws', () => {
      // #3835: issue-reference-checker is the mocked thrower now (git-validator retired).
      vi.mocked(issueReferenceChecker).mockImplementation(() => {
        throw new Error('issue reference checker crashed');
      });

      const input = createBashInput('git status');
      syncBashDispatcher(input, testCtx);

      // gh-label-enforcer comes after issue-reference-checker; it must still run
      expect(ghLabelEnforcer).toHaveBeenCalled();
    });

    it('handles non-Error throws gracefully', () => {
      vi.mocked(issueReferenceChecker).mockImplementation(() => {
        throw 'string error'; // eslint-disable-line no-throw-literal
      });

      const input = createBashInput('git status');
      expect(() => syncBashDispatcher(input, testCtx)).not.toThrow();
    });
  });

  // -------------------------------------------------------------------------
  // Phase ordering
  // -------------------------------------------------------------------------

  describe('phase ordering', () => {
    it('calls issue-reference-checker before gh-label-enforcer', () => {
      const order: string[] = [];
      vi.mocked(issueReferenceChecker).mockImplementation(() => { order.push('issue-reference-checker'); return { continue: true, suppressOutput: true }; });
      vi.mocked(ghLabelEnforcer).mockImplementation(() => { order.push('gh-label-enforcer'); return { continue: true, suppressOutput: true }; });
      syncBashDispatcher(createBashInput('git commit'), testCtx);
      expect(order.indexOf('issue-reference-checker')).toBeLessThan(order.indexOf('gh-label-enforcer'));
    });


    it('calls all Phase 2 hooks before advisory dispatcher (Phase 3)', () => {
      const order: string[] = [];
      vi.mocked(ghMilestoneEnforcer).mockImplementation(() => { order.push('gh-milestone'); return { continue: true, suppressOutput: true }; });
      vi.mocked(unifiedBashAdvisoryDispatcher).mockImplementation(() => { order.push('advisory'); return { continue: true, suppressOutput: true }; });

      syncBashDispatcher(createBashInput('git status'), testCtx);

      expect(order.indexOf('gh-milestone')).toBeLessThan(order.indexOf('advisory'));
    });
  });
});
