// Generated by OrchestKit Claude Plugin
// Created: 2026-07-20

/**
 * Unit tests for lifecycle/analytics-liveness-check
 *
 * Reproduces the observed failure: skill-usage.jsonl silent for months while
 * agent-usage.jsonl stayed hot — the hook must flag exactly that shape and
 * stay silent on idle machines, fresh installs, and single-writer dirs.
 */

import { describe, it, expect, beforeEach, afterEach, vi } from 'vitest';
import { mkdtempSync, rmSync, utimesSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { analyticsLivenessCheck, _internals } from '../lifecycle/analytics-liveness-check.js';
import { NOOP_CTX } from '../lib/context.js';
import type { HookInput } from '../types.js';

const OPT_OUT = _internals.OPT_OUT_ENV_VAR;
const DIR_VAR = _internals.DIR_ENV_VAR;
const HOUR = 60 * 60 * 1000;

const SAVED = [OPT_OUT, DIR_VAR] as const;

describe('lifecycle/analytics-liveness-check', () => {
  let tmp: string;
  let stderrSpy: ReturnType<typeof vi.spyOn>;
  const saved: Record<string, string | undefined> = {};

  beforeEach(() => {
    tmp = mkdtempSync(join(tmpdir(), 'analytics-liveness-'));
    stderrSpy = vi.spyOn(process.stderr, 'write').mockImplementation(() => true);
    for (const k of SAVED) {
      saved[k] = process.env[k];
      delete process.env[k];
    }
    process.env[DIR_VAR] = tmp;
  });

  afterEach(() => {
    stderrSpy.mockRestore();
    for (const k of SAVED) {
      if (saved[k] !== undefined) process.env[k] = saved[k];
      else delete process.env[k];
    }
    try {
      rmSync(tmp, { recursive: true, force: true });
    } catch {
      /* best-effort */
    }
  });

  const input = (): HookInput => ({ hook_event: 'SessionStart' }) as HookInput;

  /** Seed a watched writer file whose mtime is `ageHours` in the past. */
  function seedWriter(name: string, ageHours: number): void {
    const p = join(tmp, name);
    writeFileSync(p, '{"ts":"x"}\n');
    const then = new Date(Date.now() - ageHours * HOUR);
    utimesSync(p, then, then);
  }

  it('warns when one writer is stale while a sibling is fresh (the #959-class shape)', () => {
    seedWriter('skill-usage.jsonl', 30 * 24); // dead for a month
    seedWriter('agent-usage.jsonl', 1); // hot

    const result = analyticsLivenessCheck(input(), NOOP_CTX);

    expect(result).toEqual({ continue: true, suppressOutput: true });
    expect(stderrSpy).toHaveBeenCalledOnce();
    const msg = String(stderrSpy.mock.calls[0]?.[0]);
    expect(msg).toContain('skill-usage.jsonl');
    expect(msg).not.toContain('agent-usage.jsonl (last write');
  });

  it('stays silent when every watched writer is fresh', () => {
    seedWriter('skill-usage.jsonl', 2);
    seedWriter('agent-usage.jsonl', 1);
    seedWriter('hook-timing.jsonl', 3);

    analyticsLivenessCheck(input(), NOOP_CTX);

    expect(stderrSpy).not.toHaveBeenCalled();
  });

  it('stays silent when ALL writers are stale (idle machine, not a dead writer)', () => {
    seedWriter('skill-usage.jsonl', 30 * 24);
    seedWriter('agent-usage.jsonl', 29 * 24);

    analyticsLivenessCheck(input(), NOOP_CTX);

    expect(stderrSpy).not.toHaveBeenCalled();
  });

  it('stays silent with fewer than two watched writers present', () => {
    seedWriter('agent-usage.jsonl', 1);

    analyticsLivenessCheck(input(), NOOP_CTX);

    expect(stderrSpy).not.toHaveBeenCalled();
  });

  it('stays silent when the analytics dir does not exist', () => {
    process.env[DIR_VAR] = join(tmp, 'nope');

    const result = analyticsLivenessCheck(input(), NOOP_CTX);

    expect(result).toEqual({ continue: true, suppressOutput: true });
    expect(stderrSpy).not.toHaveBeenCalled();
  });

  it('honors the opt-out env var', () => {
    process.env[OPT_OUT] = '1';
    seedWriter('skill-usage.jsonl', 30 * 24);
    seedWriter('agent-usage.jsonl', 1);

    analyticsLivenessCheck(input(), NOOP_CTX);

    expect(stderrSpy).not.toHaveBeenCalled();
  });

  it('ignores non-watched jsonl files entirely', () => {
    seedWriter('skill-usage.jsonl', 1);
    seedWriter('agent-usage.jsonl', 2);
    // #3665 inverted this default. A dead file that nobody listed used to be
    // INVISIBLE, which is exactly how cache-breaks/dx-signals/session-start-perf
    // stayed unreported for four months. An unlisted stale writer now warns;
    // silencing one is a written decision (RETIRED_WRITERS), not an omission.
    seedWriter('legacy-retired.jsonl', 400 * 24);

    analyticsLivenessCheck(input(), NOOP_CTX);

    expect(stderrSpy).toHaveBeenCalledOnce();
    expect(String(stderrSpy.mock.calls[0]?.[0])).toContain('legacy-retired.jsonl');
  });

  it('findDeadWriters flags every stale writer when multiple die together', () => {
    const dead = _internals.findDeadWriters([
      { name: 'skill-usage.jsonl', ageMs: _internals.STALE_MS + 1 },
      { name: 'hook-timing.jsonl', ageMs: _internals.STALE_MS * 2 },
      { name: 'agent-usage.jsonl', ageMs: 1000 },
    ]);

    expect(dead.map(w => w.name).sort()).toEqual([
      'hook-timing.jsonl',
      'skill-usage.jsonl',
    ]);
  });

  // ── #3665 regression: the guard was watching 3 of 11 writers ──────────────
  //
  // Each test below FAILS against the pre-#3665 hardcoded allowlist, which is
  // what makes them controls rather than restatements of current behaviour.

  it('catches a dead writer that no allowlist ever named (the real #3665 shape)', () => {
    // Exactly the production state measured 2026-08-22: the three allowlisted
    // writers alive, three unlisted ones months dead.
    seedWriter('skill-usage.jsonl', 1);
    seedWriter('agent-usage.jsonl', 1);
    seedWriter('hook-timing.jsonl', 1);
    seedWriter('cache-breaks.jsonl', 139 * 24);
    seedWriter('session-start-perf.jsonl', 136 * 24);
    // dx-signals.jsonl was the third dead file, but it is RETIRED rather than
    // broken (no producer ever existed), so it must NOT appear in the banner.
    seedWriter('dx-signals.jsonl', 138 * 24);

    analyticsLivenessCheck(input(), NOOP_CTX);

    expect(stderrSpy).toHaveBeenCalledOnce();
    const msg = String(stderrSpy.mock.calls[0]?.[0]);
    expect(msg).toContain('cache-breaks.jsonl');
    expect(msg).toContain('session-start-perf.jsonl');
    expect(msg).not.toContain('dx-signals.jsonl');
  });

  it('never flags a rotated archive, whose mtime is frozen by design', () => {
    seedWriter('hook-timing.jsonl', 1);
    seedWriter('skill-usage.jsonl', 2);
    // Both rotation shapes from lib/analytics.ts: dated, and dated-with-index.
    seedWriter('hook-timing.2026-01.jsonl', 200 * 24);
    seedWriter('hook-timing.2026-01.2.jsonl', 200 * 24);

    analyticsLivenessCheck(input(), NOOP_CTX);

    expect(stderrSpy).not.toHaveBeenCalled();
  });

  it('never flags an event-driven writer, whose silence is legitimate', () => {
    seedWriter('hook-timing.jsonl', 1);
    seedWriter('skill-usage.jsonl', 2);
    // secret-audit only writes when a secret is handled; 102 days quiet was
    // correct behaviour on a healthy machine.
    seedWriter('secret-audit.jsonl', 102 * 24);

    analyticsLivenessCheck(input(), NOOP_CTX);

    expect(stderrSpy).not.toHaveBeenCalled();
  });

  it('discoverWriters applies all three exclusions and nothing else', () => {
    seedWriter('hook-timing.jsonl', 1);
    seedWriter('hook-timing.2026-01.jsonl', 1);
    seedWriter('secret-audit.jsonl', 1);
    seedWriter('brand-new-writer.jsonl', 1);
    writeFileSync(join(tmp, 'usage-playground.html'), '<html></html>');

    // A writer nobody has heard of is watched by DEFAULT — that inversion is
    // the fix. Non-jsonl files and archives stay out.
    expect(_internals.discoverWriters(tmp)).toEqual([
      'brand-new-writer.jsonl',
      'hook-timing.jsonl',
    ]);
  });

  it('returns no writers when the analytics dir is absent', () => {
    expect(_internals.discoverWriters(join(tmp, 'does-not-exist'))).toEqual([]);
  });
});
