// Generated by OrchestKit Claude Plugin
// Created: 2026-05-12

/**
 * Lifecycle Output Protocol — Roundtrip Shape Assertions (#1794)
 *
 * WHAT THIS TEST DOES
 * -------------------
 * For every lifecycle hook event that does NOT consume hookEventName or
 * additionalContext (WorktreeCreate, WorktreeRemove, CwdChanged, FileChanged,
 * ConfigChange, InstructionsLoaded, TaskCreated, Notification), this test:
 *
 *   1. Fires a synthetic input through the handler directly.
 *   2. Asserts that result.hookSpecificOutput?.hookEventName is either
 *      undefined OR matches the firing event (never 'UserPromptSubmit').
 *   3. Asserts that result.hookSpecificOutput?.additionalContext is undefined.
 *
 * WHY TWO LAYERS MATTER
 * ---------------------
 * PR-1 (fix/m119.1794-worktree-output-shape) fixes the call-site in
 * worktree-lifecycle-logger.ts. This PR (dispatcher output guard) fixes the
 * structural asymmetry in the dispatcher. This test catches the bug regardless
 * of which layer prevents it — two independent fail-safes.
 *
 * HOW TO VERIFY THE TEST IS NOT VACUOUS
 * --------------------------------------
 * Without both the call-site fix (PR-1) and the dispatcher guard, the
 * WorktreeRemove test below fails because worktree-lifecycle-logger.ts
 * calls outputPromptContext() which stamps hookEventName:'UserPromptSubmit'.
 * The dispatcher guard strips it before CC reads stdout.
 *
 * Refs #1794
 */

import { describe, it, expect, vi, beforeEach, beforeAll } from 'vitest';
import type { HookInput, HookResult } from '../types.js';
import { createTestContext } from './fixtures/test-context.js';

// ---------------------------------------------------------------------------
// Module mocks — must come before dynamic imports
// ---------------------------------------------------------------------------

vi.mock('node:fs', () => ({
  existsSync: vi.fn(() => false),
  readdirSync: vi.fn(() => []),
  readFileSync: vi.fn(() => '{}'),
  writeFileSync: vi.fn(),
  mkdirSync: vi.fn(),
}));

vi.mock('../lib/common.js', async () => {
  const { mockCommonBasic } = await import('./fixtures/mock-common.js');
  return mockCommonBasic();
});

// Silence process.stderr writes during tests (the guard writes WARN lines to stderr)
const stderrSpy = vi.spyOn(process.stderr, 'write').mockImplementation(() => true);

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * Assert that a HookResult does not carry a wrong-event hookEventName.
 * Allowed: undefined, or exactly `expectedEvent`.
 * Forbidden: any other string (especially 'UserPromptSubmit' on lifecycle events).
 */
function assertNoWrongHookEventName(result: HookResult, firingEvent: string): void {
  const hso = result.hookSpecificOutput as Record<string, unknown> | undefined;
  if (!hso) return;
  const hen = hso.hookEventName;
  if (hen === undefined) return;
  expect(hen, `hookEventName must match firing event '${firingEvent}' or be absent`).toBe(firingEvent);
}

/**
 * Assert that a HookResult does not carry additionalContext for events where
 * CC does not read it.
 */
function assertNoAdditionalContext(result: HookResult, firingEvent: string): void {
  const hso = result.hookSpecificOutput as Record<string, unknown> | undefined;
  if (!hso) return;
  expect(
    hso.additionalContext,
    `additionalContext must be absent for ${firingEvent} — CC does not read it for this event`
  ).toBeUndefined();
}

// ---------------------------------------------------------------------------
// Dynamic import of the .mjs output guard
// (vitest.config.ts excludes bin/**/*.mjs from coverage but allows import)
// ---------------------------------------------------------------------------

type SanitizeFn = (result: unknown, firingEvent: string) => unknown;
let sanitizeOutput: SanitizeFn;

beforeAll(async () => {
  // Dynamic import works for .mjs in vitest ESM mode.
  // The module ships from src/hooks/bin/ (alongside run-hook.mjs) so that the
  // build's `rsync --exclude=src` still copies it to the plugin runtime.
  const guard = await import('../../bin/output-guard.mjs');
  sanitizeOutput = guard.sanitizeOutput as SanitizeFn;
});

// ---------------------------------------------------------------------------
// WorktreeCreate
// ---------------------------------------------------------------------------

import { worktreeLifecycleLogger } from '../worktree/worktree-lifecycle-logger.js';

describe('lifecycle output protocol — WorktreeCreate', () => {
  let testCtx: ReturnType<typeof createTestContext>;
  beforeEach(() => { testCtx = createTestContext(); vi.clearAllMocks(); stderrSpy.mockClear(); });

  it('must not stamp hookEventName:UserPromptSubmit on WorktreeCreate (command-type)', () => {
    const input: HookInput = {
      hook_event: 'WorktreeCreate',
      tool_name: '',
      session_id: 'test-session-001',
      tool_input: {},
      name: 'feature-auth',
      project_dir: '/test/project',
    };
    const result = worktreeLifecycleLogger(input, testCtx);
    expect(result.continue).toBe(true);
    assertNoWrongHookEventName(result, 'WorktreeCreate');
    assertNoAdditionalContext(result, 'WorktreeCreate');
  });

  it('must not stamp hookEventName:UserPromptSubmit on WorktreeCreate (http-type)', () => {
    const input: HookInput = {
      hook_event: 'WorktreeCreate',
      tool_name: '',
      session_id: 'test-session-001',
      tool_input: {},
      name: 'feature-auth',
      project_dir: '/test/project',
      type: 'http',
    };
    const result = worktreeLifecycleLogger(input, testCtx);
    expect(result.continue).toBe(true);
    // http-type may set worktreePath — that's fine
    assertNoWrongHookEventName(result, 'WorktreeCreate');
    assertNoAdditionalContext(result, 'WorktreeCreate');
  });
});

// ---------------------------------------------------------------------------
// WorktreeRemove
// ---------------------------------------------------------------------------

describe('lifecycle output protocol — WorktreeRemove', () => {
  let testCtx: ReturnType<typeof createTestContext>;
  beforeEach(() => { testCtx = createTestContext(); vi.clearAllMocks(); stderrSpy.mockClear(); });

  /**
   * REGRESSION TEST FOR #1794
   *
   * Original bug: worktree-lifecycle-logger called outputPromptContext() for
   * WorktreeRemove, stamping hookEventName:'UserPromptSubmit'. CC misread that
   * string and mkdir'd a literal-named directory.
   *
   * This test FAILS if: (a) the call-site fix in worktree-lifecycle-logger.ts
   * is reverted AND (b) the dispatcher guard is disabled. Both must hold.
   */
  it('must not stamp hookEventName:UserPromptSubmit on WorktreeRemove (#1794 regression)', () => {
    const input: HookInput = {
      hook_event: 'WorktreeRemove',
      tool_name: '',
      session_id: 'test-session-001',
      tool_input: {},
      worktree_path: '/Users/dev/.git/worktrees/feature-auth',
      project_dir: '/test/project',
    };
    const result = worktreeLifecycleLogger(input, testCtx);
    expect(result.continue).toBe(true);
    assertNoWrongHookEventName(result, 'WorktreeRemove');
    assertNoAdditionalContext(result, 'WorktreeRemove');
  });
});

// ---------------------------------------------------------------------------
// CwdChanged
// ---------------------------------------------------------------------------

import { cwdChanged } from '../lifecycle/cwd-changed.js';

describe('lifecycle output protocol — CwdChanged (post-guard)', () => {
  let testCtx: ReturnType<typeof createTestContext>;
  beforeEach(() => { testCtx = createTestContext({ pluginRoot: '/test/plugin' }); vi.clearAllMocks(); stderrSpy.mockClear(); });

  it('sanitized output must not have wrong hookEventName or additionalContext for CwdChanged', () => {
    // cwdChanged returns outputNotify/outputWithContext which stamps hookEventName:'PostToolUse'
    // and sets additionalContext. CC does not read either for CwdChanged events.
    // The dispatcher guard strips both before stdout is emitted.
    const input: HookInput = {
      hook_event: 'CwdChanged',
      tool_name: 'CwdChanged',
      session_id: 'test-session-001',
      tool_input: {},
      old_cwd: '/old/project',
      new_cwd: '/new/project',
    };
    const rawResult = cwdChanged(input, testCtx);
    const sanitized = sanitizeOutput(rawResult, 'CwdChanged') as HookResult;
    expect(sanitized.continue).toBe(true);
    assertNoWrongHookEventName(sanitized, 'CwdChanged');
    assertNoAdditionalContext(sanitized, 'CwdChanged');
  });
});

// ---------------------------------------------------------------------------
// FileChanged
// ---------------------------------------------------------------------------

import { fileChanged } from '../lifecycle/file-changed.js';

describe('lifecycle output protocol — FileChanged (post-guard)', () => {
  let testCtx: ReturnType<typeof createTestContext>;
  beforeEach(() => { testCtx = createTestContext(); vi.clearAllMocks(); stderrSpy.mockClear(); });

  it('sanitized output must not have wrong hookEventName or additionalContext for FileChanged', () => {
    // fileChanged returns outputNotify which stamps hookEventName:'PostToolUse'.
    // CC does not read hookEventName or additionalContext for FileChanged events.
    // The dispatcher guard strips them before stdout is emitted.
    const input: HookInput = {
      hook_event: 'FileChanged',
      tool_name: 'FileChanged',
      session_id: 'test-session-001',
      tool_input: {},
      changed_file_path: '/test/project/CLAUDE.md',
      changed_file: 'CLAUDE.md',
    };
    const rawResult = fileChanged(input, testCtx);
    const sanitized = sanitizeOutput(rawResult, 'FileChanged') as HookResult;
    expect(sanitized.continue).toBe(true);
    assertNoWrongHookEventName(sanitized, 'FileChanged');
    assertNoAdditionalContext(sanitized, 'FileChanged');
  });
});

// ---------------------------------------------------------------------------
// ConfigChange, InstructionsLoaded, TaskCreated
// These handlers internally call outputPromptContext() which stamps
// hookEventName:'UserPromptSubmit'. The dispatcher guard strips it.
// We test the post-sanitize (final stdout) shape here.
// ---------------------------------------------------------------------------

import { settingsReload } from '../config-change/settings-reload.js';
import { instructionsLoadedDispatcher } from '../instructions-loaded/instructions-loaded-dispatcher.js';
import { syncTaskCreatedDispatcher } from '../task-created/sync-task-created-dispatcher.js';

describe('lifecycle output protocol — ConfigChange (post-guard)', () => {
  let testCtx: ReturnType<typeof createTestContext>;
  beforeEach(() => { testCtx = createTestContext(); vi.clearAllMocks(); stderrSpy.mockClear(); });

  it('sanitized output must not have hookEventName:UserPromptSubmit for ConfigChange', () => {
    const input: HookInput = {
      hook_event: 'ConfigChange',
      tool_name: 'ConfigChange',
      session_id: 'test-session-001',
      tool_input: {},
      project_dir: '/test/project',
    };
    const rawResult = settingsReload(input, testCtx);
    const sanitized = sanitizeOutput(rawResult, 'ConfigChange') as HookResult;
    expect(sanitized.continue).toBe(true);
    assertNoWrongHookEventName(sanitized, 'ConfigChange');
    assertNoAdditionalContext(sanitized, 'ConfigChange');
  });
});

describe('lifecycle output protocol — InstructionsLoaded (post-guard)', () => {
  let testCtx: ReturnType<typeof createTestContext>;
  beforeEach(() => { testCtx = createTestContext(); vi.clearAllMocks(); stderrSpy.mockClear(); });

  it('sanitized output must not have hookEventName:UserPromptSubmit for InstructionsLoaded', () => {
    const input: HookInput = {
      hook_event: 'InstructionsLoaded',
      tool_name: 'InstructionsLoaded',
      session_id: 'test-session-001',
      tool_input: {},
      project_dir: '/test/project',
    };
    const rawResult = instructionsLoadedDispatcher(input, testCtx);
    const sanitized = sanitizeOutput(rawResult, 'InstructionsLoaded') as HookResult;
    expect(sanitized.continue).toBe(true);
    assertNoWrongHookEventName(sanitized, 'InstructionsLoaded');
    assertNoAdditionalContext(sanitized, 'InstructionsLoaded');
  });
});

describe('lifecycle output protocol — TaskCreated (post-guard)', () => {
  let testCtx: ReturnType<typeof createTestContext>;
  beforeEach(() => { testCtx = createTestContext(); vi.clearAllMocks(); stderrSpy.mockClear(); });

  it('sanitized output must not have hookEventName:UserPromptSubmit for TaskCreated', async () => {
    const input: HookInput = {
      hook_event: 'TaskCreated',
      tool_name: 'TaskCreated',
      session_id: 'test-session-001',
      tool_input: {},
      project_dir: '/test/project',
    };
    // syncTaskCreatedDispatcher is async
    const rawResult = await syncTaskCreatedDispatcher(input, testCtx);
    const sanitized = sanitizeOutput(rawResult, 'TaskCreated') as HookResult;
    expect(sanitized.continue).toBe(true);
    assertNoWrongHookEventName(sanitized, 'TaskCreated');
    assertNoAdditionalContext(sanitized, 'TaskCreated');
  });
});

// ---------------------------------------------------------------------------
// Notification — skip: desktop/sound return outputSilentSuccess (no risk)
// ---------------------------------------------------------------------------

describe('lifecycle output protocol — Notification', () => {
  it.skip('TODO: desktop/sound return outputSilentSuccess — no hookEventName risk; add test if unified-dispatcher ever calls outputPromptContext()', () => {});
});

// ---------------------------------------------------------------------------
// sanitizeOutput unit tests (dispatcher guard in isolation)
// ---------------------------------------------------------------------------

describe('sanitizeOutput (dispatcher output guard)', () => {
  beforeEach(() => { stderrSpy.mockClear(); });

  it('passes through results with no hookSpecificOutput untouched', () => {
    const input = { continue: true, suppressOutput: true };
    expect(sanitizeOutput(input, 'WorktreeCreate')).toEqual(input);
  });

  it('strips hookEventName:UserPromptSubmit from WorktreeCreate response', () => {
    const input = {
      continue: true,
      suppressOutput: true,
      hookSpecificOutput: { hookEventName: 'UserPromptSubmit', additionalContext: 'advisory' },
    };
    const result = sanitizeOutput(input, 'WorktreeCreate') as Record<string, unknown>;
    expect(result.hookSpecificOutput).toBeUndefined();
    expect(stderrSpy).toHaveBeenCalledWith(
      expect.stringContaining('stripped hookEventName=UserPromptSubmit from WorktreeCreate')
    );
  });

  it('strips hookEventName:UserPromptSubmit from WorktreeRemove response (#1794 core)', () => {
    const input = {
      continue: true,
      suppressOutput: true,
      hookSpecificOutput: {
        hookEventName: 'UserPromptSubmit',
        additionalContext: '[WorktreeRemove] Worktree removed: /some/path',
      },
    };
    const result = sanitizeOutput(input, 'WorktreeRemove') as Record<string, unknown>;
    expect(result.hookSpecificOutput).toBeUndefined();
    expect(stderrSpy).toHaveBeenCalledWith(
      expect.stringContaining('stripped hookEventName=UserPromptSubmit from WorktreeRemove')
    );
  });

  it('preserves hookEventName:UserPromptSubmit on UserPromptSubmit events (must not strip)', () => {
    const input = {
      continue: true,
      suppressOutput: true,
      hookSpecificOutput: { hookEventName: 'UserPromptSubmit', additionalContext: 'session context' },
    };
    const result = sanitizeOutput(input, 'UserPromptSubmit') as Record<string, unknown>;
    const hso = result.hookSpecificOutput as Record<string, unknown>;
    expect(hso?.hookEventName).toBe('UserPromptSubmit');
    expect(hso?.additionalContext).toBe('session context');
    expect(stderrSpy).not.toHaveBeenCalled();
  });

  it('preserves hookEventName:PreToolUse on PreToolUse events', () => {
    const input = {
      continue: true,
      suppressOutput: true,
      hookSpecificOutput: { hookEventName: 'PreToolUse', permissionDecision: 'allow', additionalContext: 'ctx' },
    };
    const result = sanitizeOutput(input, 'PreToolUse') as Record<string, unknown>;
    const hso = result.hookSpecificOutput as Record<string, unknown>;
    expect(hso?.hookEventName).toBe('PreToolUse');
    expect(hso?.additionalContext).toBe('ctx');
  });

  it('bypasses all stripping when ORCHESTKIT_DISABLE_OUTPUT_GUARD=1', () => {
    process.env.ORCHESTKIT_DISABLE_OUTPUT_GUARD = '1';
    try {
      const input = {
        continue: true,
        hookSpecificOutput: { hookEventName: 'UserPromptSubmit', additionalContext: 'advisory' },
      };
      const result = sanitizeOutput(input, 'WorktreeCreate') as Record<string, unknown>;
      const hso = result.hookSpecificOutput as Record<string, unknown>;
      expect(hso?.hookEventName).toBe('UserPromptSubmit');
      expect(stderrSpy).not.toHaveBeenCalled();
    } finally {
      delete process.env.ORCHESTKIT_DISABLE_OUTPUT_GUARD;
    }
  });

  it('does not mutate the original result object', () => {
    const input = {
      continue: true,
      hookSpecificOutput: { hookEventName: 'UserPromptSubmit', additionalContext: 'advisory' },
    };
    const originalHSO = input.hookSpecificOutput;
    sanitizeOutput(input, 'WorktreeCreate');
    // Original must be unmodified
    expect(input.hookSpecificOutput).toBe(originalHSO);
    expect(input.hookSpecificOutput.hookEventName).toBe('UserPromptSubmit');
  });
});
