// Generated by OrchestKit Claude Plugin
// Created: 2026-08-08

/**
 * output-guard must not strip output CC actually reads.
 *
 * The guard held two HAND-TYPED allow-lists whose provenance comment cited
 * "types.ts plus the #1234 audit" — one hand-maintained artifact plus a memory.
 * Both were wrong. CC's shipped binary documents Stop, SubagentStop and
 * PostToolBatch as additionalContext consumers, verbatim:
 *
 *   "Hook-specific output for the Stop event. additionalContext is non-error
 *    feedback delivered to the model; the conversation continues so the model
 *    can act on it."
 *   "Hook-specific output for the SubagentStop event. additionalContext is
 *    non-error feedback delivered to the subagent..."
 *   "Return additionalContext via hookSpecificOutput to inject context once
 *    for the whole batch."                                    [PostToolBatch]
 *
 * The guard named none of them, so it silently DELETED additionalContext from
 * six live hooks: stop/task-completion-check, stop/stop-failure-handler,
 * stop/session-summary, subagent-stop/sync-subagent-stop-dispatcher,
 * subagent-stop/subagent-scope-auditor, subagent-stop/retry-handler.
 *
 * A guard that wrongly ALLOWS gets caught — something misbehaves. A guard that
 * wrongly STRIPS produces silence. That is the direction nobody checks, so it
 * is the direction this file checks.
 *
 * Every case below FAILS against the pre-2026-08-08 allow-lists.
 */
import { describe, it, expect } from 'vitest';
import { sanitizeOutput } from '../../bin/output-guard.mjs';
import {
  EVENTS_WITH_ADDITIONAL_CONTEXT,
  EVENTS_WITH_HOOK_EVENT_NAME,
  UNVERIFIED_KEYS,
} from '../../bin/cc-output-keys.generated.mjs';

/** What a hook returns when it wants to hand feedback back to the model. */
const withContext = (event: string) => ({
  continue: true,
  hookSpecificOutput: {
    hookEventName: event,
    additionalContext: 'feedback the model is meant to receive',
  },
});

describe('the guard preserves additionalContext where CC reads it', () => {
  // Documented by the binary. All three were absent from the old allow-list.
  it.each(['Stop', 'SubagentStop', 'PostToolBatch'])(
    'does NOT strip additionalContext on %s',
    (event) => {
      const out = sanitizeOutput(withContext(event), event) as {
        hookSpecificOutput?: { additionalContext?: string; hookEventName?: string };
      };
      expect(out.hookSpecificOutput?.additionalContext).toBe(
        'feedback the model is meant to receive'
      );
      expect(out.hookSpecificOutput?.hookEventName).toBe(event);
    }
  );

  // The events the old list did get right — kept so a fix cannot regress them.
  it.each([
    'UserPromptSubmit',
    'PreToolUse',
    'PostToolUse',
    'PostToolUseFailure',
    'SessionStart',
    'PostCompact',
  ])('still preserves additionalContext on %s', (event) => {
    const out = sanitizeOutput(withContext(event), event) as {
      hookSpecificOutput?: { additionalContext?: string };
    };
    expect(out.hookSpecificOutput?.additionalContext).toBeDefined();
  });
});

describe('the guard still strips where CC does NOT read', () => {
  // #1794: a WorktreeCreate response carrying a UserPromptSubmit envelope made
  // CC create a literal-named directory from the additionalContext string.
  // The guard must keep failing that case, or this fix is just a disable.
  it.each(['CwdChanged', 'FileChanged', 'ConfigChange', 'TaskCreated'])(
    'strips additionalContext on %s',
    (event) => {
      const out = sanitizeOutput(withContext(event), event) as {
        hookSpecificOutput?: { additionalContext?: string };
      };
      expect(out.hookSpecificOutput?.additionalContext).toBeUndefined();
    }
  );

  it('drops hookSpecificOutput entirely once it is emptied', () => {
    const out = sanitizeOutput(withContext('CwdChanged'), 'CwdChanged') as {
      hookSpecificOutput?: unknown;
      continue?: boolean;
    };
    expect(out.hookSpecificOutput).toBeUndefined();
    expect(out.continue).toBe(true);
  });
});

describe('WorktreeCreate keeps its documented envelope', () => {
  // "WorktreeCreate hook failed: hook succeeded but returned no worktree path
  //  (command: echo the path to stdout; http/callback: return
  //  hookSpecificOutput.worktreePath)"
  // The old allow-list omitted WorktreeCreate, so the guard stripped
  // hookEventName and broke the documented http/callback form.
  it('does not strip hookEventName on WorktreeCreate', () => {
    const result = {
      continue: true,
      hookSpecificOutput: {
        hookEventName: 'WorktreeCreate',
        worktreePath: '/tmp/wt',
      },
    };
    const out = sanitizeOutput(result, 'WorktreeCreate') as {
      hookSpecificOutput?: { hookEventName?: string; worktreePath?: string };
    };
    expect(out.hookSpecificOutput?.hookEventName).toBe('WorktreeCreate');
    expect(out.hookSpecificOutput?.worktreePath).toBe('/tmp/wt');
  });
});

describe('the generated contract is internally coherent', () => {
  it('every additionalContext event also accepts hookSpecificOutput', () => {
    // CC requires hookEventName inside every hookSpecificOutput. An event that
    // reads additionalContext but is missing from the hookEventName list would
    // be unrepresentable.
    for (const event of EVENTS_WITH_ADDITIONAL_CONTEXT as Set<string>) {
      expect(
        (EVENTS_WITH_HOOK_EVENT_NAME as Set<string>).has(event),
        `${event} reads additionalContext but is absent from EVENTS_WITH_HOOK_EVENT_NAME`
      ).toBe(true);
    }
  });

  it('carries the three events the hand-typed list was missing', () => {
    for (const event of ['Stop', 'SubagentStop', 'PostToolBatch']) {
      expect(
        (EVENTS_WITH_ADDITIONAL_CONTEXT as Set<string>).has(event),
        `${event} is documented by the CC binary and must be allow-listed`
      ).toBe(true);
    }
  });

  it('never strips a key the spec marks UNVERIFIED', () => {
    // Unverified means "we do not know", and stripping on not-knowing is
    // exactly how Stop broke. The guard must leave these alone.
    for (const key of UNVERIFIED_KEYS as Set<string>) {
      const result = {
        continue: true,
        hookSpecificOutput: { hookEventName: 'PreToolUse', [key]: 'value' },
      };
      const out = sanitizeOutput(result, 'PreToolUse') as {
        hookSpecificOutput?: Record<string, unknown>;
      };
      expect(
        out.hookSpecificOutput?.[key],
        `${key} is UNVERIFIED and must not be stripped`
      ).toBe('value');
    }
  });
});
