// Generated by OrchestKit Claude Plugin
// Created: 2026-04-08

/**
 * Skill Frontmatter Hooks Invariant (CC 2.1.94+)
 *
 * CC 2.1.94 fixed "plugin skill hooks defined in YAML frontmatter being
 * silently ignored". Before 2.1.94, these blocks were dead code — a skill
 * could reference a non-existent handler and nothing would break.
 *
 * With the fix activated, every frontmatter reference is now live. A missing
 * handler would cause CC to spawn a subprocess that writes "No such file or
 * directory" to stderr on every tool invocation while the skill is active.
 *
 * This test enforces the invariant: every `${CLAUDE_PLUGIN_ROOT}/hooks/bin/
 * run-hook.mjs skill/<name>` command in a SKILL.md frontmatter must resolve
 * to an exported handler in src/hooks/src/entries/skill.ts.
 *
 * If this test fails:
 *   - Either the handler was renamed/removed and the SKILL.md still
 *     references it → fix the SKILL.md frontmatter
 *   - Or the SKILL.md added a new handler that isn't registered yet →
 *     add it to src/hooks/src/entries/skill.ts hooks map
 */

import { describe, test, expect } from 'vitest';
import { readdirSync, readFileSync, statSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const SKILLS_DIR = join(__dirname, '..', '..', '..', '..', 'src', 'skills');

/**
 * Extract YAML frontmatter from a Markdown file.
 * Returns the text between the first `---` and the next `---`, or null.
 */
function extractFrontmatter(content: string): string | null {
  const match = content.match(/^---\s*\n([\s\S]*?)\n---\s*$/m);
  return match ? match[1] : null;
}

/**
 * Extract all `skill/<name>` hook references from a YAML frontmatter block.
 * Matches patterns like:
 *   command: "${CLAUDE_PLUGIN_ROOT}/hooks/bin/run-hook.mjs skill/foo-bar"
 */
function extractSkillHookRefs(frontmatter: string): string[] {
  // Use matchAll (no regex.exec) — the security scanner flags `exec` as a false positive
  const matches = frontmatter.matchAll(/run-hook\.mjs\s+(skill\/[\w-]+)/g);
  return Array.from(matches, m => m[1]);
}

/**
 * Recursively find all SKILL.md files under src/skills/.
 */
function findAllSkillFiles(dir: string): string[] {
  const results: string[] = [];
  for (const entry of readdirSync(dir)) {
    const fullPath = join(dir, entry);
    const stat = statSync(fullPath);
    if (stat.isDirectory()) {
      const skillFile = join(fullPath, 'SKILL.md');
      try {
        statSync(skillFile);
        results.push(skillFile);
      } catch {
        // No SKILL.md in this directory — recurse in case of nesting
        results.push(...findAllSkillFiles(fullPath));
      }
    }
  }
  return results;
}

describe('Skill frontmatter hooks invariant (CC 2.1.94+)', () => {
  test('all SKILL.md frontmatter hook refs resolve to exported handlers', async () => {
    // Import the registered hooks map from the skill entry point
    const skillEntry = await import('../entries/skill.js');
    const registered = new Set(skillEntry.listHooks());

    const skillFiles = findAllSkillFiles(SKILLS_DIR);
    expect(skillFiles.length).toBeGreaterThan(50); // sanity check — we have 100+ skills

    const missing: Array<{ skill: string; ref: string }> = [];
    const foundRefs: Array<{ skill: string; ref: string }> = [];

    for (const file of skillFiles) {
      const content = readFileSync(file, 'utf8');
      const fm = extractFrontmatter(content);
      if (!fm) continue;

      const refs = extractSkillHookRefs(fm);
      for (const ref of refs) {
        foundRefs.push({ skill: file, ref });
        if (!registered.has(ref)) {
          missing.push({ skill: file, ref });
        }
      }
    }

    // We expect to find the ~20 known frontmatter hook references
    expect(foundRefs.length).toBeGreaterThanOrEqual(15);

    if (missing.length > 0) {
      const report = missing
        .map(m => `  - ${m.skill.replace(SKILLS_DIR, 'src/skills')}: ${m.ref}`)
        .join('\n');
      throw new Error(
        `Found ${missing.length} SKILL.md frontmatter hook references ` +
        `that don't resolve to registered handlers in src/hooks/src/entries/skill.ts:\n${report}\n\n` +
        `CC 2.1.94 activates these hooks — unregistered refs will fail on every invocation. ` +
        `Either register the handler in skill.ts or remove the reference from SKILL.md frontmatter.`
      );
    }
  });

  test('at least one SKILL.md declares a frontmatter hook (regression guard)', () => {
    // Guard against accidental mass-deletion — if this drops to zero we've
    // likely broken a lot of skill context loading.
    const skillFiles = findAllSkillFiles(SKILLS_DIR);
    let total = 0;
    for (const file of skillFiles) {
      const content = readFileSync(file, 'utf8');
      const fm = extractFrontmatter(content);
      if (fm) total += extractSkillHookRefs(fm).length;
    }
    expect(total).toBeGreaterThanOrEqual(15);
  });
});
