// Generated by OrchestKit Claude Plugin
// Created: 2026-03-14

import { describe, test, expect, vi, beforeEach } from 'vitest';
import { PricingService, type LoyaltyApiClient, type Promotion } from './pricing.service.js';

// ─── Helpers ────────────────────────────────────────────────────────────────

function makeLoyaltyApi(tier: import('./pricing.service.js').CustomerTier = 'standard'): LoyaltyApiClient {
  return { getCustomerTier: vi.fn().mockResolvedValue(tier) };
}

const FIXED_NOW = new Date('2025-06-01T12:00:00Z');

// ─── Fixtures ────────────────────────────────────────────────────────────────

const PROMO_10: Promotion = { code: 'SAVE10', discountPercent: 10 };
const PROMO_20: Promotion = { code: 'BIG20', discountPercent: 20 };
const PROMO_WITH_MIN: Promotion = { code: 'MIN200', discountPercent: 15, minOrderTotal: 200 };
const PROMO_EXPIRED: Promotion = {
  code: 'EXPIRED',
  discountPercent: 30,
  expiresAt: new Date('2025-01-01T00:00:00Z'),
};
const PROMO_NOT_YET_EXPIRED: Promotion = {
  code: 'VALID',
  discountPercent: 5,
  expiresAt: new Date('2025-12-31T23:59:59Z'),
};

// ─── Tier discounts ──────────────────────────────────────────────────────────

describe('tier-based discounts', () => {
  test.each([
    { tier: 'standard' as const, rate: 0,    discount: 0,  final: 200 },
    { tier: 'silver'   as const, rate: 0.05, discount: 10, final: 190 },
    { tier: 'gold'     as const, rate: 0.10, discount: 20, final: 180 },
    { tier: 'platinum' as const, rate: 0.15, discount: 30, final: 170 },
  ])('$tier tier gets $discount discount on $200 order', async ({ tier, discount, final: finalTotal }) => {
    // Arrange
    const svc = new PricingService(makeLoyaltyApi(tier));

    // Act
    const result = await svc.calculatePrice('u1', 200, [], FIXED_NOW);

    // Assert
    expect(result.discountAmount).toBe(discount);
    expect(result.finalTotal).toBe(finalTotal);
    if (tier === 'standard') {
      expect(result.appliedDiscounts).toEqual([]);
    } else {
      expect(result.appliedDiscounts).toContain(`tier:${tier}`);
    }
  });
});

// ─── Volume discounts ────────────────────────────────────────────────────────

describe('volume-based discounts', () => {
  let svc: PricingService;

  beforeEach(() => {
    svc = new PricingService(makeLoyaltyApi('standard'));
  });

  test('below $100 gets no volume discount', async () => {
    const result = await svc.calculatePrice('u1', 99.99, [], FIXED_NOW);
    expect(result.appliedDiscounts).toEqual(
      expect.not.arrayContaining([expect.stringContaining('volume')]),
    );
    expect(result.discountAmount).toBe(0);
  });

  test('exactly $100 triggers 5% volume discount', async () => {
    const result = await svc.calculatePrice('u1', 100, [], FIXED_NOW);
    expect(result.discountAmount).toBe(5);    // 100 × 0.05
    expect(result.appliedDiscounts).toContain('volume:100');
  });

  test('$500+ triggers 10% volume discount (not stacked with $100 bracket)', async () => {
    const result = await svc.calculatePrice('u1', 500, [], FIXED_NOW);
    expect(result.discountAmount).toBe(50);   // 500 × 0.10
    expect(result.appliedDiscounts).toContain('volume:500');
    expect(result.appliedDiscounts).not.toContain('volume:100');
  });

  test('order between $100 and $499 uses 5% bracket', async () => {
    const result = await svc.calculatePrice('u1', 300, [], FIXED_NOW);
    expect(result.discountAmount).toBe(15);   // 300 × 0.05
    expect(result.appliedDiscounts).toContain('volume:100');
  });
});

// ─── Promotions ───────────────────────────────────────────────────────────────

describe('promotions', () => {
  let svc: PricingService;

  beforeEach(() => {
    svc = new PricingService(makeLoyaltyApi('standard'));
  });

  test('valid promo is applied', async () => {
    const result = await svc.calculatePrice('u1', 100, [PROMO_10], FIXED_NOW);
    expect(result.discountAmount).toBe(10);   // 100 × 0.10
    expect(result.appliedDiscounts).toContain('promo:SAVE10');
  });

  test('multiple promos stack additively', async () => {
    const result = await svc.calculatePrice('u1', 100, [PROMO_10, PROMO_20], FIXED_NOW);
    // 100 × (0.10 + 0.20) = 30
    expect(result.discountAmount).toBe(30);
    expect(result.appliedDiscounts).toContain('promo:SAVE10');
    expect(result.appliedDiscounts).toContain('promo:BIG20');
  });

  test('expired promo is ignored', async () => {
    const result = await svc.calculatePrice('u1', 100, [PROMO_EXPIRED], FIXED_NOW);
    expect(result.discountAmount).toBe(0);
    expect(result.appliedDiscounts).not.toContain('promo:EXPIRED');
  });

  test('promo expiring in the future is applied', async () => {
    const result = await svc.calculatePrice('u1', 100, [PROMO_NOT_YET_EXPIRED], FIXED_NOW);
    expect(result.discountAmount).toBe(5);
    expect(result.appliedDiscounts).toContain('promo:VALID');
  });

  test('promo expiring exactly at "now" is NOT applied', async () => {
    const exactExpiry: Promotion = { code: 'EDGE', discountPercent: 10, expiresAt: FIXED_NOW };
    const result = await svc.calculatePrice('u1', 100, [exactExpiry], FIXED_NOW);
    expect(result.discountAmount).toBe(0);
  });

  test('promo with minOrderTotal is skipped when order is below threshold', async () => {
    const result = await svc.calculatePrice('u1', 150, [PROMO_WITH_MIN], FIXED_NOW);
    expect(result.appliedDiscounts).not.toContain('promo:MIN200');
  });

  test('promo with minOrderTotal is applied when order meets threshold', async () => {
    const result = await svc.calculatePrice('u1', 200, [PROMO_WITH_MIN], FIXED_NOW);
    expect(result.appliedDiscounts).toContain('promo:MIN200');
    expect(result.discountAmount).toBe(30);   // 200 × 0.15
  });

  test('empty promotions list applies no promo discounts', async () => {
    const result = await svc.calculatePrice('u1', 100, [], FIXED_NOW);
    expect(result.appliedDiscounts.filter((d) => d.startsWith('promo:'))).toHaveLength(0);
  });
});

// ─── Discount stacking ───────────────────────────────────────────────────────

describe('discount stacking', () => {
  test('tier + volume + promo all stack', async () => {
    // gold (10%) + volume:100 (5%) + SAVE10 (10%) = 25% of 200 = 50
    const svc = new PricingService(makeLoyaltyApi('gold'));
    const result = await svc.calculatePrice('u1', 200, [PROMO_10], FIXED_NOW);

    expect(result.discountAmount).toBe(50);
    expect(result.finalTotal).toBe(150);
    expect(result.appliedDiscounts).toEqual(
      expect.arrayContaining(['tier:gold', 'volume:100', 'promo:SAVE10']),
    );
  });

  test('total discount is capped at 50%', async () => {
    // platinum (15%) + volume:500 (10%) + BIG20 (20%) + SAVE10 (10%) = 55% → capped at 50%
    const svc = new PricingService(makeLoyaltyApi('platinum'));
    const result = await svc.calculatePrice('u1', 1000, [PROMO_20, PROMO_10], FIXED_NOW);

    expect(result.discountAmount).toBe(500);   // 1000 × 0.50
    expect(result.finalTotal).toBe(500);
  });
});

// ─── Loyalty API failures ────────────────────────────────────────────────────

describe('loyalty API failure handling', () => {
  test('API timeout falls back to standard tier silently', async () => {
    const api: LoyaltyApiClient = {
      getCustomerTier: vi.fn().mockRejectedValue(new Error('timeout')),
    };
    const svc = new PricingService(api);
    const result = await svc.calculatePrice('u1', 200, [], FIXED_NOW);

    // Standard tier = no tier discount; 200 qualifies for volume:100 only
    expect(result.discountAmount).toBe(10);   // 200 × 0.05
    expect(result.appliedDiscounts).toEqual(
      expect.not.arrayContaining([expect.stringMatching(/^tier:/)]),
    );
  });

  test('API network error falls back to standard tier', async () => {
    const api: LoyaltyApiClient = {
      getCustomerTier: vi.fn().mockRejectedValue(new Error('ECONNREFUSED')),
    };
    const svc = new PricingService(api);
    const result = await svc.calculatePrice('u1', 50, [], FIXED_NOW);

    expect(result.discountAmount).toBe(0);
    expect(result.finalTotal).toBe(50);
  });

  test('loyalty API is called with the correct customer ID', async () => {
    const api: LoyaltyApiClient = {
      getCustomerTier: vi.fn().mockResolvedValue('standard'),
    };
    const svc = new PricingService(api);
    await svc.calculatePrice('customer-xyz', 100, [], FIXED_NOW);

    expect(api.getCustomerTier).toHaveBeenCalledOnce();
    expect(api.getCustomerTier).toHaveBeenCalledWith('customer-xyz');
  });
});

// ─── Edge cases ───────────────────────────────────────────────────────────────

describe('edge cases', () => {
  let svc: PricingService;

  beforeEach(() => {
    svc = new PricingService(makeLoyaltyApi('standard'));
  });

  test('zero order total returns all zeros', async () => {
    const result = await svc.calculatePrice('u1', 0, [PROMO_10], FIXED_NOW);
    expect(result.originalTotal).toBe(0);
    expect(result.discountAmount).toBe(0);
    expect(result.finalTotal).toBe(0);
  });

  test('negative order total throws', async () => {
    await expect(svc.calculatePrice('u1', -1)).rejects.toThrow('orderTotal must be non-negative');
  });

  test('result preserves originalTotal unchanged', async () => {
    const result = await svc.calculatePrice('u1', 123.45, [PROMO_10], FIXED_NOW);
    expect(result.originalTotal).toBe(123.45);
  });

  test('discountAmount + finalTotal equals originalTotal', async () => {
    const result = await svc.calculatePrice('u1', 99.99, [PROMO_10], FIXED_NOW);
    expect(result.discountAmount + result.finalTotal).toBeCloseTo(result.originalTotal, 2);
  });

  test('fractional totals are rounded to 2 decimal places', async () => {
    // 33.33 × 10% = 3.333 → 3.33
    const result = await svc.calculatePrice('u1', 33.33, [PROMO_10], FIXED_NOW);
    expect(result.discountAmount.toString()).toMatch(/^\d+(\.\d{1,2})?$/);
  });

  test('default "now" parameter works without explicit date', async () => {
    const result = await svc.calculatePrice('u1', 100);
    expect(result).toHaveProperty('finalTotal');
    expect(result.originalTotal).toBe(100);
  });
});
