// Generated by OrchestKit Claude Plugin
// Created: 2026-07-15

/**
 * Tests for notification/message-display-observer (MessageDisplay, CC 2.1.208).
 *
 * P3-A3 contract: OBSERVER ONLY. Every input — empty, malformed, oversized —
 * must return { continue: true, suppressOutput: true }. Message CONTENT is
 * never logged (assistant output can quote secrets) — only size metrics.
 */

import { describe, test, expect, vi, beforeEach } from 'vitest';
import type { HookInput } from '../../types.js';

vi.mock('../../lib/common.js', async () => {
  const actual = await vi.importActual<typeof import('../../lib/common.js')>('../../lib/common.js');
  return { ...actual, logHook: vi.fn() };
});

import { messageDisplayObserver } from '../../notification/message-display-observer.js';
import { logHook } from '../../lib/common.js';

function expectSilentContinue(result: Record<string, unknown>): void {
  expect(result.continue).toBe(true);
  expect(result.suppressOutput).toBe(true);
  expect(result.decision).toBeUndefined();
  expect(result.systemMessage).toBeUndefined();
  expect(result.hookSpecificOutput).toBeUndefined();
}

describe('notification/message-display-observer', () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  test('empty input {} returns silent continue', async () => {
    const result = await messageDisplayObserver({} as HookInput);
    expectSilentContinue(result as unknown as Record<string, unknown>);
  });

  test('absent/unknown fields return silent continue', async () => {
    const input = {
      hook_event: 'MessageDisplay',
      session_id: 'test-session',
      tool_name: '',
      tool_input: {},
      message: null, // wrong type — must be tolerated
      unknown_future_field: ['a', 'b'],
    } as unknown as HookInput;
    const result = await messageDisplayObserver(input);
    expectSilentContinue(result as unknown as Record<string, unknown>);
  });

  test('oversized payload returns silent continue with a compact logged line', async () => {
    const huge = ('line with secret sk-ant-abc123\n').repeat(200_000); // ~6MB
    const input = {
      hook_event: 'MessageDisplay',
      session_id: 'test-session',
      tool_name: '',
      tool_input: {},
      message: huge,
    } as unknown as HookInput;

    const result = await messageDisplayObserver(input);
    expectSilentContinue(result as unknown as Record<string, unknown>);

    const line = vi.mocked(logHook).mock.calls[0]?.[1] ?? '';
    expect(line.length).toBeLessThan(256);
    expect(line).toContain(`len=${huge.length}`);
    expect(line).toContain('truncated_scan=true');
  });

  test('never logs message content (secrets stay out of hooks.log)', async () => {
    const input = {
      message: 'your API key is ghp_supersecret and the password is hunter2',
      session_id: 'test-session',
      tool_name: '',
      tool_input: {},
    } as unknown as HookInput;
    const result = await messageDisplayObserver(input);
    expectSilentContinue(result as unknown as Record<string, unknown>);

    const line = vi.mocked(logHook).mock.calls[0]?.[1] ?? '';
    expect(line).not.toContain('ghp_supersecret');
    expect(line).not.toContain('hunter2');
    expect(line).toMatch(/len=\d+ lines=\d+/);
  });
});
