// Generated by OrchestKit Claude Plugin
// Created: 2026-03-29

/**
 * Unit tests for workflow-preference-learner hook
 * Tests: main hook, getPrimaryWorkflowPreference, getAllWorkflowPreferences, getWorkflowSummary
 */

import { describe, it, expect, vi, beforeEach } from 'vitest';
import { mockCommonBasic } from '../fixtures/mock-common.js';

// ---------------------------------------------------------------------------
// Hoisted mocks
// ---------------------------------------------------------------------------
const { mockExistsSync, mockReadFileSync, mockMkdirSync, mockAtomicWriteSync } = vi.hoisted(() => ({
  mockExistsSync: vi.fn((_p?: string) => false),
  mockReadFileSync: vi.fn((_p?: string, _e?: string) => ''),
  mockMkdirSync: vi.fn((_p?: string, _o?: unknown) => undefined),
  mockAtomicWriteSync: vi.fn((_p?: string, _d?: string) => undefined),
}));

const { mockAnalyzeDecisionFlow, mockCompleteDecisionFlow } = vi.hoisted(() => ({
  mockAnalyzeDecisionFlow: vi.fn(),
  mockCompleteDecisionFlow: vi.fn(),
}));

// ---------------------------------------------------------------------------
// Module mocks
// ---------------------------------------------------------------------------
vi.mock('../../lib/common.js', () => mockCommonBasic({
  getSessionId: vi.fn(() => 'test-session-001'),
}));

vi.mock('../../lib/decision-flow-tracker.js', () => ({
  analyzeDecisionFlow: (input: unknown) => mockAnalyzeDecisionFlow(input),
  completeDecisionFlow: (input: unknown) => mockCompleteDecisionFlow(input),
}));

vi.mock('node:fs', () => ({
  existsSync: (p: string) => mockExistsSync(p),
  readFileSync: (p: string, e?: string) => mockReadFileSync(p, e),
  mkdirSync: (p: string, o?: unknown) => mockMkdirSync(p, o),
}));

vi.mock('../../lib/atomic-write.js', () => ({
  atomicWriteSync: (p: string, d: string) => mockAtomicWriteSync(p, d),
}));

vi.mock('node:path', () => ({
  join: vi.fn((...args: string[]) => args.join('/')),
  dirname: vi.fn((p: string) => p.split('/').slice(0, -1).join('/')),
}));

// ---------------------------------------------------------------------------
// Imports (after mocks)
// ---------------------------------------------------------------------------
import {
  workflowPreferenceLearner,
  getPrimaryWorkflowPreference,
  getAllWorkflowPreferences,
  getWorkflowSummary,
} from '../../stop/workflow-preference-learner.js';
import { logHook } from '../../lib/common.js';
import type { HookInput } from '../../types.js';

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------
function makeInput(overrides: Partial<HookInput> = {}): HookInput {
  return {
    hook_event: 'Stop',
    tool_name: '',
    session_id: 'test-session-001',
    tool_input: {},
    ...overrides,
  };
}

function makeFlow(overrides: Record<string, unknown> = {}) {
  return {
    session_id: 'test-session-001',
    actions: Array.from({ length: 10 }, (_, i) => ({
      tool: 'Write',
      timestamp: new Date().toISOString(),
      category: 'write',
      summary: `action-${i}`,
    })),
    inferred_pattern: 'test-first',
    stats: { success_rate: 0.9, total: 10 },
    ...overrides,
  };
}

function makePreferencesData(overrides: Record<string, unknown> = {}) {
  return {
    pattern_counts: { 'test-first': 6, 'explore-first': 2, 'iterate-fast': 0, 'big-bang': 0, 'agent-delegate': 0, 'mixed': 0 },
    pattern_success_rates: { 'test-first': [0.8, 0.9], 'explore-first': [0.7], 'iterate-fast': [], 'big-bang': [], 'agent-delegate': [], 'mixed': [] },
    total_sessions: 8,
    preferences: [
      { pattern: 'test-first', frequency: 0.75, count: 6, total_sessions: 8, avg_success_rate: 0.85, updated_at: '2026-01-01T00:00:00Z' },
      { pattern: 'explore-first', frequency: 0.25, count: 2, total_sessions: 8, avg_success_rate: 0.7, updated_at: '2026-01-01T00:00:00Z' },
    ],
    updated_at: '2026-01-01T00:00:00Z',
    ...overrides,
  };
}

// ===========================================================================
// TESTS
// ===========================================================================
describe('workflow-preference-learner', () => {
  beforeEach(() => {
    vi.clearAllMocks();
    mockExistsSync.mockReturnValue(false);
  });

  // =========================================================================
  // workflowPreferenceLearner (main hook)
  // =========================================================================
  describe('workflowPreferenceLearner', () => {
    it('returns silent success when no decision flow found', () => {
      // Arrange
      mockAnalyzeDecisionFlow.mockReturnValue(null);

      // Act
      const result = workflowPreferenceLearner(makeInput());

      // Assert
      expect(result).toEqual({ continue: true, suppressOutput: true });
      expect(logHook).toHaveBeenCalledWith(
        'workflow-preference-learner',
        expect.stringContaining('No decision flow found'),
        'debug',
      );
    });

    it('returns silent success when too few actions', () => {
      // Arrange
      mockAnalyzeDecisionFlow.mockReturnValue(makeFlow({
        actions: [{ tool: 'Write', timestamp: '', category: 'write', summary: 'a' }],
      }));

      // Act
      const result = workflowPreferenceLearner(makeInput());

      // Assert
      expect(result).toEqual({ continue: true, suppressOutput: true });
      expect(logHook).toHaveBeenCalledWith(
        'workflow-preference-learner',
        expect.stringContaining('Too few actions'),
        'debug',
      );
    });

    it('returns silent success for mixed pattern without saving', () => {
      // Arrange
      mockAnalyzeDecisionFlow.mockReturnValue(makeFlow({ inferred_pattern: 'mixed' }));

      // Act
      const result = workflowPreferenceLearner(makeInput());

      // Assert
      expect(result).toEqual({ continue: true, suppressOutput: true });
      expect(mockCompleteDecisionFlow).toHaveBeenCalledWith('test-session-001');
      // Should NOT attempt to save preferences for mixed
      expect(mockAtomicWriteSync).not.toHaveBeenCalled();
    });

    it('saves preferences for valid non-mixed pattern', () => {
      // Arrange
      mockAnalyzeDecisionFlow.mockReturnValue(makeFlow());
      mockExistsSync.mockReturnValue(false); // No existing file

      // Act
      const result = workflowPreferenceLearner(makeInput());

      // Assert
      expect(result).toEqual({ continue: true, suppressOutput: true });
      expect(mockCompleteDecisionFlow).toHaveBeenCalledWith('test-session-001');
      expect(mockAtomicWriteSync).toHaveBeenCalledTimes(1);

      // Verify written data
      const writtenJson = JSON.parse(mockAtomicWriteSync.mock.calls[0][1] as string);
      expect(writtenJson.total_sessions).toBe(1);
      expect(writtenJson.pattern_counts['test-first']).toBe(1);
    });

    it('loads and updates existing preferences', () => {
      // Arrange
      const existing = makePreferencesData();
      mockExistsSync.mockReturnValue(true);
      mockReadFileSync.mockReturnValue(JSON.stringify(existing));
      mockAnalyzeDecisionFlow.mockReturnValue(makeFlow());

      // Act
      workflowPreferenceLearner(makeInput());

      // Assert
      const writtenJson = JSON.parse(mockAtomicWriteSync.mock.calls[0][1] as string);
      expect(writtenJson.total_sessions).toBe(9); // 8 + 1
      expect(writtenJson.pattern_counts['test-first']).toBe(7); // 6 + 1
    });

    it('uses input.session_id when provided', () => {
      // Arrange
      mockAnalyzeDecisionFlow.mockReturnValue(null);

      // Act
      workflowPreferenceLearner(makeInput({ session_id: 'custom-session' }));

      // Assert
      expect(mockAnalyzeDecisionFlow).toHaveBeenCalledWith('custom-session');
    });

    it('logs strong preference when frequency > 0.6 and count >= 5', () => {
      // Arrange
      const existing = makePreferencesData();
      mockExistsSync.mockReturnValue(true);
      mockReadFileSync.mockReturnValue(JSON.stringify(existing));
      mockAnalyzeDecisionFlow.mockReturnValue(makeFlow());

      // Act
      workflowPreferenceLearner(makeInput());

      // Assert
      expect(logHook).toHaveBeenCalledWith(
        'workflow-preference-learner',
        expect.stringContaining('Strong workflow preference'),
        'info',
      );
    });

    it('handles corrupt preferences file gracefully', () => {
      // Arrange
      mockExistsSync.mockReturnValue(true);
      mockReadFileSync.mockReturnValue('not-json');
      mockAnalyzeDecisionFlow.mockReturnValue(makeFlow());

      // Act
      const result = workflowPreferenceLearner(makeInput());

      // Assert
      expect(result).toEqual({ continue: true, suppressOutput: true });
      expect(mockAtomicWriteSync).toHaveBeenCalled();
    });

    it('creates directory if it does not exist', () => {
      // Arrange
      mockAnalyzeDecisionFlow.mockReturnValue(makeFlow());
      mockExistsSync.mockReturnValue(false);

      // Act
      workflowPreferenceLearner(makeInput());

      // Assert
      expect(mockMkdirSync).toHaveBeenCalledWith(expect.any(String), { recursive: true });
    });

    it('returns silent success when save fails', () => {
      // Arrange
      mockAnalyzeDecisionFlow.mockReturnValue(makeFlow());
      mockExistsSync.mockReturnValue(false);
      mockAtomicWriteSync.mockImplementation(() => { throw new Error('disk full'); });

      // Act
      const result = workflowPreferenceLearner(makeInput());

      // Assert
      expect(result).toEqual({ continue: true, suppressOutput: true });
      expect(logHook).toHaveBeenCalledWith(
        'workflow-preference-learner',
        expect.stringContaining('Failed to save'),
        'warn',
      );
    });
  });

  // =========================================================================
  // getPrimaryWorkflowPreference
  // =========================================================================
  describe('getPrimaryWorkflowPreference', () => {
    it('returns null when no preferences file exists', () => {
      // Arrange
      mockExistsSync.mockReturnValue(false);

      // Act
      const result = getPrimaryWorkflowPreference();

      // Assert
      expect(result).toBeNull();
    });

    it('returns top preference when file exists', () => {
      // Arrange
      mockExistsSync.mockReturnValue(true);
      mockReadFileSync.mockReturnValue(JSON.stringify(makePreferencesData()));

      // Act
      const result = getPrimaryWorkflowPreference();

      // Assert
      expect(result).not.toBeNull();
      expect(result!.pattern).toBe('test-first');
      expect(result!.frequency).toBe(0.75);
    });
  });

  // =========================================================================
  // getAllWorkflowPreferences
  // =========================================================================
  describe('getAllWorkflowPreferences', () => {
    it('returns empty array when no file exists', () => {
      // Arrange
      mockExistsSync.mockReturnValue(false);

      // Act
      const result = getAllWorkflowPreferences();

      // Assert
      expect(result).toEqual([]);
    });

    it('returns all preferences sorted by frequency', () => {
      // Arrange
      mockExistsSync.mockReturnValue(true);
      mockReadFileSync.mockReturnValue(JSON.stringify(makePreferencesData()));

      // Act
      const result = getAllWorkflowPreferences();

      // Assert
      expect(result).toHaveLength(2);
      expect(result[0].pattern).toBe('test-first');
      expect(result[1].pattern).toBe('explore-first');
    });
  });

  // =========================================================================
  // getWorkflowSummary
  // =========================================================================
  describe('getWorkflowSummary', () => {
    it('returns null when fewer than 3 sessions', () => {
      // Arrange
      mockExistsSync.mockReturnValue(true);
      mockReadFileSync.mockReturnValue(JSON.stringify(makePreferencesData({ total_sessions: 2 })));

      // Act
      const result = getWorkflowSummary();

      // Assert
      expect(result).toBeNull();
    });

    it('returns null when no clear preference (frequency < 0.4)', () => {
      // Arrange
      const data = makePreferencesData({
        preferences: [
          { pattern: 'test-first', frequency: 0.3, count: 3, total_sessions: 10, avg_success_rate: 0.8, updated_at: '' },
        ],
      });
      mockExistsSync.mockReturnValue(true);
      mockReadFileSync.mockReturnValue(JSON.stringify(data));

      // Act
      const result = getWorkflowSummary();

      // Assert
      expect(result).toBeNull();
    });

    it('returns null when no preferences exist', () => {
      // Arrange
      mockExistsSync.mockReturnValue(false);

      // Act
      const result = getWorkflowSummary();

      // Assert
      expect(result).toBeNull();
    });

    it('returns description string for strong preference', () => {
      // Arrange
      mockExistsSync.mockReturnValue(true);
      mockReadFileSync.mockReturnValue(JSON.stringify(makePreferencesData()));

      // Act
      const result = getWorkflowSummary();

      // Assert
      expect(result).not.toBeNull();
      expect(result).toContain('writes tests before implementation');
      expect(result).toContain('75%');
      expect(result).toContain('85%');
    });

    it('returns correct description for explore-first pattern', () => {
      // Arrange
      const data = makePreferencesData({
        total_sessions: 5,
        preferences: [
          { pattern: 'explore-first', frequency: 0.6, count: 3, total_sessions: 5, avg_success_rate: 0.9, updated_at: '' },
        ],
      });
      mockExistsSync.mockReturnValue(true);
      mockReadFileSync.mockReturnValue(JSON.stringify(data));

      // Act
      const result = getWorkflowSummary();

      // Assert
      expect(result).toContain('reads existing code before making changes');
    });
  });

  // =========================================================================
  // Edge cases: success rate tracking
  // =========================================================================
  describe('success rate capping', () => {
    it('keeps only last 20 success rates per pattern', () => {
      // Arrange — start with 19 success rates, add 2 more sessions
      const existingRates = Array.from({ length: 19 }, () => 0.8);
      const data = makePreferencesData({
        pattern_counts: { 'test-first': 19, 'explore-first': 0, 'iterate-fast': 0, 'big-bang': 0, 'agent-delegate': 0, 'mixed': 0 },
        pattern_success_rates: { 'test-first': existingRates, 'explore-first': [], 'iterate-fast': [], 'big-bang': [], 'agent-delegate': [], 'mixed': [] },
        total_sessions: 19,
      });

      // First call: adds to 20
      mockExistsSync.mockReturnValue(true);
      mockReadFileSync.mockReturnValue(JSON.stringify(data));
      mockAnalyzeDecisionFlow.mockReturnValue(makeFlow({ stats: { success_rate: 0.95, total: 10 } }));

      // Act
      workflowPreferenceLearner(makeInput());

      // Assert
      const writtenJson = JSON.parse(mockAtomicWriteSync.mock.calls[0][1] as string);
      expect(writtenJson.pattern_success_rates['test-first']).toHaveLength(20);
      expect(writtenJson.pattern_success_rates['test-first'][19]).toBe(0.95);
    });
  });
});
