#!/usr/bin/env bash
# Generated by OrchestKit Claude Plugin
# Created: 2026-09-06

# Gate: tests/plugins/test-cc-discovery-simulation.sh
# Pass condition: FAILED == 0. FAILED only rises when the skills dir or agents dir
# is MISSING, or an agent .md lacks name:/description:. A skills dir and an agents
# dir that exist but are EMPTY produce total_skills=0, agent_count=0, zero metadata
# assertions, and "PASSED: Plugin is properly structured for CC 2.1.16 discovery".
set -uo pipefail

REPO="${REPO:?set by the fault-arms runner}"
GATE="$REPO/tests/plugins/test-cc-discovery-simulation.sh"
FIX="$H/fixtures/cc-discovery-simulation"

rm -rf "$FIX"
for arm in control fault; do
  mkdir -p "$FIX/$arm/plugins/ork/.claude-plugin" "$FIX/$arm/plugins/ork/skills" "$FIX/$arm/src/agents"
  cp "$REPO/plugins/ork/.claude-plugin/plugin.json" "$FIX/$arm/plugins/ork/.claude-plugin/plugin.json"
done

# control: two real skills and two real agents copied verbatim from the repo.
for s in doctor help; do
  mkdir -p "$FIX/control/plugins/ork/skills/$s"
  cp "$REPO/plugins/ork/skills/$s/SKILL.md" "$FIX/control/plugins/ork/skills/$s/SKILL.md"
done
for a in test-generator security-auditor; do
  cp "$REPO/src/agents/$a.md" "$FIX/control/src/agents/$a.md"
done

# fault: the same directories exist and are empty (an interrupted build, #3578 shape).

CLAUDE_PROJECT_DIR="$FIX/control" bash "$GATE" >"$FIX/control.log" 2>&1
control_rc=$?
CLAUDE_PROJECT_DIR="$FIX/fault" bash "$GATE" >"$FIX/fault.log" 2>&1
fault_rc=$?

{
  echo "--- control tail ---"; tail -6 "$FIX/control.log"
  echo "--- fault tail ---";   tail -6 "$FIX/fault.log"
} >&2

printf 'RESULT gate=%s control=%s fault=%s\n' "cc-discovery-simulation" "$control_rc" "$fault_rc"
