// Generated by OrchestKit Claude Plugin
// Created: 2026-04-17

import { describe, test, expect, beforeEach, afterEach } from 'vitest';
import { mkdtempSync, writeFileSync, rmSync, existsSync, mkdirSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { tmpdir } from 'node:os';
import {
  findThrashingFiles,
  readAndTrimHistory,
  MAX_ENTRIES,
  thrashDetector,
} from '../../prompt/thrash-detector.js';
import { NOOP_CTX } from '../../lib/context.js';

describe('thrash-detector — pure logic', () => {
  describe('findThrashingFiles', () => {
    test('returns empty when no file hits 3 edits in the window', () => {
      const entries = [
        { t: 1, f: '/a.ts' },
        { t: 2, f: '/b.ts' },
        { t: 3, f: '/c.ts' },
      ];
      expect(findThrashingFiles(entries).size).toBe(0);
    });

    test('flags a file that hits 3+ edits in the last 10 events', () => {
      const entries = [
        { t: 1, f: '/a.ts' },
        { t: 2, f: '/a.ts' },
        { t: 3, f: '/b.ts' },
        { t: 4, f: '/a.ts' },
      ];
      const thrashing = findThrashingFiles(entries);
      expect(thrashing.get('/a.ts')).toBe(3);
      expect(thrashing.has('/b.ts')).toBe(false);
    });

    test('windows only the last 10 events — older edits drop out', () => {
      const entries = [
        // 3 edits to /old.ts will fall outside the 10-event window once we add 10 more
        { t: 1, f: '/old.ts' },
        { t: 2, f: '/old.ts' },
        { t: 3, f: '/old.ts' },
        ...Array.from({ length: 10 }, (_, i) => ({ t: 10 + i, f: '/fresh.ts' })),
      ];
      const thrashing = findThrashingFiles(entries);
      expect(thrashing.has('/old.ts')).toBe(false);
      expect(thrashing.get('/fresh.ts')).toBe(10);
    });
  });

  describe('readAndTrimHistory', () => {
    let tmp: string;

    beforeEach(() => {
      tmp = mkdtempSync(join(tmpdir(), 'thrash-test-'));
    });
    afterEach(() => {
      rmSync(tmp, { recursive: true, force: true });
    });

    test('returns [] when file does not exist', () => {
      expect(readAndTrimHistory(join(tmp, 'absent.jsonl'))).toEqual([]);
    });

    test('parses valid JSONL, skips malformed lines', () => {
      const p = join(tmp, 'hist.jsonl');
      writeFileSync(p, '{"t":1,"f":"/a.ts"}\nnot-json\n{"t":2,"f":"/b.ts"}\n', 'utf8');
      const entries = readAndTrimHistory(p);
      expect(entries.map(e => e.f)).toEqual(['/a.ts', '/b.ts']);
    });

    test('trims file in-place when over MAX_ENTRIES', () => {
      const p = join(tmp, 'huge.jsonl');
      const lines = Array.from({ length: MAX_ENTRIES + 20 }, (_, i) => JSON.stringify({ t: i, f: `/f${i}.ts` })).join('\n');
      writeFileSync(p, `${lines}\n`, 'utf8');
      const entries = readAndTrimHistory(p);
      expect(entries.length).toBe(MAX_ENTRIES);
      // Verify the trim was written back
      expect(readAndTrimHistory(p).length).toBe(MAX_ENTRIES);
    });
  });

  describe('thrashDetector — end-to-end', () => {
    let tmp: string;

    beforeEach(() => {
      tmp = mkdtempSync(join(tmpdir(), 'thrash-e2e-'));
    });
    afterEach(() => {
      rmSync(tmp, { recursive: true, force: true });
    });

    test('silent when no history exists', () => {
      const result = thrashDetector({} as never, { ...NOOP_CTX, projectDir: tmp });
      expect(result.hookSpecificOutput).toBeUndefined();
    });

    test('injects advisory when thrash detected', () => {
      // Seed history with 4 edits to the same file
      const dir = resolve(tmp, '.claude', 'state');
      mkdirSync(dir, { recursive: true });
      const p = resolve(dir, 'edit-history.jsonl');
      const body = [1, 2, 3, 4].map(t => JSON.stringify({ t, f: '/src/auth.ts', tool: 'Edit' })).join('\n');
      writeFileSync(p, `${body}\n`, 'utf8');
      expect(existsSync(p)).toBe(true);

      const result = thrashDetector({} as never, { ...NOOP_CTX, projectDir: tmp });
      const ctx = (result.hookSpecificOutput as { additionalContext?: string })?.additionalContext;
      expect(ctx).toBeDefined();
      expect(ctx).toContain('[thrash-detector]');
      expect(ctx).toContain('auth.ts');
    });

    // #2919: the history file is shared per-project — the window must only
    // count the CURRENT session's edits, or concurrent sessions produce
    // false thrash warnings for files they never touched.
    test('ignores another session\'s edits (#2919 cross-session bleed)', () => {
      const dir = resolve(tmp, '.claude', 'state');
      mkdirSync(dir, { recursive: true });
      const p = resolve(dir, 'edit-history.jsonl');
      const body = [1, 2, 3, 4]
        .map(t => JSON.stringify({ t, f: '/src/auth.ts', tool: 'Edit', sid: 'session-A' }))
        .join('\n');
      writeFileSync(p, `${body}\n`, 'utf8');

      const result = thrashDetector(
        { session_id: 'session-B' } as never,
        { ...NOOP_CTX, projectDir: tmp, sessionId: 'session-B' },
      );
      expect(result.hookSpecificOutput).toBeUndefined();
    });

    test('fires for own session even when interleaved with another session (#2919)', () => {
      const dir = resolve(tmp, '.claude', 'state');
      mkdirSync(dir, { recursive: true });
      const p = resolve(dir, 'edit-history.jsonl');
      const rows: string[] = [];
      for (let t = 1; t <= 4; t++) {
        rows.push(JSON.stringify({ t: t * 2 - 1, f: '/src/auth.ts', tool: 'Edit', sid: 'session-A' }));
        rows.push(JSON.stringify({ t: t * 2, f: '/src/other.ts', tool: 'Edit', sid: 'session-B' }));
      }
      writeFileSync(p, `${rows.join('\n')}\n`, 'utf8');

      const result = thrashDetector(
        { session_id: 'session-A' } as never,
        { ...NOOP_CTX, projectDir: tmp, sessionId: 'session-A' },
      );
      const ctx = (result.hookSpecificOutput as { additionalContext?: string })?.additionalContext;
      expect(ctx).toBeDefined();
      expect(ctx).toContain('auth.ts');
    });

    test('legacy records without sid never match a real session (#2919)', () => {
      const dir = resolve(tmp, '.claude', 'state');
      mkdirSync(dir, { recursive: true });
      const p = resolve(dir, 'edit-history.jsonl');
      const body = [1, 2, 3, 4].map(t => JSON.stringify({ t, f: '/src/auth.ts', tool: 'Edit' })).join('\n');
      writeFileSync(p, `${body}\n`, 'utf8');

      const result = thrashDetector(
        { session_id: 'session-A' } as never,
        { ...NOOP_CTX, projectDir: tmp, sessionId: 'session-A' },
      );
      expect(result.hookSpecificOutput).toBeUndefined();
    });
  });

  // #4651: subagents share the parent session id, so the window pooled their
  // edits, the message printed a bare basename, and the same warning repeated
  // on every later prompt even with no new edit.
  describe('thrashDetector: per agent, project paths, no repeats (#4651)', () => {
    let tmp: string;

    beforeEach(() => {
      tmp = mkdtempSync(join(tmpdir(), 'thrash-4651-'));
    });
    afterEach(() => {
      rmSync(tmp, { recursive: true, force: true });
    });

    function seed(rows: Array<Record<string, unknown>>): string {
      const dir = resolve(tmp, '.claude', 'state');
      mkdirSync(dir, { recursive: true });
      const p = resolve(dir, 'edit-history.jsonl');
      writeFileSync(p, `${rows.map(r => JSON.stringify(r)).join('\n')}\n`, 'utf8');
      return p;
    }

    function run(): string | undefined {
      const result = thrashDetector(
        { session_id: 'parent' } as never,
        { ...NOOP_CTX, projectDir: tmp, sessionId: 'parent' },
      );
      return (result.hookSpecificOutput as { additionalContext?: string } | undefined)?.additionalContext;
    }

    test('three subagents editing one file once each is not thrash', () => {
      const f = join(tmp, 'scripts', 'validate-deploy.sh');
      seed(['a1', 'a2', 'a3'].map((agent, i) => ({ t: i + 1, f, tool: 'Edit', sid: 'parent', agent })));
      expect(run()).toBeUndefined();
    });

    test('one subagent editing one file three times is still thrash', () => {
      const f = join(tmp, 'scripts', 'validate-deploy.sh');
      seed([1, 2, 3].map(t => ({ t, f, tool: 'Edit', sid: 'parent', agent: 'a1' })));
      expect(run()).toContain('validate-deploy.sh');
    });

    test('names the file by its path relative to the project, not the basename', () => {
      const f = join(tmp, 'scripts', 'deploy', 'validate-deploy.sh');
      seed([1, 2, 3].map(t => ({ t, f, tool: 'Edit', sid: 'parent' })));
      expect(run()).toContain('scripts/deploy/validate-deploy.sh');
    });

    test('a second prompt with no new edit since the warning stays silent', () => {
      const f = join(tmp, 'src', 'auth.ts');
      const p = seed([1, 2, 3].map(t => ({ t, f, tool: 'Edit', sid: 'parent' })));
      expect(run()).toBeDefined();
      expect(run()).toBeUndefined();

      // A newer edit to the thrashing file earns the warning again.
      writeFileSync(p, `${JSON.stringify({ t: 4, f, tool: 'Edit', sid: 'parent' })}\n`, { flag: 'a' });
      expect(run()).toBeDefined();
    });
  });
});
