// Generated by OrchestKit Claude Plugin
// Created: 2026-06-08
import { buildLlmsTxt } from "@/lib/llms-txt";

// /api/llms.txt.md — Markdown twin of /api/llms.txt. Same body (heading-led,
// starts with a top-level `#`), but served as text/markdown so agents and
// renderers that content-negotiate on the `.md` extension get the right type.
// Content is generated by the shared buildLlmsTxt() helper — no duplication.
export const revalidate = false;

export function GET() {
	const body = buildLlmsTxt();

	return new Response(body, {
		headers: {
			"Content-Type": "text/markdown; charset=utf-8",
			"Cache-Control": "public, max-age=3600",
		},
	});
}
