/**
 * Unit tests for write-headers hook
 * Tests addition of standard headers to new files based on file type
 */

import { describe, it, expect, vi, beforeEach } from 'vitest';

// Mock dependencies before imports
vi.mock('../../lib/common.js', () => ({
  logHook: vi.fn(),
  outputSilentSuccess: vi.fn(() => ({ continue: true, suppressOutput: true })),
  outputWithUpdatedInput: vi.fn((updated: Record<string, unknown>) => ({
    continue: true,
    suppressOutput: true,
    hookSpecificOutput: {
      hookEventName: 'PreToolUse',
      updatedInput: updated,
    },
  })),
}));

vi.mock('node:fs', () => ({
  existsSync: vi.fn(() => false),
}));

vi.mock('node:path', () => ({
  extname: vi.fn((p: string) => {
    const dot = p.lastIndexOf('.');
    return dot >= 0 ? p.slice(dot) : '';
  }),
}));

import { writeHeaders } from '../../pretool/input-mod/write-headers.js';
import type { HookInput } from '../../types.js';
import { existsSync } from 'node:fs';

function createWriteInput(filePath: string, content: string): HookInput {
  return {
    tool_name: 'Write',
    session_id: 'test-session-123',
    project_dir: '/test/project',
    tool_input: { file_path: filePath, content },
  };
}

describe('write-headers', () => {
  beforeEach(() => {
    vi.clearAllMocks();
    vi.mocked(existsSync).mockReturnValue(false);
  });

  it('returns silent success for non-Write tools', () => {
    const input: HookInput = {
      tool_name: 'Edit',
      session_id: 'test-session-123',
      project_dir: '/test/project',
      tool_input: { file_path: 'src/app.ts', old_string: 'a', new_string: 'b' },
    };
    const result = writeHeaders(input);

    expect(result.continue).toBe(true);
    expect(result.suppressOutput).toBe(true);
  });

  it('returns silent success when file already exists', () => {
    vi.mocked(existsSync).mockReturnValue(true);

    const input = createWriteInput('src/existing.ts', 'const x = 1;');
    const result = writeHeaders(input);

    expect(result.continue).toBe(true);
    expect(result.suppressOutput).toBe(true);
  });

  it('adds Python comment header for new .py files', () => {
    const input = createWriteInput('src/module.py', 'def main():\n    pass');
    const result = writeHeaders(input);

    expect(result.continue).toBe(true);
    const updated = result.hookSpecificOutput?.updatedInput;
    expect(updated).toBeDefined();
    expect(String(updated?.content)).toContain('# Generated by OrchestKit Claude Plugin');
    expect(String(updated?.content)).toContain('def main()');
  });

  it('adds JS/TS comment header for new .ts files', () => {
    const input = createWriteInput('src/app.ts', 'export const app = {};');
    const result = writeHeaders(input);

    expect(result.continue).toBe(true);
    const updated = result.hookSpecificOutput?.updatedInput;
    expect(String(updated?.content)).toContain('// Generated by OrchestKit Claude Plugin');
  });

  it('skips header for JSON files', () => {
    const input = createWriteInput('config/settings.json', '{"key": "value"}');
    const result = writeHeaders(input);

    expect(result.continue).toBe(true);
    expect(result.suppressOutput).toBe(true);
  });

  it('skips header when content already contains OrchestKit marker', () => {
    const input = createWriteInput(
      'src/new-file.ts',
      '// Generated by OrchestKit Claude Plugin\nconst x = 1;'
    );
    const result = writeHeaders(input);

    expect(result.continue).toBe(true);
    expect(result.suppressOutput).toBe(true);
  });
});
