#!/usr/bin/env bash
# Generated by OrchestKit Claude Plugin
# Created: 2026-09-06

# scripts/ci/check-skill-structure.sh [skills-dir]
#
# Every skill directory must carry a SKILL.md. Called by plugin-validation.yml
# "Skills Validation" against the BUILT plugin tree (plugins/ork/skills).
#
# History: this used to be an inline workflow step that tested `[[ -d skills ]]`
# at the checkout ROOT and exited 0 with "No skills directory found" when the
# directory was absent. The repo has had no root skills/ since the plugins/
# restructure, so the step passed on every run without looking at a single
# skill (measured 2026-09-06, docs/audits/gate-fault-arm-audit-2026-09-06.md).
# A gate whose input is missing is a failed gate, not a passed one:
#   missing dir  -> exit 1
#   zero skills  -> exit 1
#   any skill without SKILL.md -> exit 1
#
# Exit 0 only when at least one skill exists and every one has a SKILL.md.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="${CLAUDE_PROJECT_DIR:-$(cd "$SCRIPT_DIR/../.." && pwd)}"
SKILLS_DIR="${1:-$PROJECT_ROOT/plugins/ork/skills}"

echo "Validating skills (flat structure) in ${SKILLS_DIR}..."

if [[ ! -d "$SKILLS_DIR" ]]; then
  echo "ERROR: skills directory not found: $SKILLS_DIR"
  echo "       Was the plugin built (npm run build) and the artifact downloaded?"
  exit 1
fi

errors=0
skill_count=0

for skill_dir in "$SKILLS_DIR"/*/; do
  [[ -d "$skill_dir" ]] || continue
  skill_name=$(basename "$skill_dir")
  skill_count=$((skill_count + 1))

  if [[ ! -f "$skill_dir/SKILL.md" ]]; then
    echo "  ERROR: $skill_name missing SKILL.md"
    errors=$((errors + 1))
  fi
done

echo "Validated $skill_count skills"

if [[ $skill_count -eq 0 ]]; then
  echo "ERROR: zero skill directories under $SKILLS_DIR; nothing was validated"
  exit 1
fi

if [[ $errors -gt 0 ]]; then
  echo "Found $errors skill errors"
  exit 1
fi

echo "All skills are valid!"
