#!/usr/bin/env bash
# Generated by OrchestKit Claude Plugin
# Created: 2026-02-12

# detect-plan-context.sh — Auto-detect plan context from git state
# Usage: bash detect-plan-context.sh [issue_number]
set -euo pipefail

# Detect base branch
BASE_BRANCH="main"
if git rev-parse --verify dev &>/dev/null; then
  # Check if current branch was created from dev
  MERGE_BASE_MAIN=$(git merge-base HEAD main 2>/dev/null || echo "")
  MERGE_BASE_DEV=$(git merge-base HEAD dev 2>/dev/null || echo "")
  if [ -n "$MERGE_BASE_DEV" ] && [ "$MERGE_BASE_DEV" != "$MERGE_BASE_MAIN" ]; then
    BASE_BRANCH="dev"
  fi
fi

# Current branch
BRANCH=$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "unknown")

# Extract issue number from branch name (feat/thing-#123 or feat/thing-123)
ISSUE_REF="${1:-}"
if [ -z "$ISSUE_REF" ]; then
  ISSUE_REF=$(echo "$BRANCH" | grep -oE '#?[0-9]+' | tail -1 || echo "")
  if [ -n "$ISSUE_REF" ]; then
    ISSUE_REF="#${ISSUE_REF#\#}"
  fi
fi

# Plan name from branch
PLAN_NAME=$(echo "$BRANCH" | sed -E 's|^feat/||;s|^fix/||;s|^chore/||;s|^refactor/||;s|^docs/||' | tr '-' ' ' | awk '{for(i=1;i<=NF;i++) $i=toupper(substr($i,1,1)) tolower(substr($i,2))}1')

# Commit count since divergence
COMMIT_COUNT=$(git rev-list --count "${BASE_BRANCH}..HEAD" 2>/dev/null || echo "0")

# File change summary
DIFF_STAT=$(git diff --stat "${BASE_BRANCH}...HEAD" 2>/dev/null || echo "No changes detected")

# Files by action
FILES_ADDED=$(git diff --diff-filter=A --name-only "${BASE_BRANCH}...HEAD" 2>/dev/null | wc -l | tr -d ' ')
FILES_MODIFIED=$(git diff --diff-filter=M --name-only "${BASE_BRANCH}...HEAD" 2>/dev/null | wc -l | tr -d ' ')
FILES_DELETED=$(git diff --diff-filter=D --name-only "${BASE_BRANCH}...HEAD" 2>/dev/null | wc -l | tr -d ' ')
FILES_TOTAL=$((FILES_ADDED + FILES_MODIFIED + FILES_DELETED))

# Line counts
LINES=$(git diff --numstat "${BASE_BRANCH}...HEAD" 2>/dev/null | awk '{a+=$1; r+=$2} END {printf "+%d -%d", a, r}' || echo "+0 -0")

# Issue title (if gh available and issue detected)
ISSUE_TITLE=""
if [ -n "$ISSUE_REF" ] && command -v gh &>/dev/null; then
  ISSUE_NUM="${ISSUE_REF#\#}"
  ISSUE_TITLE=$(gh issue view "$ISSUE_NUM" --json title -q '.title' 2>/dev/null || echo "")
fi

# Output structured context
echo "=== PLAN CONTEXT ==="
echo "Branch: $BRANCH"
echo "Base: $BASE_BRANCH"
echo "Plan Name: $PLAN_NAME"
echo "Issue: ${ISSUE_REF:-none}"
[ -n "$ISSUE_TITLE" ] && echo "Issue Title: $ISSUE_TITLE"
echo "Commits: $COMMIT_COUNT"
echo "Files: $FILES_TOTAL ($FILES_ADDED added, $FILES_MODIFIED modified, $FILES_DELETED deleted)"
echo "Lines: $LINES"
echo ""
echo "=== DIFF STAT ==="
echo "$DIFF_STAT"
