// Generated by OrchestKit Claude Plugin
// Created: 2026-06-01

/**
 * Skill Channel Tracker (SubagentStop)
 *
 * Closes the biggest telemetry blind spot: skills invoked *inside* a subagent.
 * The PreToolUse·Skill tracker only sees main-session Skill calls — a subagent
 * runs in an isolated context, so its Skill invocations never reach the parent
 * session's hooks. When a subagent finishes, this handler reads its transcript
 * (`agent_transcript_path`, CC 2.1.69+), extracts every `Skill` tool_use, and
 * records each as a `channel:"subagent"` row in skill-channels.jsonl tagged with
 * the subagent type as parent.
 *
 * Read-only + best-effort: never blocks, never throws (the dispatcher also
 * try/catches each handler). Always returns silent success.
 */

import { existsSync, readFileSync } from 'node:fs';
import type { HookInput, HookResult, HookContext } from '../types.js';
import { outputSilentSuccess } from '../lib/common.js';
import { NOOP_CTX } from '../lib/context.js';
import { recordSkillChannel } from '../lib/skill-channels.js';

const HOOK_NAME = 'skill-channel-tracker';

interface TranscriptToolUse {
  type?: string;
  name?: string;
  input?: { skill?: string };
}

interface TranscriptLine {
  message?: { content?: unknown };
}

/** Pull skill names from one transcript line's tool_use blocks (Skill calls only). */
export function skillsInLine(line: TranscriptLine): string[] {
  const content = line.message?.content;
  if (!Array.isArray(content)) return [];
  const out: string[] = [];
  for (const block of content as TranscriptToolUse[]) {
    if (block?.type === 'tool_use' && block?.name === 'Skill') {
      const skill = block.input?.skill;
      if (typeof skill === 'string' && skill.length > 0) out.push(skill);
    }
  }
  return out;
}

export function skillChannelTracker(input: HookInput, ctx: HookContext = NOOP_CTX): HookResult {
  const transcriptPath = input.agent_transcript_path;
  if (!transcriptPath || !existsSync(transcriptPath)) {
    return outputSilentSuccess();
  }

  const projectDir = input.project_dir || ctx.projectDir;
  const parent = input.subagent_type || input.agent_type || 'unknown';

  let content: string;
  try {
    content = readFileSync(transcriptPath, 'utf8');
  } catch {
    return outputSilentSuccess();
  }

  let recorded = 0;
  for (const raw of content.split('\n')) {
    if (!raw.trim()) continue;
    let parsed: TranscriptLine;
    try {
      parsed = JSON.parse(raw) as TranscriptLine;
    } catch {
      continue;
    }
    for (const skill of skillsInLine(parsed)) {
      recordSkillChannel(projectDir, {
        skill,
        channel: 'subagent',
        parent,
        sessionId: input.session_id,
      });
      recorded++;
    }
  }

  if (recorded > 0) {
    ctx.log(HOOK_NAME, `Recorded ${recorded} subagent-channel skill call(s) from ${parent}`);
  }

  return outputSilentSuccess();
}
