// Generated by OrchestKit Claude Plugin
// Created: 2026-06-11

// OpenAPI `components` for the public docs API — referenced from
// app/api/openapi/route.ts. Kept beside `paths.ts` so spec and implementation
// stay reviewable together.

export const RATE_LIMIT_HEADER_REFS = {
	"RateLimit-Limit": { $ref: "#/components/headers/RateLimit-Limit" },
	"RateLimit-Remaining": { $ref: "#/components/headers/RateLimit-Remaining" },
	"RateLimit-Reset": { $ref: "#/components/headers/RateLimit-Reset" },
	"RateLimit-Policy": { $ref: "#/components/headers/RateLimit-Policy" },
} as const;

export const OPENAPI_COMPONENTS = {
	parameters: {
		IdempotencyKey: {
			name: "Idempotency-Key",
			in: "header",
			required: false,
			description:
				"Client-chosen key for correlating retries. Every endpoint is a read (naturally idempotent); the key is echoed back in the response's `Idempotency-Key` header.",
			schema: { type: "string", maxLength: 255 },
		},
		Limit: {
			name: "limit",
			in: "query",
			required: false,
			description:
				"Page size. Omit for all results. The total before pagination is returned in the `X-Total-Count` response header.",
			schema: { type: "integer", minimum: 1, maximum: 100 },
		},
		Cursor: {
			name: "cursor",
			in: "query",
			required: false,
			description:
				'Opaque pagination cursor from a previous response\'s `X-Next-Cursor` header (or `Link: rel="next"`). Omit for the first page. Cursor-based — page contents do not drift between requests.',
			schema: { type: "string" },
		},
	},
	headers: {
		"RateLimit-Limit": {
			description: "Requests allowed in the current window (per IP, per endpoint).",
			schema: { type: "integer" },
		},
		"RateLimit-Remaining": {
			description: "Requests remaining in the current window.",
			schema: { type: "integer" },
		},
		"RateLimit-Reset": {
			description: "Seconds until the current window resets.",
			schema: { type: "integer" },
		},
		"RateLimit-Policy": {
			description: 'Quota policy, e.g. "120;w=60" (120 requests per 60-second window).',
			schema: { type: "string" },
		},
	},
	schemas: {
		SearchResult: {
			type: "object",
			description: "A single documentation search hit.",
			properties: {
				id: { type: "string", description: "Stable result id." },
				url: { type: "string", description: "Path to the doc page." },
				type: {
					type: "string",
					description: "Match granularity (page | heading | text).",
				},
				content: {
					type: "string",
					description: "Matching heading or text excerpt.",
				},
			},
			required: ["id", "url"],
		},
		NlwebResult: {
			type: "object",
			description:
				"NLWeb result: a documentation page answering the query. Carries both NLWeb-canonical fields (name, site, score, description) and this API's stable fields (id, title, url, content).",
			properties: {
				id: { type: "string", description: "Stable result id." },
				name: { type: "string", description: "Page title (NLWeb-canonical)." },
				title: { type: "string", description: "Page title." },
				url: { type: "string", description: "Absolute URL of the doc page." },
				site: { type: "string", description: "Origin site of the result." },
				score: {
					type: "number",
					minimum: 0,
					maximum: 1,
					description: "Relevance score, 1 = best match.",
				},
				description: { type: "string", description: "Text excerpt (NLWeb-canonical)." },
				content: { type: "string", description: "Text excerpt." },
			},
			required: ["name", "url", "score"],
		},
		AskRequest: {
			type: "object",
			properties: {
				query: {
					type: "string",
					minLength: 1,
					description: "The natural-language question (aliases: `q`, `question`).",
				},
				mode: {
					type: "string",
					enum: ["list", "summarize", "generate"],
					default: "list",
					description: "NLWeb response mode.",
				},
				streaming: {
					type: "boolean",
					default: false,
					description: "Stream the response as Server-Sent Events.",
				},
			},
			required: ["query"],
		},
		AskResponse: {
			type: "object",
			properties: {
				query_id: { type: "string", description: "Server-assigned id for this query." },
				query: { type: "string", description: "The query as interpreted." },
				results: {
					type: "array",
					items: { $ref: "#/components/schemas/NlwebResult" },
				},
				_meta: {
					type: "object",
					description: "NLWeb metadata.",
					properties: {
						response_type: { type: "string", examples: ["list"] },
						version: { type: "string" },
						count: { type: "integer" },
					},
					required: ["response_type", "version"],
				},
			},
			required: ["results", "_meta"],
		},
		BatchMarkdownRequest: {
			type: "object",
			properties: {
				paths: {
					type: "array",
					minItems: 1,
					maxItems: 20,
					items: { type: "string" },
					description:
						"Doc URL paths to fetch, e.g. /docs/getting-started/installation.",
				},
			},
			required: ["paths"],
		},
		BatchMarkdownResponse: {
			type: "object",
			properties: {
				results: {
					type: "array",
					description: "One entry per requested path, in request order.",
					items: {
						type: "object",
						properties: {
							path: { type: "string" },
							ok: { type: "boolean" },
							title: { type: "string", description: "Present when ok." },
							markdown: { type: "string", description: "Present when ok." },
							status: {
								type: "integer",
								description: "Per-path error status; present when not ok.",
							},
							detail: { type: "string", description: "Present when not ok." },
						},
						required: ["path", "ok"],
					},
				},
			},
			required: ["results"],
		},
		Problem: {
			type: "object",
			description: "RFC 9457 Problem Details.",
			properties: {
				type: { type: "string" },
				title: { type: "string" },
				status: { type: "integer" },
				detail: { type: "string" },
				instance: { type: "string" },
			},
			required: ["title", "status"],
		},
	},
	responses: {
		AskOk: {
			description: "Structured answer with matching documentation.",
			headers: {
				"Idempotency-Key": {
					description: "Echo of the request's Idempotency-Key, when sent.",
					schema: { type: "string" },
				},
				...RATE_LIMIT_HEADER_REFS,
			},
			content: {
				"application/json": {
					schema: { $ref: "#/components/schemas/AskResponse" },
				},
				"text/event-stream": {
					schema: {
						type: "string",
						description: "SSE stream of NLWeb events: start, result, complete.",
					},
				},
			},
		},
		Problem: {
			description:
				"Error using the RFC 9457 Problem Details shape, served as application/json.",
			content: {
				"application/json": {
					schema: { $ref: "#/components/schemas/Problem" },
				},
			},
		},
		TooManyRequests: {
			description:
				"Rate limit exceeded (RFC 9457 Problem Details body). Honor `Retry-After` before retrying.",
			headers: {
				"Retry-After": {
					description: "Seconds to wait before retrying.",
					schema: { type: "integer" },
				},
				...RATE_LIMIT_HEADER_REFS,
			},
			content: {
				"application/json": {
					schema: { $ref: "#/components/schemas/Problem" },
				},
			},
		},
	},
} as const;
