// Generated by OrchestKit Claude Plugin
// Created: 2026-06-10

/**
 * Unit tests for pretool/task/fable-spend-consent.
 *
 * Policy: spawning an agent pinned to Claude Fable 5 ($10/$50 per MTok) is a
 * deliberate spend decision — explicit pins escalate to a user permission
 * prompt unless ORK_FABLE_OK=1 pre-consents. Also pins the dispatcher-level
 * guarantee that ask escalations propagate instead of being merged away.
 */

import { describe, test, expect, beforeEach, afterEach } from 'vitest';
import type { HookInput } from '../../../types.js';
import { fableSpendConsent } from '../../../pretool/task/fable-spend-consent.js';
import { syncTaskDispatcher } from '../../../pretool/task/sync-task-dispatcher.js';
import { NOOP_CTX } from '../../../lib/context.js';

function spawn(model?: string): HookInput {
  return {
    tool_name: 'Agent',
    session_id: 's-fable-consent',
    tool_input: model ? { subagent_type: 'general-purpose', description: 'task', model } : { subagent_type: 'general-purpose', description: 'task' },
  };
}

const savedEnv = { ...process.env };
beforeEach(() => {
  delete process.env.ORK_FABLE_OK;
});
afterEach(() => {
  process.env = { ...savedEnv };
});

describe('fableSpendConsent', () => {
  test('escalates short-name fable pin to a permission ask', () => {
    const r = fableSpendConsent(spawn('fable'), NOOP_CTX);
    expect(r.continue).toBe(true);
    expect(r.hookSpecificOutput?.permissionDecision).toBe('ask');
    expect(r.hookSpecificOutput?.permissionDecisionReason).toContain('$10/$50');
    expect(r.hookSpecificOutput?.permissionDecisionReason).toContain('ORK_FABLE_OK=1');
  });

  test('escalates full-ID pin (claude-fable-5)', () => {
    const r = fableSpendConsent(spawn('claude-fable-5'), NOOP_CTX);
    expect(r.hookSpecificOutput?.permissionDecision).toBe('ask');
  });

  test('escalates the 1M-context variant (claude-fable-5[1m])', () => {
    const r = fableSpendConsent(spawn('claude-fable-5[1m]'), NOOP_CTX);
    expect(r.hookSpecificOutput?.permissionDecision).toBe('ask');
  });

  test('silent when ORK_FABLE_OK=1 pre-consents', () => {
    process.env.ORK_FABLE_OK = '1';
    const r = fableSpendConsent(spawn('fable'), NOOP_CTX);
    expect(r.continue).toBe(true);
    expect(r.hookSpecificOutput?.permissionDecision).toBeUndefined();
  });

  test('silent for non-fable pins (sonnet/opus/haiku)', () => {
    for (const m of ['sonnet', 'opus', 'haiku', 'claude-opus-4-8']) {
      const r = fableSpendConsent(spawn(m), NOOP_CTX);
      expect(r.hookSpecificOutput?.permissionDecision, m).toBeUndefined();
    }
  });

  test('silent when no model is pinned (inherit follows the session)', () => {
    const r = fableSpendConsent(spawn(), NOOP_CTX);
    expect(r.continue).toBe(true);
    expect(r.hookSpecificOutput?.permissionDecision).toBeUndefined();
  });
});

describe('syncTaskDispatcher ask propagation', () => {
  test('the fable ask escalation survives the dispatcher (not merged away)', () => {
    const r = syncTaskDispatcher(spawn('fable'), NOOP_CTX);
    expect(r.continue).toBe(true);
    expect(r.hookSpecificOutput?.permissionDecision).toBe('ask');
    expect(r.hookSpecificOutput?.permissionDecisionReason).toContain('Fable');
  });

  test('non-fable spawns still flow through the dispatcher normally', () => {
    process.env.ORK_FABLE_OK = '1';
    const r = syncTaskDispatcher(spawn('fable'), NOOP_CTX);
    expect(r.hookSpecificOutput?.permissionDecision).toBeUndefined();
  });
});
