// Generated by OrchestKit Claude Plugin
// Created: 2026-06-07

import { type DocHit, searchDocs } from "@/lib/doc-search";
import { problemResponse } from "@/lib/problem";

// NLWeb /ask endpoint (rewritten from /ask in next.config.mjs). Accepts a
// natural-language query and returns matching documentation as JSON with a
// `_meta` block. With `Accept: text/event-stream` (or `prefer.streaming: true`)
// it streams NLWeb events: start, result, complete.
// Spec: https://github.com/microsoft/NLWeb
export const dynamic = "force-dynamic";

const NLWEB_VERSION = "0.1";

function jsonResponse(query: string, hits: DocHit[]): Response {
	return Response.json({
		query,
		results: hits,
		_meta: {
			response_type: "docs",
			version: NLWEB_VERSION,
			count: hits.length,
		},
	});
}

function sseResponse(query: string, hits: DocHit[]): Response {
	const encoder = new TextEncoder();
	const event = (type: string, data: unknown) =>
		encoder.encode(`event: ${type}\ndata: ${JSON.stringify(data)}\n\n`);

	const stream = new ReadableStream({
		start(controller) {
			controller.enqueue(
				event("start", { query, _meta: { response_type: "docs", version: NLWEB_VERSION } }),
			);
			for (const hit of hits) {
				controller.enqueue(event("result", hit));
			}
			controller.enqueue(event("complete", { count: hits.length }));
			controller.close();
		},
	});

	return new Response(stream, {
		headers: {
			"Content-Type": "text/event-stream; charset=utf-8",
			"Cache-Control": "no-cache",
			Connection: "keep-alive",
		},
	});
}

async function readQuery(req: Request): Promise<{ query: string; streaming: boolean } | null> {
	const accept = req.headers.get("accept") ?? "";
	let streaming = accept.includes("text/event-stream");

	if (req.method === "GET") {
		const q = new URL(req.url).searchParams.get("query") ?? "";
		return { query: q, streaming };
	}

	try {
		const body = (await req.json()) as {
			query?: string;
			prefer?: { streaming?: boolean };
		};
		if (body?.prefer?.streaming) streaming = true;
		return { query: body?.query ?? "", streaming };
	} catch {
		return null;
	}
}

async function handle(req: Request): Promise<Response> {
	const parsed = await readQuery(req);
	if (!parsed) {
		return problemResponse({
			title: "Invalid request body",
			status: 400,
			detail: "Expected a JSON body of the form { \"query\": \"...\" }.",
		});
	}

	const query = parsed.query.trim();
	if (!query) {
		return problemResponse({
			title: "Missing query",
			status: 400,
			detail: "Provide a non-empty `query` (in the JSON body or as a ?query= parameter).",
		});
	}

	const hits = searchDocs(query);
	return parsed.streaming ? sseResponse(query, hits) : jsonResponse(query, hits);
}

export async function POST(req: Request) {
	return handle(req);
}

export async function GET(req: Request) {
	return handle(req);
}
