// Generated by OrchestKit Claude Plugin
// Created: 2026-03-31

/**
 * Unit tests for denial-notification PermissionDenied hook
 * Tests sliding-window threshold and cooldown for desktop notifications
 */

import { describe, test, expect, vi, beforeEach, afterEach } from 'vitest';
import type { HookInput } from '../../types.js';

// Mock node:child_process
vi.mock('node:child_process', () => ({
  execFileSync: vi.fn(),
}));

// Mock node:os
vi.mock('node:os', () => ({
  platform: vi.fn().mockReturnValue('darwin'),
}));

// Mock the common module
vi.mock('../../lib/common.js', async () => {
  const actual = await vi.importActual<typeof import('../../lib/common.js')>('../../lib/common.js');
  return {
    ...actual,
    logHook: vi.fn(),
    outputSilentSuccess: () => ({ continue: true, suppressOutput: true }),
  };
});

import { execFileSync } from 'node:child_process';

/**
 * Create a mock HookInput for a denied tool call
 */
function createDeniedInput(toolName = 'Bash'): HookInput {
  return {
    tool_name: toolName,
    session_id: 'test-session-789',
    tool_input: { command: 'some command' },
    project_dir: '/test/project',
    hook_event: 'PermissionDenied',
  };
}

describe('denial-notification', () => {
  let denialNotification: typeof import('../../permission-denied/denial-notification.js').denialNotification;

  beforeEach(async () => {
    vi.clearAllMocks();
    vi.useFakeTimers();

    // Re-import to reset module-level state (denialTimestamps, lastNotifiedAt)
    vi.resetModules();
    const mod = await import('../../permission-denied/denial-notification.js');
    denialNotification = mod.denialNotification;
  });

  afterEach(() => {
    vi.useRealTimers();
  });

  describe('No notification under threshold (1-2 denials)', () => {
    test('first denial does not trigger notification', () => {
      // Arrange
      const input = createDeniedInput();

      // Act
      const result = denialNotification(input);

      // Assert
      expect(execFileSync).not.toHaveBeenCalled();
      expect(result.continue).toBe(true);
      expect(result.suppressOutput).toBe(true);
    });

    test('second denial does not trigger notification', () => {
      // Arrange
      const input = createDeniedInput();

      // Act
      denialNotification(input);
      const result = denialNotification(input);

      // Assert
      expect(execFileSync).not.toHaveBeenCalled();
      expect(result.continue).toBe(true);
    });
  });

  describe('Notification fires at 3+ denials in 60s', () => {
    test('third denial triggers notification', () => {
      // Arrange
      const input = createDeniedInput();

      // Act — 3 denials in rapid succession
      denialNotification(input);
      denialNotification(input);
      const result = denialNotification(input);

      // Assert
      expect(execFileSync).toHaveBeenCalledTimes(1);
      expect(execFileSync).toHaveBeenCalledWith(
        'osascript',
        expect.arrayContaining(['-e', expect.stringContaining('display notification')]),
        expect.objectContaining({ timeout: 3000 })
      );
      expect(result.continue).toBe(true);
    });

    test('notification includes tool name', () => {
      // Arrange
      const input = createDeniedInput('Write');

      // Act
      denialNotification(input);
      denialNotification(input);
      denialNotification(input);

      // Assert
      const osascriptArg = vi.mocked(execFileSync).mock.calls[0][1]![1] as string;
      expect(osascriptArg).toContain('Write');
    });

    test('denials outside 60s window do not count', () => {
      // Arrange
      const input = createDeniedInput();

      // Act — 2 denials, then wait 61s, then 1 more denial
      denialNotification(input);
      denialNotification(input);
      vi.advanceTimersByTime(61_000);
      denialNotification(input);

      // Assert — only 1 denial in window, so no notification
      expect(execFileSync).not.toHaveBeenCalled();
    });

    test('4th denial still sends notification (above threshold)', () => {
      // Arrange
      const input = createDeniedInput();

      // Act
      denialNotification(input);
      denialNotification(input);
      denialNotification(input); // fires notification
      vi.mocked(execFileSync).mockClear();

      // Advance past cooldown
      vi.advanceTimersByTime(121_000);
      denialNotification(input);
      denialNotification(input);
      denialNotification(input);
      denialNotification(input); // fires notification again

      // Assert — should fire again after cooldown
      expect(execFileSync).toHaveBeenCalled();
    });
  });

  describe('Cooldown prevents spam (2 min cooldown)', () => {
    test('suppresses notification during cooldown period', () => {
      // Arrange
      const input = createDeniedInput();

      // Act — trigger first notification
      denialNotification(input);
      denialNotification(input);
      denialNotification(input); // fires
      vi.mocked(execFileSync).mockClear();

      // 4th and 5th denial within cooldown
      denialNotification(input);
      denialNotification(input);

      // Assert — no additional notification (within 2min cooldown)
      expect(execFileSync).not.toHaveBeenCalled();
    });

    test('allows notification after cooldown expires', () => {
      // Arrange
      const input = createDeniedInput();

      // Act — first batch triggers notification
      denialNotification(input);
      denialNotification(input);
      denialNotification(input);
      vi.mocked(execFileSync).mockClear();

      // Wait past cooldown (2min = 120s)
      vi.advanceTimersByTime(121_000);

      // New batch of denials
      denialNotification(input);
      denialNotification(input);
      denialNotification(input);

      // Assert
      expect(execFileSync).toHaveBeenCalledTimes(1);
    });
  });

  describe('Always returns silent success (never retry)', () => {
    test('never returns retry regardless of denial count', () => {
      // Arrange
      const input = createDeniedInput();

      // Act
      const results: ReturnType<typeof denialNotification>[] = [];
      for (let i = 0; i < 5; i++) {
        results.push(denialNotification(input));
      }

      // Assert
      for (const result of results) {
        expect(result.continue).toBe(true);
        expect(result.suppressOutput).toBe(true);
        expect(result.hookSpecificOutput?.retry).toBeUndefined();
      }
    });
  });

  describe('Error handling', () => {
    test('gracefully handles osascript failure', () => {
      // Arrange
      vi.mocked(execFileSync).mockImplementation(() => {
        throw new Error('osascript not found');
      });
      const input = createDeniedInput();

      // Act — should not throw even when notification fails
      denialNotification(input);
      denialNotification(input);
      const result = denialNotification(input);

      // Assert
      expect(result.continue).toBe(true);
      expect(result.suppressOutput).toBe(true);
    });
  });
});
