// Generated by OrchestKit Claude Plugin
// Created: 2026-09-25

/**
 * secrets-veil must never return a tool result unmasked, even when the mod
 * never saw session.start (enabled or hot-reloaded mid-session). This file
 * runs in its own module instance (vitest isolates per file), so `table`
 * starts null exactly as it does in that window. Each test registers fresh
 * hooks but shares the module, so the no-session case runs first.
 */

import { describe, test, expect } from "vitest";
import { register } from "../hooks/register.js";

type RegisteredHook = (...args: unknown[]) => unknown;

// A fake GitHub token shape, assembled at runtime so no token-shaped literal
// sits in the source: the ghp_ prefix plus 36 filler characters.
const FAKE_GH = "gh" + "p_" + "Zq8Lm3Rt7Vx2Kp9Nw4Hy6Bc1Df5Gj0Sa8Ue3";

/** Synthetic named value: no vendor shape, low entropy, so only the named path masks it. */
const SYNTHETIC = "veiltest-synthetic-value-42";

function hooksOf(): Map<string, RegisteredHook> {
  const hooks = new Map<string, RegisteredHook>();
  register((event: string, hook: unknown) => {
    hooks.set(event, hook as RegisteredHook);
  }, {});
  return hooks;
}

function fake$(env: Record<string, string> | "throws"): unknown {
  return {
    env: {
      get: async (name: string): Promise<string | undefined> => {
        if (env === "throws") throw new Error(`env.get(${name}) refused`);
        return env[name];
      },
    },
    ui: {
      notice: async (): Promise<void> => undefined,
      toast: async (): Promise<void> => undefined,
      status: async (): Promise<void> => undefined,
      log: async (): Promise<void> => undefined,
    },
  };
}

const next = (result: unknown) => async (): Promise<unknown> => result;

describe("fail closed when session.start never ran", () => {
  test("a planted ghp_ token and a named value come out masked with no session.start", async () => {
    const hooks = hooksOf();
    const out = await hooks.get("tool.call")!(
      fake$({ GITHUB_TOKEN: SYNTHETIC }),
      { tool: "Bash", args: {} },
      next({ result: { stdout: `FAKE_TOKEN=${FAKE_GH}\nNAMED=${SYNTHETIC}\n` } })
    );
    const text = JSON.stringify(out);
    expect(text).not.toContain(FAKE_GH);
    // The lazy arm read the named variables too, not only the shapes.
    expect(text).not.toContain(SYNTHETIC);
    expect(text).toContain("•".repeat(8));
  });
});

describe("fail closed when masking itself throws", () => {
  test("a result that cannot be walked is withheld with deny, never passed through", async () => {
    const hooks = hooksOf();
    const hostile = {
      get stdout(): string {
        throw new Error("unreadable field");
      },
    };
    const out = (await hooks.get("tool.call")!(fake$({}), { tool: "Bash", args: {} }, next({ result: hostile }))) as {
      deny?: string;
      result?: unknown;
    };
    expect(out.result).toBeUndefined();
    expect(out.deny).toContain("withheld rather than shown unmasked");
  });
});
