#!/usr/bin/env bash
# Generated by OrchestKit Claude Plugin
# Created: 2026-08-04

# find-living-plan.sh — Locate an existing living plan by SLUG, not by path.
#
# Why this exists: the living-plan contract is "one plan = one file", but detection
# used to key on docs/<branch-dir>/plan-viz.html. The path is derived from the branch
# name, so a branch rename moved the path, the check missed, and the plan forked into
# a second file. Confirmed in the wild: slug "langchain-ecosystem-currency" shipped
# twice (docs/chore--… and docs/research--…) with the same updated date.
#
# The slug is the identity. The path is an address that can change.
#
# Usage:  bash find-living-plan.sh <slug> [search-root]
# Output: one matching path per line (stdout).
# Exit:   0 = exactly one match (UPDATE that file)
#         1 = no match          (AUTHOR a new one)
#         2 = multiple matches  (FORKED — stop and reconcile, do not write a third)
#         3 = usage error

set -euo pipefail

SLUG="${1:-}"
ROOT="${2:-docs}"

if [[ -z "$SLUG" ]]; then
    echo "usage: find-living-plan.sh <slug> [search-root]" >&2
    exit 3
fi

# No docs/ dir at all — nothing can exist yet, so this is an AUTHOR case.
[[ -d "$ROOT" ]] || exit 1

read_slug() {
    python3 - "$1" <<'PY'
import json, re, sys
try:
    text = open(sys.argv[1], encoding="utf-8", errors="replace").read()
except OSError as exc:
    print("unreadable: %s" % exc, file=sys.stderr)
    sys.exit(0)
m = re.search(r'id="lpp-state"[^>]*>(.*?)</script>', text, re.S)
if not m:
    sys.exit(0)
try:
    print(json.loads(m.group(1)).get("slug", ""))
except ValueError as exc:
    # A malformed island is worth SAYING out loud — it is exactly how a plan goes
    # missing from lookup and then gets silently forked into a second file.
    print("malformed lpp-state in %s: %s" % (sys.argv[1], exc), file=sys.stderr)
    sys.exit(0)
PY
}

# Candidates: any HTML carrying a state island. grep's exit 1 means "no candidates",
# which is a legitimate AUTHOR case; exit >=2 is a real error and must not be hidden.
candidates=""
grep_rc=0
candidates="$(grep -rl 'id="lpp-state"' "$ROOT" --include='*.html')" || grep_rc=$?
if (( grep_rc > 1 )); then
    echo "find-living-plan: grep failed (exit $grep_rc) scanning '$ROOT'" >&2
    exit 3
fi

matches=()
while IFS= read -r f; do
    [[ -n "$f" ]] || continue
    # docs/site/ is the generated documentation site — its code samples are not real plans.
    case "$f" in */site/*) continue ;; esac
    if [[ "$(read_slug "$f")" == "$SLUG" ]]; then
        matches+=("$f")
    fi
done <<< "$candidates"

case "${#matches[@]}" in
    0) exit 1 ;;
    1) printf '%s\n' "${matches[0]}"; exit 0 ;;
    *)
        printf '%s\n' "${matches[@]}" | sort
        echo "FORKED: ${#matches[@]} files share slug '$SLUG' — reconcile before writing." >&2
        exit 2
        ;;
esac
