// Generated by OrchestKit Claude Plugin
// Created: 2026-07-22

// did:web DID document — served at /.well-known/did.json via a rewrite in
// next.config.mjs. Resolves the host identity did:web:orchestkit.yonyon.ai that
// the ARD catalog (/.well-known/ai-catalog.json) and its trustManifest claim,
// so an agent can dereference the DID instead of trusting a bare string.
//
// The verification method is the SAME Ed25519 key already published in the
// RFC 9421 key directory (/.well-known/http-message-signatures-directory) — one
// key, two spec shapes, kept in sync by did.test.ts. Honest scope: this docs
// origin is anonymous read-only and signs nothing today, so the key is a valid,
// unused verification key (an identity anchor, not a load-bearing credential).
// The matching private key is held out-of-band, never committed; rotate by
// regenerating the pair and swapping `x` + `kid` in both routes together.
export const revalidate = false;

const DID = "did:web:orchestkit.yonyon.ai";
// Mirror of the JWK in http-message-signatures-directory/route.ts (kid must match).
const KID = "6a120f4f14168a35";
const VERIFICATION_METHOD_ID = `${DID}#${KID}`;

export function GET() {
	const doc = {
		"@context": [
			"https://www.w3.org/ns/did/v1",
			"https://w3id.org/security/suites/jws-2020/v1",
		],
		id: DID,
		verificationMethod: [
			{
				id: VERIFICATION_METHOD_ID,
				type: "JsonWebKey2020",
				controller: DID,
				publicKeyJwk: {
					kty: "OKP",
					crv: "Ed25519",
					x: "z5ufUBtSG2s-PEH_Sx2DYttadlsrQts4vAfLj2I2vUA",
					kid: KID,
					alg: "EdDSA",
					use: "sig",
				},
			},
		],
		// The same key both authenticates the DID and signs assertions about it.
		authentication: [VERIFICATION_METHOD_ID],
		assertionMethod: [VERIFICATION_METHOD_ID],
	};

	return new Response(JSON.stringify(doc, null, 2), {
		headers: {
			"Content-Type": "application/did+json; charset=utf-8",
			"Cache-Control": "public, max-age=3600, s-maxage=86400",
		},
	});
}
