// Generated by OrchestKit Claude Plugin
// Created: 2026-04-01

/**
 * CwdChanged Hook — Reload project context on directory change
 *
 * CC 2.1.83: Fires when working directory changes. Returns updated
 * watchPaths list and injects refreshed project context.
 *
 * @hook CwdChanged
 * @since CC 2.1.83
 * @see #1229
 */

import type { HookInput, HookResult } from '../types.js';
import { outputSilentSuccess, logHook } from '../lib/common.js';
import { existsSync } from 'node:fs';
import { join } from 'node:path';

const HOOK_NAME = 'cwd-changed';

/** Files to watch for changes in the new directory */
function getWatchPaths(projectDir: string): string[] {
  const candidates = [
    '.claude/rules',
    'CLAUDE.md',
    'package.json',
    '.env',
    '.claude/settings.json',
  ];
  return candidates
    .map(f => join(projectDir, f))
    .filter(p => existsSync(p));
}

export function cwdChanged(input: HookInput): HookResult {
  const oldCwd = input.old_cwd || '';
  const newCwd = input.new_cwd || '';

  if (!newCwd) {
    return outputSilentSuccess();
  }

  logHook(HOOK_NAME, `Directory changed: ${oldCwd} → ${newCwd}`);

  const watchPaths = getWatchPaths(newCwd);

  // Detect project type from new directory
  const signals: string[] = [];
  if (existsSync(join(newCwd, 'package.json'))) signals.push('Node.js');
  if (existsSync(join(newCwd, 'pyproject.toml')) || existsSync(join(newCwd, 'requirements.txt'))) signals.push('Python');
  if (existsSync(join(newCwd, 'go.mod'))) signals.push('Go');
  if (existsSync(join(newCwd, 'Cargo.toml'))) signals.push('Rust');
  if (existsSync(join(newCwd, 'Gemfile'))) signals.push('Ruby');
  if (existsSync(join(newCwd, 'terraform'))) signals.push('Terraform');

  const techStack = signals.length > 0 ? signals.join(', ') : 'unknown';

  return {
    continue: true,
    suppressOutput: true,
    hookSpecificOutput: {
      additionalContext: `[CwdChanged] New directory: ${newCwd} | Stack: ${techStack}`,
      watchPaths,
    },
  } as HookResult;
}
