// Generated by OrchestKit Claude Plugin
// Created: 2026-08-29

/**
 * Model Switch Telemetry — PostModelSwitch hook (CC 2.1.251, #3789)
 *
 * Observer only. Appends one line per session model change to
 * ~/.claude/analytics/model-switch.jsonl so ork:analytics can answer "how often
 * do sessions move tiers, from where, and what did the re-cache cost", which
 * until 2.1.251 was not observable from a plugin at all.
 *
 * Never writes to stdout context: PostModelSwitch exit-0 stdout is shown to
 * Claude on the next request, and a telemetry hook has nothing to say there.
 * Registered async so it never sits on the switch's critical path.
 *
 * Payload contract measured on 2.1.251 (2026-08-29), see lib/session-staleness.ts.
 *
 * @hook PostModelSwitch
 */

import type { HookInput, HookResult, HookContext } from '../types.js';
import { outputSilentSuccess } from '../lib/common.js';
import { appendAnalytics, hashProject } from '../lib/analytics.js';
import { NOOP_CTX } from '../lib/context.js';
import { isPremiumTierModel, readModelSwitch } from '../lib/session-staleness.js';

const HOOK_NAME = 'model-switch-telemetry';
export const MODEL_SWITCH_ANALYTICS_FILE = 'model-switch.jsonl';

export function modelSwitchTelemetry(input: HookInput, ctx: HookContext = NOOP_CTX): HookResult {
  const sw = readModelSwitch(input);
  if (!sw.toModel) {
    return outputSilentSuccess();
  }
  try {
    appendAnalytics(MODEL_SWITCH_ANALYTICS_FILE, {
      ts: new Date().toISOString(),
      pid: hashProject(input.project_dir || ctx.projectDir || process.env.CLAUDE_PROJECT_DIR || ''),
      session_id: input.session_id ?? null,
      from_model: sw.fromModel || null,
      to_model: sw.toModel,
      requested_model: sw.requestedModel,
      source: sw.source || null,
      context_tokens: sw.contextTokens,
      prompt_cache_warm: sw.promptCacheWarm,
      cache_ttl: sw.cacheTtl || null,
      estimated_cache_write_usd: sw.estimatedCacheWriteUsd,
      pricing: sw.pricing || null,
      to_premium_tier: isPremiumTierModel(sw.toModel),
    });
    ctx.log(HOOK_NAME, `recorded ${sw.fromModel || '?'} -> ${sw.toModel} (source=${sw.source || '?'})`);
  } catch (err) {
    ctx.log(HOOK_NAME, `failed to record model switch: ${err instanceof Error ? err.message : String(err)}`, 'warn');
  }
  return outputSilentSuccess();
}
