// Generated by OrchestKit Claude Plugin
// Created: 2026-04-02

/**
 * Universal Webhook Forwarder — streams ALL hook events to registered sinks.
 *
 * Registered for every CC event type in hooks.json (async: true).
 * Delegates to telemetry.emit() which fans out to pluggable sinks
 * (JSONL local + HTTP remote). No-op when no sinks are active.
 *
 * This function is the PUBLIC API — all dispatchers import it.
 * The emit() machinery is internal plumbing.
 *
 * Auth: HMAC-SHA256 signature in X-CC-Hooks-Signature header.
 * The receiving API verifies the signature to ensure payload integrity.
 *
 * #1259: Simplified to thin wrapper around telemetry.emit().
 */

import type { HookInput, HookResult } from '../types.js';
import { outputSilentSuccess } from '../lib/common.js';
import { getWebhookUrl } from '../lib/orchestration-state.js';
import { emit, registerSink } from '../lib/telemetry.js';
import { JsonlSink } from '../lib/jsonl-sink.js';
import { HttpSink } from '../lib/http-sink.js';

// ---------------------------------------------------------------------------
// Module-scope sink registration (runs once per process on import)
// Each CC hook = separate Node.js process, so this is deterministic.
// ---------------------------------------------------------------------------
// Always register JSONL sink — never-lose-data safety net (local backup)
registerSink(new JsonlSink());

// Conditionally register HTTP sink (requires remote API configuration)
const hookUrl = getWebhookUrl();
const hookToken = process.env.ORCHESTKIT_HOOK_TOKEN;
if (hookUrl && hookToken) {
  registerSink(new HttpSink());
}

// ---------------------------------------------------------------------------
// Public API (unchanged signature — dispatchers don't need updates)
// ---------------------------------------------------------------------------

export async function webhookForwarder(input: HookInput): Promise<HookResult> {
  emit(input);
  return outputSilentSuccess();
}
