// Generated by OrchestKit Claude Plugin
// Created: 2026-03-02

/**
 * Unit tests for config-change/settings-reload hook
 *
 * Tests that settings-reload emits an advisory prompt context message
 * when settings change mid-session, and logs the event.
 *
 * CC 2.1.50+: ConfigChange fires automatically when config files are modified.
 */

import { describe, it, expect, vi, beforeEach } from 'vitest';
import type { HookInput } from '../../types.js';

// ---------------------------------------------------------------------------
// Mocks
// ---------------------------------------------------------------------------

vi.mock('../../lib/common.js', async () => {
  const actual = await vi.importActual<typeof import('../../lib/common.js')>('../../lib/common.js');
  return {
    ...actual,
    logHook: vi.fn(),
    outputPromptContext: vi.fn((msg: string) => ({
      continue: true,
      suppressOutput: true,
      hookSpecificOutput: { additionalContext: msg, hookEventName: 'ConfigChange' },
    })),
  };
});

import { settingsReload } from '../../config-change/settings-reload.js';
import { logHook, outputPromptContext } from '../../lib/common.js';

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function createConfigChangeInput(overrides: Partial<HookInput> = {}): HookInput {
  return {
    hook_event: 'ConfigChange',
    tool_name: '',
    session_id: 'test-session-456',
    tool_input: {},
    ...overrides,
  };
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

describe('config-change/settings-reload', () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  // -------------------------------------------------------------------------
  // Core behavior
  // -------------------------------------------------------------------------

  describe('core behavior', () => {
    it('returns a result with continue: true', () => {
      const input = createConfigChangeInput();
      const result = settingsReload(input);

      expect(result.continue).toBe(true);
    });

    it('calls outputPromptContext (not outputSilentSuccess)', () => {
      const input = createConfigChangeInput();
      settingsReload(input);

      expect(outputPromptContext).toHaveBeenCalled();
    });

    it('context message mentions [ConfigChange]', () => {
      const input = createConfigChangeInput();
      settingsReload(input);

      const msg = vi.mocked(outputPromptContext).mock.calls[0][0];
      expect(msg).toContain('[ConfigChange]');
    });

    it('context message mentions permissions', () => {
      const input = createConfigChangeInput();
      settingsReload(input);

      const msg = vi.mocked(outputPromptContext).mock.calls[0][0];
      expect(msg.toLowerCase()).toContain('permission');
    });

    it('context message mentions settings were modified', () => {
      const input = createConfigChangeInput();
      settingsReload(input);

      const msg = vi.mocked(outputPromptContext).mock.calls[0][0];
      expect(msg).toContain('modified');
    });

    it('context message mentions immediate effect', () => {
      const input = createConfigChangeInput();
      settingsReload(input);

      const msg = vi.mocked(outputPromptContext).mock.calls[0][0];
      expect(msg).toContain('immediately');
    });
  });

  // -------------------------------------------------------------------------
  // Logging
  // -------------------------------------------------------------------------

  describe('logging', () => {
    it('logs with hook name "config-change"', () => {
      const input = createConfigChangeInput({ session_id: 'abc-123' });
      settingsReload(input);

      expect(logHook).toHaveBeenCalledWith(
        'config-change',
        expect.stringContaining('abc-123'),
      );
    });

    it('includes session_id in log message', () => {
      const input = createConfigChangeInput({ session_id: 'sess-xyz' });
      settingsReload(input);

      expect(logHook).toHaveBeenCalledWith(
        'config-change',
        expect.stringContaining('sess-xyz'),
      );
    });

    it('uses "unknown" when session_id is absent', () => {
      const input = createConfigChangeInput({ session_id: undefined });
      settingsReload(input);

      expect(logHook).toHaveBeenCalledWith(
        'config-change',
        expect.stringContaining('unknown'),
      );
    });
  });

  // -------------------------------------------------------------------------
  // Edge cases
  // -------------------------------------------------------------------------

  describe('edge cases', () => {
    it('handles empty tool_input gracefully', () => {
      const input = createConfigChangeInput({ tool_input: {} });
      expect(() => settingsReload(input)).not.toThrow();
    });

    it('works with minimal input (no session_id field)', () => {
      const input: HookInput = {
        hook_event: 'ConfigChange',
        tool_name: '',
        tool_input: {},
      };
      expect(() => settingsReload(input)).not.toThrow();
    });

    it('always returns a result (never throws)', () => {
      const inputs: HookInput[] = [
        createConfigChangeInput(),
        createConfigChangeInput({ session_id: undefined }),
        { hook_event: 'ConfigChange', tool_name: '', tool_input: {} },
      ];

      for (const input of inputs) {
        const result = settingsReload(input);
        expect(result).toBeDefined();
        expect(result.continue).toBe(true);
      }
    });
  });
});
