// Generated by OrchestKit Claude Plugin
// Created: 2026-05-20

/**
 * Session Heartbeat Publisher — PostToolUse[Bash] hook (#1885).
 *
 * Detects structural git/gh operations in the Bash command + output and
 * publishes a distilled JSON state file to
 *   ~/.claude/state/orchestkit/<repo>/<session-id>.json
 *
 * Other sessions read that file directly to know what THIS session is
 * doing. See docs/parallel-primitives.md for the cross-session model.
 *
 * Never blocks. Best-effort writes. No-op on non-structural commands.
 *
 * Structural events recognised:
 *   • git commit ...                → last_commit
 *   • git push ...                  → last_push
 *   • gh pr create | merge | ready  → last_pr
 *
 * The publisher does NOT parse exit codes; CC's command output is the
 * source of truth. If the command failed, the output will lack the
 * structural markers and the heartbeat just bumps timestamp + status.
 */

import type { HookInput, HookResult, HookContext } from '../../types.js';
import { outputSilentSuccess } from '../../lib/common.js';
import { getProjectDir } from '../../lib/paths.js';
import { NOOP_CTX } from '../../lib/context.js';
import {
  type SessionState,
  type CommitRef,
  type PushRef,
  type PrRef,
  getStateFilePath,
  readSessionState,
  writeSessionStateAtomic,
  mergeSessionState,
  repoSlugFromCwd,
} from '../../lib/session-state.js';

const HOOK_NAME = 'session-heartbeat-publisher';

const RE_GIT_COMMIT = /^\s*git\s+(?:-C\s+\S+\s+)?commit\b/;
const RE_GIT_PUSH = /^\s*git\s+(?:-C\s+\S+\s+)?push\b/;
const RE_GH_PR = /^\s*gh\s+pr\s+(create|merge|ready|review|edit)\b/;

/** Pull a short-sha + first-line message out of `git commit` stdout. */
export function parseCommitFromOutput(output: string): CommitRef | null {
  // git commit prints something like:
  //   [main 5c9a906e] feat(api): canonical seed-data migration
  // OR with no branch:
  //   [detached HEAD 5c9a906e] message…
  const match = output.match(/\[[^\]]*\b([0-9a-f]{7,40})\]\s*(.+?)$/m);
  if (!match) return null;
  return { sha: match[1], msg: match[2].trim() };
}

/** Pull `<branch> -> <branch>` out of `git push` stderr. */
export function parsePushFromCommandAndOutput(
  command: string,
  output: string,
): PushRef | null {
  // git push lines we can parse:
  //   "   abc1234..def5678  feat/x -> feat/x"
  //   "+ abc1234...def5678  feat/x -> feat/x  (forced update)"
  //   " * [new branch]      feat/x -> feat/x"
  const updateMatch = output.match(/^\s*[+*\s]*(?:\[new branch\]\s+)?([0-9a-f]+(?:\.\.+[0-9a-f]+)?\s+)?(\S+)\s*->\s*(\S+)\s*(?:\(.*\))?\s*$/m);
  if (updateMatch) {
    const branch = updateMatch[3] || updateMatch[2];
    const ref = updateMatch[1]?.split(/\.+/).pop()?.trim() || branch;
    return { branch, ref };
  }
  // Fallback: scrape `git push origin <branch>` from the command itself.
  const cmdMatch = command.match(/git\s+(?:-C\s+\S+\s+)?push\s+(?:-\S+\s+)*(\S+)?\s*(\S+)?/);
  if (cmdMatch?.[2]) {
    return { branch: cmdMatch[2], ref: cmdMatch[2] };
  }
  return null;
}

/** Pull a PR url+number out of `gh pr create` / `gh pr merge` output. */
export function parsePrFromOutput(
  command: string,
  output: string,
): PrRef | null {
  // gh pr create prints "https://github.com/<owner>/<repo>/pull/1234"
  const urlMatch = output.match(/https:\/\/github\.com\/[^/]+\/[^/]+\/pull\/(\d+)/);
  if (!urlMatch) return null;
  const number = Number(urlMatch[1]);
  if (!Number.isFinite(number)) return null;

  const state: PrRef['state'] = (() => {
    if (/\bmerged\b/i.test(output)) return 'merged';
    if (/\bclosed\b/i.test(output)) return 'closed';
    if (/\bdraft\b/i.test(output) || /-d\b|--draft\b/.test(command)) return 'draft';
    return 'open';
  })();

  return { number, url: urlMatch[0], state };
}

/** What kind of structural event the command matches, if any. */
type EventKind = 'commit' | 'push' | 'pr' | null;

export function classifyCommand(command: string): EventKind {
  if (RE_GIT_COMMIT.test(command)) return 'commit';
  if (RE_GIT_PUSH.test(command)) return 'push';
  if (RE_GH_PR.test(command)) return 'pr';
  return null;
}

export function sessionHeartbeatPublisher(
  input: HookInput,
  ctx: HookContext = NOOP_CTX,
): HookResult {
  if (input.tool_name !== 'Bash') return outputSilentSuccess();

  const toolInput = input.tool_input as { command?: unknown } | undefined;
  const command = typeof toolInput?.command === 'string' ? toolInput.command : '';
  if (!command) return outputSilentSuccess();

  const kind = classifyCommand(command);
  if (!kind) return outputSilentSuccess();

  const cwd = getProjectDir();
  if (!cwd) return outputSilentSuccess();

  const repo = repoSlugFromCwd(cwd);
  const sessionId = input.session_id;
  if (!sessionId) return outputSilentSuccess();

  // tool_output may be a string or a structured object. We coerce both
  // to string for regex scanning.
  const output = (() => {
    const out = input.tool_output;
    if (typeof out === 'string') return out;
    if (out && typeof out === 'object') {
      try {
        return JSON.stringify(out);
      } catch {
        return '';
      }
    }
    return '';
  })();

  const path = getStateFilePath(repo, sessionId);
  const existing = readSessionState(path);

  const update: Partial<SessionState> = {};
  if (kind === 'commit') {
    const c = parseCommitFromOutput(output);
    if (c) update.last_commit = c;
  } else if (kind === 'push') {
    const p = parsePushFromCommandAndOutput(command, output);
    if (p) update.last_push = p;
  } else if (kind === 'pr') {
    const pr = parsePrFromOutput(command, output);
    if (pr) update.last_pr = pr;
  }

  const next = mergeSessionState(existing, update, repo, sessionId);
  const wrote = writeSessionStateAtomic(path, next);
  if (wrote) {
    ctx.log(HOOK_NAME, `Published ${kind} heartbeat for ${repo}/${sessionId}`, 'debug');
  } else {
    ctx.log(HOOK_NAME, `Failed to write heartbeat for ${repo}/${sessionId}`, 'warn');
  }

  return outputSilentSuccess();
}

export default sessionHeartbeatPublisher;
