// Generated by OrchestKit Claude Plugin
// Created: 2026-03-08

/**
 * Unit tests for instructions-loaded-dispatcher.ts
 * Main dispatcher: wires 6 handlers, merges additionalContext
 */

import { describe, test, expect, vi, beforeEach } from 'vitest';
import type { HookInput } from '../../types.js';

// Mock all 6 handlers so dispatcher logic is tested in isolation
const mockTokenBudget = vi.fn();
const mockPriorityMap = vi.fn();
const mockDriftDetection = vi.fn();
const mockContentDedup = vi.fn();
const mockRuleConflicts = vi.fn();
const mockSmartSuggestions = vi.fn();

vi.mock('../../instructions-loaded/token-budget-tracker.js', () => ({
  tokenBudgetTracker: (...args: unknown[]) => mockTokenBudget(...args),
}));
vi.mock('../../instructions-loaded/priority-map.js', () => ({
  priorityMap: (...args: unknown[]) => mockPriorityMap(...args),
}));
vi.mock('../../instructions-loaded/drift-detection.js', () => ({
  driftDetection: (...args: unknown[]) => mockDriftDetection(...args),
}));
vi.mock('../../instructions-loaded/content-dedup.js', () => ({
  contentDedupScanner: (...args: unknown[]) => mockContentDedup(...args),
}));
vi.mock('../../instructions-loaded/rule-conflicts.js', () => ({
  ruleConflictDetector: (...args: unknown[]) => mockRuleConflicts(...args),
}));
vi.mock('../../instructions-loaded/smart-suggestions.js', () => ({
  smartRuleSuggestions: (...args: unknown[]) => mockSmartSuggestions(...args),
}));

vi.mock('../../lib/common.js', () => ({
  logHook: vi.fn(),
  outputSilentSuccess: () => ({ continue: true, suppressOutput: true }),
  outputPromptContext: (ctx: string) =>
    ctx && ctx.trim()
      ? { continue: true, suppressOutput: true, hookSpecificOutput: { hookEventName: 'UserPromptSubmit', additionalContext: ctx } }
      : { continue: true, suppressOutput: true },
}));

import { instructionsLoadedDispatcher } from '../../instructions-loaded/instructions-loaded-dispatcher.js';

function makeInput(filesLoaded?: unknown): HookInput {
  return {
    tool_name: '',
    session_id: 'test-session',
    project_dir: '/test/project',
    tool_input: {},
    ...(filesLoaded !== undefined ? { files_loaded: filesLoaded } : {}),
  } as unknown as HookInput;
}

beforeEach(() => {
  vi.clearAllMocks();
  // Default: all handlers return null (silent)
  mockTokenBudget.mockReturnValue(null);
  mockPriorityMap.mockReturnValue(null);
  mockDriftDetection.mockReturnValue(null);
  mockContentDedup.mockReturnValue(null);
  mockRuleConflicts.mockReturnValue(null);
  mockSmartSuggestions.mockReturnValue(null);
});

describe('instructionsLoadedDispatcher', () => {
  describe('early exit — no files', () => {
    test('returns silent success when files_loaded is absent', () => {
      const result = instructionsLoadedDispatcher(makeInput(undefined));
      expect(result.continue).toBe(true);
      expect(result.suppressOutput).toBe(true);
    });

    test('returns silent success when files_loaded is an empty array', () => {
      const result = instructionsLoadedDispatcher(makeInput([]));
      expect(result.continue).toBe(true);
      expect(result.suppressOutput).toBe(true);
    });

    test('does not invoke any handler when files_loaded is empty', () => {
      instructionsLoadedDispatcher(makeInput([]));
      expect(mockTokenBudget).not.toHaveBeenCalled();
      expect(mockPriorityMap).not.toHaveBeenCalled();
    });
  });

  describe('all handlers silent', () => {
    test('returns silent success when all 6 handlers return null', () => {
      const input = makeInput([{ path: '/project/CLAUDE.md', byte_size: 1000 }]);
      const result = instructionsLoadedDispatcher(input);
      expect(result.continue).toBe(true);
      expect(result.suppressOutput).toBe(true);
    });

    test('calls all 6 handlers exactly once', () => {
      const input = makeInput([{ path: '/project/CLAUDE.md', byte_size: 500 }]);
      instructionsLoadedDispatcher(input);
      expect(mockTokenBudget).toHaveBeenCalledOnce();
      expect(mockPriorityMap).toHaveBeenCalledOnce();
      expect(mockDriftDetection).toHaveBeenCalledOnce();
      expect(mockContentDedup).toHaveBeenCalledOnce();
      expect(mockRuleConflicts).toHaveBeenCalledOnce();
      expect(mockSmartSuggestions).toHaveBeenCalledOnce();
    });

    test('passes the parsed files_loaded array to each handler', () => {
      const files = [
        { path: '/project/CLAUDE.md', byte_size: 1000 },
        { path: '/project/.claude/rules/a.md', byte_size: 500 },
      ];
      instructionsLoadedDispatcher(makeInput(files));
      expect(mockTokenBudget).toHaveBeenCalledWith(files);
      expect(mockDriftDetection).toHaveBeenCalledWith(files);
    });
  });

  describe('handler output merging', () => {
    test('returns prompt context when one handler produces output', () => {
      mockTokenBudget.mockReturnValue('[Instruction Budget] 5000 tokens across 3 files (2.5% of context). Largest: CLAUDE.md (4000)');
      const input = makeInput([{ path: '/project/CLAUDE.md', byte_size: 20_000 }]);
      const result = instructionsLoadedDispatcher(input);
      expect(result.continue).toBe(true);
      // outputPromptContext injects additionalContext
      expect(result.suppressOutput).toBe(true);
    });

    test('joins multiple handler outputs with double newline', () => {
      mockTokenBudget.mockReturnValue('Budget output');
      mockPriorityMap.mockReturnValue('Priority output');
      const input = makeInput([{ path: '/project/CLAUDE.md', byte_size: 20_000 }]);
      const result = instructionsLoadedDispatcher(input);
      // additionalContext is under hookSpecificOutput per CC 2.1.9
      const context = result.hookSpecificOutput?.additionalContext;
      expect(context).toContain('Budget output');
      expect(context).toContain('Priority output');
      expect(context).toContain('\n\n');
    });

    test('includes only non-null handler results', () => {
      mockTokenBudget.mockReturnValue('Budget output');
      // All others null
      const input = makeInput([{ path: '/project/CLAUDE.md', byte_size: 20_000 }]);
      const result = instructionsLoadedDispatcher(input);
      const context = result.hookSpecificOutput?.additionalContext;
      expect(context).toBe('Budget output');
    });
  });

  describe('handler error isolation', () => {
    test('continues running remaining handlers when one throws', () => {
      mockTokenBudget.mockImplementation(() => { throw new Error('budget exploded'); });
      mockSmartSuggestions.mockReturnValue('Smart suggestion output');

      const input = makeInput([{ path: '/project/CLAUDE.md', byte_size: 1000 }]);
      const result = instructionsLoadedDispatcher(input);

      // Should not throw; smart suggestions still runs
      expect(result.continue).toBe(true);
      const context = result.hookSpecificOutput?.additionalContext;
      expect(context).toContain('Smart suggestion output');
    });

    test('returns silent success when all handlers throw', () => {
      const boom = () => { throw new Error('boom'); };
      mockTokenBudget.mockImplementation(boom);
      mockPriorityMap.mockImplementation(boom);
      mockDriftDetection.mockImplementation(boom);
      mockContentDedup.mockImplementation(boom);
      mockRuleConflicts.mockImplementation(boom);
      mockSmartSuggestions.mockImplementation(boom);

      const input = makeInput([{ path: '/project/CLAUDE.md', byte_size: 1000 }]);
      expect(() => instructionsLoadedDispatcher(input)).not.toThrow();
      const result = instructionsLoadedDispatcher(input);
      expect(result.continue).toBe(true);
      expect(result.suppressOutput).toBe(true);
    });
  });
});
