// Generated by OrchestKit Claude Plugin
// Created: 2026-09-14

// The optional-identity auth chain, walked end to end from /auth.md.
//
// Two claims are pinned, and they are the ones that are easy to break in
// opposite directions:
//
//   1. Every link in the discovery chain resolves. auth.md names the PRM, the
//      PRM names the authorization server, the AS metadata names its
//      endpoints, and each of those answers something other than 404. A
//      document that advertises a URL nobody serves is the "token endpoint
//      that does not exist" defect the brief rules out.
//   2. The 401 hint is raised ONLY where it is true: a presented bearer this
//      origin did not issue (or one that expired), and GET /agent/identity
//      with no bearer. Anonymous GET /api and POST /api/mcp stay untouched.
//      An always-on 401 on a public site scored once already (portfolio
//      GH-670) and was a lie. docs/adr/optional-agent-identity.md.

import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { NextRequest } from "next/server";
import { describe, expect, it, vi } from "vitest";

vi.mock("@/lib/analytics-server", () => ({
	reportServerEvent: vi.fn(),
	reportServerEvents: vi.fn(),
}));

import { GET as getApiIndex } from "@/app/api/route";
import { GET as getApiCatalog } from "@/app/api/well-known/api-catalog/route";
import { GET as getAsMetadata } from "@/app/api/well-known/oauth-authorization-server/route";
import { GET as getPrm } from "@/app/api/well-known/oauth-protected-resource/route";
import { GET as getApiPolicyMd } from "@/app/api-policy.md/route";
import {
	GET as getIdentity,
	OPTIONS as optionsIdentity,
	POST as postIdentity,
} from "@/app/agent/identity/route";
import { GET as getAuthMd } from "@/app/auth.md/route";
import { isServedPath } from "@/lib/agent-404";
import {
	IDENTITY_TOKEN_TYPE,
	mintIdentityAssertion,
	PRM_URL,
	verifyIdentityAssertion,
} from "@/lib/agent-identity";
import { SITE } from "@/lib/constants";
import { middleware } from "@/middleware";

const ORIGIN = SITE.domain;

type Handler = () => Response | Promise<Response>;

// Every URL the chain may advertise, mapped to the handler that serves it.
// A URL missing from this map is the failure the walk exists to catch.
const SERVED: Record<string, Handler> = {
	[`${ORIGIN}`]: () => new Response("home", { status: 200 }),
	[`${ORIGIN}/.well-known/oauth-protected-resource`]: getPrm,
	[`${ORIGIN}/.well-known/oauth-authorization-server`]: getAsMetadata,
	[`${ORIGIN}/auth.md`]: getAuthMd,
	[`${ORIGIN}/api-policy.md`]: getApiPolicyMd,
	[`${ORIGIN}/agent/identity`]: optionsIdentity,
};

async function resolves(url: string): Promise<number> {
	const handler = SERVED[url];
	expect(handler, `${url} is advertised but nothing in the map serves it`).toBeDefined();
	const res = await handler();
	expect(res.status, `${url} answered ${res.status}`).not.toBe(404);
	return res.status;
}

let ipCounter = 0;
function req(
	path: string,
	init: { method?: string; headers?: Record<string, string> } = {},
): NextRequest {
	ipCounter += 1;
	return new NextRequest(`${ORIGIN}${path}`, {
		method: init.method ?? "GET",
		headers: {
			accept: "application/json",
			"x-real-ip": `203.0.113.${(ipCounter % 250) + 1}`,
			...init.headers,
		},
	});
}

async function run(path: string, init?: Parameters<typeof req>[1]): Promise<Response> {
	return (await middleware(req(path, init))) as Response;
}

// ------------------------------------------------------------ the walk

describe("the discovery chain from /auth.md resolves at every hop", () => {
	it("auth.md names the PRM, and the PRM is served", async () => {
		const md = await getAuthMd().text();
		expect(md).toContain(PRM_URL);
		expect(await resolves(PRM_URL)).toBe(200);
	});

	it("the PRM is filled in: authorization server, scopes, bearer method", async () => {
		const prm = (await getPrm().json()) as {
			resource: string;
			authorization_servers: string[];
			scopes_supported: string[];
			bearer_methods_supported: string[];
			resource_documentation: string;
			authentication_required: boolean;
		};
		expect(prm.resource).toBe(ORIGIN);
		expect(prm.authorization_servers).toEqual([ORIGIN]);
		expect(prm.scopes_supported.length).toBeGreaterThan(0);
		expect(prm.bearer_methods_supported).toEqual(["header"]);
		expect(prm.resource_documentation).toBe(`${ORIGIN}/auth.md`);
		// Identity is optional and the document says so in one bit.
		expect(prm.authentication_required).toBe(false);
	});

	it("authorization_servers[0] leads to RFC 8414 metadata for that issuer", async () => {
		const prm = (await getPrm().json()) as { authorization_servers: string[] };
		const issuer = prm.authorization_servers[0];
		const asUrl = `${issuer}/.well-known/oauth-authorization-server`;
		expect(await resolves(asUrl)).toBe(200);
		const as = (await getAsMetadata().json()) as { issuer: string };
		expect(as.issuer).toBe(issuer);
	});

	it("every endpoint the AS metadata advertises resolves (no phantom token endpoint)", async () => {
		const as = (await getAsMetadata().json()) as Record<string, unknown> & {
			agent_auth: Record<string, unknown>;
		};
		// Endpoints this origin does not operate must be ABSENT, not pointed at
		// a 404. RFC 8414 lets them be omitted when the grant is not offered.
		for (const absent of [
			"authorization_endpoint",
			"token_endpoint",
			"registration_endpoint",
			"revocation_endpoint",
			"introspection_endpoint",
		]) {
			expect(as[absent], `${absent} is advertised but not served`).toBeUndefined();
		}
		for (const absent of ["claim_endpoint", "events_endpoint"]) {
			expect(as.agent_auth[absent], `agent_auth.${absent} is advertised but not served`)
				.toBeUndefined();
		}
		const advertised = [
			as.service_documentation,
			as.op_policy_uri,
			as.authorization_server_metadata,
			as.agent_auth.skill,
			as.agent_auth.identity_endpoint,
		];
		for (const url of advertised) {
			expect(typeof url).toBe("string");
			await resolves(url as string);
		}
	});

	it("the agent_auth block lists only what the identity endpoint accepts", async () => {
		const as = (await getAsMetadata().json()) as {
			agent_auth: {
				identity_endpoint: string;
				identity_types_supported: string[];
				identity_assertion: { assertion_types_supported: string[] };
			};
		};
		expect(as.agent_auth.identity_endpoint).toBe(`${ORIGIN}/agent/identity`);
		expect(as.agent_auth.identity_types_supported).toEqual([
			"anonymous",
			"identity_assertion",
		]);
		expect(as.agent_auth.identity_assertion.assertion_types_supported).toEqual([
			IDENTITY_TOKEN_TYPE,
		]);
		// service_auth needs a claim ceremony; the endpoint refuses it, so the
		// metadata must not offer it.
		const res = await postIdentity(
			new Request(`${ORIGIN}/agent/identity`, {
				method: "POST",
				headers: { "content-type": "application/json" },
				body: JSON.stringify({ type: "service_auth", login_hint: "a@b.c" }),
			}),
		);
		expect(res.status).toBe(400);
		expect(((await res.json()) as { error: string }).error).toBe("service_auth_not_enabled");
	});

	it("the catalog and the API index point at the same three documents", async () => {
		const catalog = (await getApiCatalog().json()) as {
			linkset: { item?: { href: string }[] }[];
		};
		const hrefs = catalog.linkset.flatMap((l) => l.item ?? []).map((i) => i.href);
		for (const u of [
			`${ORIGIN}/.well-known/oauth-protected-resource`,
			`${ORIGIN}/.well-known/oauth-authorization-server`,
			`${ORIGIN}/agent/identity`,
		]) {
			expect(hrefs, `catalog lacks ${u}`).toContain(u);
		}
		const index = (await getApiIndex().json()) as { discovery: Record<string, string> };
		expect(index.discovery.protectedResourceMetadata).toBe(PRM_URL);
		expect(index.discovery.authorizationServerMetadata).toBe(
			`${ORIGIN}/.well-known/oauth-authorization-server`,
		);
		expect(index.discovery.identity).toBe(`${ORIGIN}/agent/identity`);
	});

	it("middleware lets both metadata paths and the identity endpoint through to their handlers", () => {
		// /agent is not a served prefix; middleware answers unknown paths with a
		// JSON 404 BEFORE routing, so each exact path has to be listed.
		for (const p of [
			"/.well-known/oauth-protected-resource",
			"/.well-known/oauth-authorization-server",
			"/agent/identity",
		]) {
			expect(isServedPath(p), `${p} would be 404ed by middleware`).toBe(true);
		}
		const config = readFileSync(resolve(__dirname, "../next.config.mjs"), "utf8");
		expect(config).toContain('source: "/.well-known/oauth-authorization-server"');
	});
});

// ------------------------------------------------------------ the 401 rule

describe("the 401 hint is raised only where it is true", () => {
	const HINT = `resource_metadata="${PRM_URL}"`;

	it("anonymous GET /api is untouched (no 401, no challenge)", async () => {
		const res = await run("/api");
		expect(res.status).toBe(200);
		expect(res.headers.get("www-authenticate")).toBeNull();
	});

	it("anonymous POST /api/mcp is untouched", async () => {
		const res = await run("/api/mcp", {
			method: "POST",
			headers: { "content-type": "application/json" },
		});
		expect(res.status).toBe(200);
		expect(res.headers.get("www-authenticate")).toBeNull();
	});

	it("anonymous GET /api/mcp is not turned into a 401 either", async () => {
		// Live it answers 405 from the handler; middleware must not intercept.
		const res = await run("/api/mcp");
		expect(res.status).not.toBe(401);
		expect(res.headers.get("www-authenticate")).toBeNull();
	});

	it("an invalid bearer on /api is 401 with the discovery hint", async () => {
		const res = await run("/api", { headers: { authorization: "Bearer not-a-token" } });
		expect(res.status).toBe(401);
		const challenge = res.headers.get("www-authenticate") ?? "";
		expect(challenge).toMatch(/^Bearer /);
		expect(challenge).toContain('error="invalid_token"');
		expect(challenge).toContain(HINT);
		expect(res.headers.get("content-type")).toContain("application/json");
		const body = (await res.json()) as { status: number; resource_metadata: string; detail: string };
		expect(body.status).toBe(401);
		expect(body.resource_metadata).toBe(PRM_URL);
		expect(body.detail).toMatch(/optional/i);
	});

	it("an invalid bearer on /api/mcp is 401 with the same hint", async () => {
		const res = await run("/api/mcp", {
			method: "POST",
			headers: { authorization: "Bearer nope", "content-type": "application/json" },
		});
		expect(res.status).toBe(401);
		expect(res.headers.get("www-authenticate")).toContain(HINT);
	});

	it("an expired assertion is 401 and says so", async () => {
		const { token } = await mintIdentityAssertion({ now: Date.now() - 100_000_000, ttlSeconds: 60 });
		const res = await run("/api", { headers: { authorization: `Bearer ${token}` } });
		expect(res.status).toBe(401);
		expect(res.headers.get("www-authenticate")).toContain("expired");
	});

	it("a foreign issuer is 401 (it is not a token this origin issued)", async () => {
		const b64 = (v: unknown) =>
			Buffer.from(JSON.stringify(v)).toString("base64url");
		const foreign = `${b64({ alg: "HS256", typ: "oauth-id-jag+jwt" })}.${b64({
			iss: "https://example.com",
			aud: ORIGIN,
			sub: "reg_x",
			iat: 1,
			exp: Math.floor(Date.now() / 1000) + 3600,
		})}.AAAA`;
		const res = await run("/api", { headers: { authorization: `Bearer ${foreign}` } });
		expect(res.status).toBe(401);
		expect(res.headers.get("www-authenticate")).toContain("not issued by this origin");
	});

	it("a valid assertion passes through, and grants nothing extra", async () => {
		const { token } = await mintIdentityAssertion();
		const res = await run("/api", { headers: { authorization: `Bearer ${token}` } });
		expect(res.status).toBe(200);
		expect(res.headers.get("www-authenticate")).toBeNull();
		// Same rate-limit decoration as an anonymous call on a metered route:
		// identity is not a tier. (/api itself is the unmetered index.)
		const metered = await run("/api/health", { headers: { authorization: `Bearer ${token}` } });
		expect(metered.status).toBe(200);
		expect(metered.headers.get("ratelimit-limit")).not.toBeNull();
	});

	it("other Authorization schemes are not this API's business", async () => {
		for (const authorization of ["Basic dXNlcjpwYXNz", 'Signature keyId="x"']) {
			const res = await run("/api", { headers: { authorization } });
			expect(res.status).toBe(200);
		}
	});

	it("a bearer on its way to the PostHog proxy is ignored", async () => {
		const res = await run("/ingest/e/", { headers: { authorization: "Bearer junk" } });
		expect(res.status).not.toBe(401);
	});

	it("GET /agent/identity without a bearer is 401 with the hint and no error code", async () => {
		const res = await getIdentity(new Request(`${ORIGIN}/agent/identity`));
		expect(res.status).toBe(401);
		const challenge = res.headers.get("www-authenticate") ?? "";
		expect(challenge).toContain(HINT);
		// RFC 6750 section 3.1: no error code when no token was sent.
		expect(challenge).not.toContain("error=");
	});

	it("auth.md no longer claims a 401 can never happen, and names both cases", async () => {
		const md = await getAuthMd().text();
		expect(md).not.toMatch(/never (a|returns?) `?401/i);
		expect(md).toContain("When you will see a 401");
		expect(md).toContain('error="invalid_token"');
		expect(md).toContain("GET https://orchestkit.yonyon.ai/agent/identity");
		expect(md).toMatch(/Identity is optional/);
	});
});

// ------------------------------------------------------------ the identity endpoint

describe("POST /agent/identity registers, GET reads it back", () => {
	const identityUrl = `${ORIGIN}/agent/identity`;

	async function register(body: unknown): Promise<Response> {
		return postIdentity(
			new Request(identityUrl, {
				method: "POST",
				headers: { "content-type": "application/json" },
				body: JSON.stringify(body),
			}),
		);
	}

	it("anonymous registration returns a verifiable assertion with anonymous scopes only", async () => {
		const res = await register({ type: "anonymous" });
		expect(res.status).toBe(201);
		const body = (await res.json()) as {
			registration_id: string;
			registration_type: string;
			identity_assertion: string;
			assertion_type: string;
			scopes: string[];
			pre_claim_scopes: string[];
			claim: unknown;
			token_endpoint: unknown;
		};
		expect(body.registration_id).toMatch(/^reg_/);
		expect(body.registration_type).toBe("anonymous");
		expect(body.assertion_type).toBe(IDENTITY_TOKEN_TYPE);
		expect(body.claim).toBeNull();
		expect(body.token_endpoint).toBeNull();
		expect(body.scopes).toEqual(body.pre_claim_scopes);
		const prm = (await getPrm().json()) as { scopes_supported: string[] };
		expect(body.scopes).toEqual(prm.scopes_supported);
		const verdict = await verifyIdentityAssertion(body.identity_assertion);
		expect(verdict.ok).toBe(true);
	});

	it("the assertion works as a bearer at GET /agent/identity and echoes the same registration", async () => {
		const reg = (await (await register({ type: "anonymous" })).json()) as {
			registration_id: string;
			identity_assertion: string;
		};
		const res = await getIdentity(
			new Request(identityUrl, {
				headers: { authorization: `Bearer ${reg.identity_assertion}` },
			}),
		);
		expect(res.status).toBe(200);
		const me = (await res.json()) as { registration_id: string; issuer: string };
		expect(me.registration_id).toBe(reg.registration_id);
		expect(me.issuer).toBe(ORIGIN);
		// And the same bearer travels through middleware to any public route.
		const viaMiddleware = await run("/agent/identity", {
			headers: { authorization: `Bearer ${reg.identity_assertion}` },
		});
		expect(viaMiddleware.status).toBe(200);
	});

	it("re-registration with this origin's assertion keeps the registration id", async () => {
		const reg = (await (await register({ type: "anonymous" })).json()) as {
			registration_id: string;
			identity_assertion: string;
		};
		const res = await register({
			type: "identity_assertion",
			assertion_type: IDENTITY_TOKEN_TYPE,
			assertion: reg.identity_assertion,
		});
		expect(res.status).toBe(200);
		const again = (await res.json()) as { registration_id: string; identity_assertion: string };
		expect(again.registration_id).toBe(reg.registration_id);
	});

	it("re-registration with a forged or foreign assertion is refused with an OAuth error", async () => {
		const res = await register({
			type: "identity_assertion",
			assertion_type: IDENTITY_TOKEN_TYPE,
			assertion: "eyJhbGciOiJIUzI1NiJ9.e30.bad",
		});
		expect(res.status).toBe(400);
		const body = (await res.json()) as { error: string };
		expect(["invalid_signature", "invalid_issuer", "expired"]).toContain(body.error);
	});

	it("a bearer this origin did not issue is 401 at GET /agent/identity too", async () => {
		const res = await getIdentity(
			new Request(identityUrl, { headers: { authorization: "Bearer garbage" } }),
		);
		expect(res.status).toBe(401);
		expect(res.headers.get("www-authenticate")).toContain('error="invalid_token"');
	});

	it("malformed bodies and unknown types are 400 invalid_request", async () => {
		const bad = await postIdentity(
			new Request(identityUrl, { method: "POST", body: "not json" }),
		);
		expect(bad.status).toBe(400);
		const unknown = await register({ type: "magic" });
		expect(unknown.status).toBe(400);
		expect(((await unknown.json()) as { error: string }).error).toBe("invalid_request");
	});

	it("OPTIONS resolves and names the methods", () => {
		const res = optionsIdentity();
		expect(res.status).toBe(204);
		expect(res.headers.get("allow")).toBe("GET, POST, OPTIONS");
		expect(res.headers.get("access-control-allow-headers")).toContain("Authorization");
	});
});
