// Generated by OrchestKit Claude Plugin
// Created: 2026-07-31

import { describe, expect, it } from "vitest";
import { mcpTelemetryEvents } from "@/lib/mcp-telemetry";

describe("mcpTelemetryEvents", () => {
	it("records the handshake, including which agent implementation connected", () => {
		const events = mcpTelemetryEvents([
			{
				request: {
					jsonrpc: "2.0",
					id: 1,
					method: "initialize",
					params: {
						protocolVersion: "2025-06-18",
						clientInfo: { name: "claude-code", version: "2.1.220" },
					},
				},
				response: { jsonrpc: "2.0", id: 1, result: {} },
			},
		]);
		expect(events).toHaveLength(1);
		expect(events[0].name).toBe("agent:mcp-call");
		expect(events[0].path).toBe("/api/mcp");
		expect(events[0].properties).toMatchObject({
			method: "initialize",
			protocol_version: "2025-06-18",
			client_name: "claude-code",
			is_error: false,
		});
	});

	it("records tool selection and result count for a successful search", () => {
		const events = mcpTelemetryEvents([
			{
				request: {
					method: "tools/call",
					params: {
						name: "orchestkit_docs_search",
						arguments: { query: "hooks" },
					},
				},
				response: {
					result: {
						content: [{ type: "text", text: "..." }],
						structuredContent: { results: [{}, {}, {}] },
					},
				},
			},
		]);
		expect(events[0].properties).toMatchObject({
			method: "tools/call",
			tool: "orchestkit_docs_search",
			result_count: 3,
			query_len: 5,
			is_error: false,
		});
		// Raw text is NOT sent when the query matched something.
		expect(events[0].properties.query).toBeUndefined();
	});

	it("sends the raw (truncated) query ONLY on a zero-result call", () => {
		const events = mcpTelemetryEvents([
			{
				request: {
					method: "tools/call",
					params: {
						name: "orchestkit_docs_search",
						arguments: { query: "  kubernetes operator  " },
					},
				},
				response: { result: { structuredContent: { results: [] } } },
			},
		]);
		expect(events[0].properties.result_count).toBe(0);
		expect(events[0].properties.query).toBe("kubernetes operator");
	});

	it("flags a tool-level failure (isError) as an error", () => {
		const events = mcpTelemetryEvents([
			{
				request: {
					method: "tools/call",
					params: { name: "orchestkit_docs_get", arguments: { path: "/nope" } },
				},
				response: { result: { content: [], isError: true } },
			},
		]);
		expect(events[0].properties.is_error).toBe(true);
		expect(events[0].properties.tool).toBe("orchestkit_docs_get");
	});

	it("flags a JSON-RPC error, and keeps the unknown tool name it was called with", () => {
		const events = mcpTelemetryEvents([
			{
				request: { method: "tools/call", params: { name: "search_docs" } },
				response: {
					error: { code: -32602, message: "Unknown tool: search_docs" },
				},
			},
		]);
		expect(events[0].properties).toMatchObject({
			tool: "search_docs",
			is_error: true,
			error_code: -32602,
		});
	});

	it("ignores transport chatter — notifications and ping produce no events", () => {
		expect(
			mcpTelemetryEvents([
				{ request: { method: "notifications/initialized" }, response: null },
				{ request: { method: "ping", id: 2 }, response: { result: {} } },
				{ request: { method: "resources/read" }, response: { result: {} } },
			]),
		).toEqual([]);
	});

	it("emits one event per reported request in a JSON-RPC batch", () => {
		const events = mcpTelemetryEvents(
			[
				{ request: { method: "tools/list" }, response: { result: {} } },
				{
					request: {
						method: "tools/call",
						params: { name: "orchestkit_docs_search", arguments: {} },
					},
					response: { result: { structuredContent: { results: [{}] } } },
				},
			],
			{ ua_family: "claudebot", accept_family: "json" },
		);
		expect(events.map((e) => e.properties.method)).toEqual([
			"tools/list",
			"tools/call",
		]);
		// The shared audience properties ride along on every event in the batch.
		for (const e of events) {
			expect(e.properties.ua_family).toBe("claudebot");
			expect(e.properties.accept_family).toBe("json");
		}
	});

	it("survives malformed input without throwing", () => {
		expect(
			mcpTelemetryEvents([
				{ request: null, response: null },
				{ request: "not-an-object", response: 42 },
				{ request: { method: 7 }, response: {} },
				{ request: { method: "tools/call" }, response: {} },
			]),
		).toHaveLength(1); // only the tools/call, with tool: "unknown"
	});

	it("caps agent-supplied names so a hostile client cannot blow up cardinality", () => {
		const events = mcpTelemetryEvents([
			{
				request: {
					method: "tools/call",
					params: { name: "z".repeat(500) },
				},
				response: { result: {} },
			},
		]);
		expect(String(events[0].properties.tool)).toHaveLength(64);
	});
});
