#!/usr/bin/env bash
# Generated by OrchestKit Claude Plugin
# Created: 2026-08-08

# scripts/probe-command-discovery.sh — the #3314 tripwire.
#
# QUESTION IT ANSWERS
# -------------------
# Does Claude Code surface a plugin's user-invocable skills as slash commands
# WITHOUT the generated commands/*.md wrappers? Upstream anthropics/claude-code
# #18949 says no; scripts/build-plugins.sh:51 generates 35 wrapper files
# (9,960 lines) purely to work around that, with a note to delete them "when
# #18949 ships". Issue labels are not evidence — this script asks the binary.
#
# METHOD (the 2026-08-08 probe, mechanized)
# -----------------------------------------
# Two fixtures from the real built plugin, installed into isolated
# CLAUDE_CONFIG_DIRs so nothing touches the developer's config:
#
#   A  CONTROL  plugins/ork as built (commands/ present)
#   B  PROBE    identical, commands/ removed + plugin.json "commands" key
#               stripped (mirroring build-plugins.sh's has_commands behaviour)
#
# A throwaway `claude --debug -p` run needs no login to reach plugin loading;
# the loader logs a per-plugin counter into <config>/debug/<session>.txt:
#
#   Total plugin commands loaded: <n>
#
# Observed at 2.1.226 on 2026-08-08:  A=35, B=0  ->  wrappers load-bearing.
#
# EXIT CODES (same contract as scripts/derive-cc-output-keys.mjs)
# ---------------------------------------------------------------
#   0  wrappers still required (B loads 0 commands, control healthy)
#   1  TRIPPED: B loaded commands without wrappers — #18949 has effectively
#      shipped. Execute the DELETE branch of #3314: remove
#      generate_command_from_skill, plugins/ork/commands/, the passthrough
#      test and its ci.yml wiring, in one commit.
#   2  CANNOT OBSERVE: binary missing, control failed to show 35, or the
#      debug line vanished (log format drift). NOT a verdict either way.
#
# Runs locally / workflow_dispatch only — ci.yml never installs the CC binary,
# so wiring this into the PR gate would make it vacuously green (the #959
# class). Invoke as: npm run verify:cc-commands

set -euo pipefail
trap 'echo "[probe-command-discovery] failed at line $LINENO" >&2' ERR

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# Latest installed CC binary. `command -v claude` is NOT trustworthy here: on
# this estate it resolves to a cmux shim (corrupted 3 of 6 audit buckets on
# 2026-08-08), so go straight to the versions directory.
VERSIONS_DIR="$HOME/.local/share/claude/versions"
if [[ ! -d "$VERSIONS_DIR" ]]; then
  echo "CANNOT OBSERVE: $VERSIONS_DIR does not exist — no CC binary to probe." >&2
  exit 2
fi
BIN="$VERSIONS_DIR/$(ls -1 "$VERSIONS_DIR" | sort -V | tail -1)"
if [[ ! -x "$BIN" ]]; then
  echo "CANNOT OBSERVE: $BIN is not executable." >&2
  exit 2
fi

PLUGIN_SRC="$PROJECT_ROOT/plugins/ork"
if [[ ! -d "$PLUGIN_SRC/commands" ]]; then
  echo "CANNOT OBSERVE: $PLUGIN_SRC/commands missing — run npm run build first." >&2
  exit 2
fi
EXPECTED_COMMANDS=$(ls "$PLUGIN_SRC/commands"/*.md | awk 'END{print NR}')

WORK="$(mktemp -d)"
cleanup() { rm -rf "$WORK"; }
trap cleanup EXIT

# probe_one <label> <strip_commands: yes|no> — prints the loaded-commands count,
# or the literal string ABSENT when the debug counter line never appeared.
probe_one() {
  local label="$1" strip="$2"
  local fix="$WORK/$label"
  mkdir -p "$fix/.claude-plugin"
  cp -R "$PLUGIN_SRC" "$fix/plugin"
  if [[ "$strip" == "yes" ]]; then
    rm -rf "$fix/plugin/commands"
    jq 'del(.commands)' "$fix/plugin/.claude-plugin/plugin.json" \
      > "$fix/pj.tmp" && mv "$fix/pj.tmp" "$fix/plugin/.claude-plugin/plugin.json"
  fi
  cat > "$fix/.claude-plugin/marketplace.json" <<JSON
{
  "name": "probe-$label",
  "description": "#3314 discovery probe ($label)",
  "owner": { "name": "probe" },
  "plugins": [
    { "name": "ork", "description": "probe fixture", "version": "0.0.0",
      "category": "development", "source": "./plugin" }
  ]
}
JSON

  local cfg="$WORK/cfg-$label"
  mkdir -p "$cfg"
  CLAUDE_CONFIG_DIR="$cfg" "$BIN" plugin marketplace add "$fix" \
    > "$WORK/$label-add.log" 2>&1
  CLAUDE_CONFIG_DIR="$cfg" "$BIN" plugin install "ork@probe-$label" \
    > "$WORK/$label-install.log" 2>&1

  # The -p run exits non-zero in a fresh config (no login) AFTER plugin
  # loading has already been logged; that exit code is expected, so it is
  # captured rather than allowed to trip set -e.
  local rc=0
  CLAUDE_CONFIG_DIR="$cfg" "$BIN" --debug -p 'noop' --max-turns 1 \
    < /dev/null > "$WORK/$label-run.log" 2>&1 || rc=$?

  local dbg
  dbg="$(ls -t "$cfg/debug/"*.txt 2>&1 | head -1)"
  if [[ ! -f "$dbg" ]]; then
    echo "ABSENT"
    return 0
  fi
  # Exactly the loader's counter. awk never exits non-zero on no-match, so a
  # missing line yields ABSENT rather than a swallowed failure.
  awk '/Total plugin commands loaded:/ { n = $NF } END { print (n == "" ? "ABSENT" : n) }' "$dbg"
}

echo "probe-command-discovery: binary $(basename "$BIN"), expecting $EXPECTED_COMMANDS wrappers"

CONTROL=$(probe_one control no)
PROBE=$(probe_one probe yes)

echo "  control (with commands/)  : $CONTROL"
echo "  probe   (without)         : $PROBE"

if [[ "$CONTROL" == "ABSENT" || "$PROBE" == "ABSENT" ]]; then
  echo "CANNOT OBSERVE: the 'Total plugin commands loaded' debug line is gone —" >&2
  echo "the log format drifted. Update the awk pattern; no verdict." >&2
  exit 2
fi
if [[ "$CONTROL" != "$EXPECTED_COMMANDS" ]]; then
  echo "CANNOT OBSERVE: control loaded $CONTROL commands, expected $EXPECTED_COMMANDS —" >&2
  echo "the harness itself is broken, so the probe result proves nothing." >&2
  exit 2
fi

if [[ "$PROBE" != "0" ]]; then
  echo "" >&2
  echo "TRIPPED: $PROBE commands loaded WITHOUT wrapper files." >&2
  echo "Upstream #18949 has effectively shipped in $(basename "$BIN")." >&2
  echo "Execute the DELETE branch of #3314: remove generate_command_from_skill" >&2
  echo "from scripts/build-plugins.sh, plugins/ork/commands/, and" >&2
  echo "tests/plugins/test-command-frontmatter-passthrough.sh + its ci.yml" >&2
  echo "wiring, in one commit." >&2
  exit 1
fi

echo "OK: wrappers still load-bearing (skills do not surface as commands without them)."
exit 0
