#!/usr/bin/env bash
# Generated by OrchestKit Claude Plugin
# Created: 2026-05-05

# Validate ASCII design tokens against schema + primitives membership.
# Usage: scripts/validate-tokens.sh
# Exit:  0 on pass, 1 on validation failure, 2 on missing dependency.

set -euo pipefail

SKILL_DIR="${ASCII_SKILL_DIR:-src/skills/ascii-visualizer}"
PRIMITIVES="$SKILL_DIR/primitives.json"
TOKENS="$SKILL_DIR/tokens.json"
SCHEMA="$SKILL_DIR/tokens.schema.json"

fail=0
warn() { printf '⚠  %s\n' "$*" >&2; }
err()  { printf '✗  %s\n' "$*" >&2; fail=1; }
ok()   { printf '✓  %s\n' "$*"; }

command -v jq >/dev/null 2>&1 || { warn "jq not found — cannot validate"; exit 2; }

for f in "$PRIMITIVES" "$TOKENS" "$SCHEMA"; do
  [ -f "$f" ] || { err "missing file: $f"; exit 1; }
  jq -e . "$f" >/dev/null || { err "invalid JSON: $f"; exit 1; }
done
ok "JSON syntax: 3 files parsed"

prim_chars=$(jq -r '.glyphs | to_entries[] | .value' "$PRIMITIVES" | sort -u)

token_chars=$(jq -r '
  [ .sets[]? | (.corner // {}) | .[] ]
  + [ .sets[]? | (.edge // {}) | .[] ]
  + [ .sets[]? | (.junction // {}) | .[] ]
  + [ .arrows[]? | (.right // empty), (.left // empty), (.up // empty), (.down // empty) ]
  + [ .fills | (.high // empty), (.med // empty), (.low // empty), (.full // empty) ]
  + (.fills.bars // [])
  | .[] | select(. != null and . != " ")
' "$TOKENS" | sort -u)

missing=0
while IFS= read -r ch; do
  [ -z "$ch" ] && continue
  if ! printf '%s\n' "$prim_chars" | grep -qxF -- "$ch"; then
    err "tokens.json uses glyph not in primitives.json: '$ch'"
    missing=$((missing + 1))
  fi
done <<EOF
$token_chars
EOF

[ "$missing" -eq 0 ] && ok "primitives membership: all token glyphs catalogued"

# silent: best-effort (feature-detect optional jsonschema dependency)
if command -v python3 >/dev/null 2>&1 && python3 -c "import jsonschema" 2>/dev/null; then
  if python3 -c "
import json, sys, jsonschema
with open('$SCHEMA') as s, open('$TOKENS') as t:
    schema = json.load(s); tokens = json.load(t)
try:
    jsonschema.validate(instance=tokens, schema=schema)
    print('✓  schema: tokens.json conforms to tokens.schema.json')
except jsonschema.ValidationError as e:
    print('✗  schema validation failed: ' + str(e.message), file=sys.stderr)
    sys.exit(1)
"; then :; else fail=1; fi
else
  warn "python3 jsonschema not available — schema check skipped (install: pip install jsonschema)"
fi

[ "$fail" -eq 0 ] || exit 1
ok "validate-tokens: PASS"
