// Generated by OrchestKit Claude Plugin
// Created: 2026-06-10

/**
 * Canary tests for lib/cost-estimator (#2338).
 *
 * This module had ZERO tests and zero importers when Fable 5 launched — the
 * missing claude-fable-5 pricing entry silently fell back to sonnet pricing
 * (getPricing's unknown-model default), underbilling by 70%. These canaries
 * pin the vocab-derived pricing table so a future model launch can't hide
 * the same way: the explicit-entry assertions fail loudly when the vocab
 * lags a pricing change, and the fallback test pins the current
 * unknown-model behavior so any change to it is a conscious decision.
 *
 * KEEP decision (#2338): the module stays (analytics/cost-estimation skill
 * references it; ~/.claude/orchestkit-pricing.json user-override contract is
 * public). Deleting it remains an option but belongs in its own PR.
 */

import { describe, it, expect } from 'vitest';
import { getCostConfig, __internals } from '../../lib/cost-estimator.js';
import modelsVocab from '../../lib/models.vocab.json';

const { resolveModelKey, getPricing, calculateCost } = __internals;

const MTOK = { input: 1_000_000, output: 1_000_000, cache_read: 0, cache_write: 0 };

describe('cost-estimator vocab canaries (#2338)', () => {
  it('prices claude-fable-5 at $10/$50 per MTok (cache 1.0/12.5)', () => {
    const fable = getCostConfig().models['claude-fable-5'];
    expect(fable).toEqual({
      input_per_mtok: 10.0,
      output_per_mtok: 50.0,
      cache_read_per_mtok: 1.0,
      cache_write_per_mtok: 12.5,
    });
  });

  it('keeps the classifier-fallback model claude-opus-4-8 at $5/$25', () => {
    const opus = getCostConfig().models['claude-opus-4-8'];
    expect(opus?.input_per_mtok).toBe(5.0);
    expect(opus?.output_per_mtok).toBe(25.0);
  });

  it('every vocab pricing entry follows the cache 0.1x/1.25x convention', () => {
    for (const [id, p] of Object.entries(modelsVocab.pricing)) {
      expect(p.cache_read_per_mtok, `${id} cache_read`).toBeCloseTo(p.input_per_mtok * 0.1, 5);
      expect(p.cache_write_per_mtok, `${id} cache_write`).toBeCloseTo(p.input_per_mtok * 1.25, 5);
    }
  });

  it('resolves the `fable` alias to claude-fable-5 pricing', () => {
    expect(resolveModelKey('fable')).toBe('claude-fable-5');
    expect(calculateCost('fable', MTOK).total).toBeCloseTo(60.0, 5); // $10 + $50
  });

  it('resolves `opus` alias to claude-opus-5 (alias table cannot silently flip)', () => {
    // Advanced claude-opus-4-8 -> claude-opus-5 on 2026-07-25 (CC 2.1.219 made
    // Opus 5 the default Opus). The per-MTok total is unchanged because both
    // price at $5/$25, so this assertion is the only thing that catches the flip.
    expect(resolveModelKey('opus')).toBe('claude-opus-5');
    expect(calculateCost('opus', MTOK).total).toBeCloseTo(30.0, 5); // $5 + $25
  });

  it('prices claude-opus-5 at $5/$25 per MTok (cache 0.5/6.25)', () => {
    expect(getCostConfig().models['claude-opus-5']).toEqual({
      input_per_mtok: 5.0,
      output_per_mtok: 25.0,
      cache_read_per_mtok: 0.5,
      cache_write_per_mtok: 6.25,
    });
  });

  it('prices the 1M-context variant claude-opus-5[1m] via partial match', () => {
    // '[1m]' is a CC session-label suffix, not an API model ID. It only resolves
    // once the base ID is priced, which is why the missing entry hit BOTH forms.
    expect(getPricing('claude-opus-5[1m]').input_per_mtok).toBe(5.0);
    expect(getPricing('claude-opus-5[1m]').output_per_mtok).toBe(25.0);
  });

  it('prices the 1M-context variant claude-fable-5[1m] via partial match', () => {
    expect(getPricing('claude-fable-5[1m]').input_per_mtok).toBe(10.0);
    expect(getPricing('claude-fable-5[1m]').output_per_mtok).toBe(50.0);
  });

  it('every full ID in the pricing table resolves to itself', () => {
    for (const id of Object.keys(modelsVocab.pricing)) {
      expect(resolveModelKey(id)).toBe(id);
    }
  });

  // The gap that let Opus 5 ship mispriced: the canaries above pin the pricing
  // TABLE, and the one below pins the unknown-model FALLBACK, but nothing
  // asserted that a model ork actually supports never reaches that fallback.
  // claude-opus-5 was a real fullId with no pricing row, so it resolved to
  // sonnet's $3/$15 and undercounted by 40% with no test turning red.
  it('no fullIds model silently takes the unknown-model fallback', () => {
    const TIER: Record<string, number> = {
      fable: 10.0,
      opus: 5.0,
      sonnet: 3.0,
      haiku: 1.0,
    };
    for (const id of modelsVocab.fullIds) {
      const family = Object.keys(TIER).find(f => id.includes(f));
      expect(family, `${id} matches no known family; add it to TIER`).toBeDefined();
      expect(getPricing(id).input_per_mtok, `${id} priced off-tier`).toBe(
        TIER[family as string],
      );
    }
  });

  it('PINS current behavior: unknown models fall back to sonnet pricing', () => {
    // This is the behavior that hid the missing fable entry. Pinned so any
    // future change (e.g. throw / log) is a conscious decision, and so the
    // fallback can never again be confused with a real pricing entry.
    const p = getPricing('zz-totally-unknown-model-9');
    expect(p.input_per_mtok).toBe(3.0);
    expect(p.output_per_mtok).toBe(15.0);
  });
});
