// Generated by OrchestKit Claude Plugin
// Created: 2026-04-03

import { describe, it, expect, beforeEach, afterEach, afterAll, vi } from 'vitest';
import type { TelemetryEvent } from '../../lib/telemetry.js';

// Track mock calls
let mockFetchCalls: Array<{ url: string; options: RequestInit }> = [];
let mockFetchResolve = true;
let logMessages: string[] = [];

// Mock fetch globally
const originalFetch = globalThis.fetch;
globalThis.fetch = vi.fn(async (url: string | URL | Request, options?: RequestInit) => {
  mockFetchCalls.push({ url: url as string, options: options! });
  if (!mockFetchResolve) throw new Error('Network error');
  return new Response('{}', { status: 202 });
}) as unknown as typeof fetch;

// Mock dependencies
vi.mock('../../lib/crypto.js', () => ({
  signPayload: (body: string, secret: string) => `sha256=mock-${secret}-${body.length}`,
}));

let mockWebhookUrl: string | undefined = 'https://hq.example.com/api/hooks';

vi.mock('../../lib/orchestration-state.js', () => ({
  getWebhookUrl: () => mockWebhookUrl,
}));

vi.mock('../../lib/common.js', () => ({
  logHook: (_name: string, msg: string) => { logMessages.push(msg); },
}));

import { HttpSink } from '../../lib/http-sink.js';

function makeEvent(overrides: Partial<TelemetryEvent> = {}): TelemetryEvent {
  return {
    event: 'PreToolUse',
    session_id: 'sess-test',
    project: 'test-project',
    timestamp: '2026-04-03T12:00:00.000Z',
    data: { tool_name: 'Bash' },
    metadata: { branch: 'main', source_channel: 'orchestkit-forwarder' },
    ...overrides,
  };
}

describe('HttpSink', () => {
  let sink: HttpSink;

  beforeEach(() => {
    sink = new HttpSink();
    mockFetchCalls = [];
    logMessages = [];
    mockFetchResolve = true;
    mockWebhookUrl = 'https://hq.example.com/api/hooks';
    process.env.ORCHESTKIT_HOOK_TOKEN = 'test-secret-token';
  });

  afterEach(() => {
    delete process.env.ORCHESTKIT_HOOK_TOKEN;
  });

  describe('interface compliance', () => {
    it('has name "http"', () => {
      expect(sink.name).toBe('http');
    });

    it('accepts all events (empty supportedEvents)', () => {
      expect(sink.supportedEvents).toEqual([]);
    });

    it('flush is a no-op', async () => {
      await expect(sink.flush()).resolves.toBeUndefined();
    });
  });

  describe('addEvent', () => {
    it('POSTs to {hookUrl}/cc-event', async () => {
      sink.addEvent(makeEvent());
      await vi.waitFor(() => expect(mockFetchCalls).toHaveLength(1));

      expect(mockFetchCalls[0].url).toBe('https://hq.example.com/api/hooks/cc-event');
    });

    it('strips trailing slash from hookUrl', async () => {
      mockWebhookUrl = 'https://hq.example.com/api/hooks/';
      sink.addEvent(makeEvent());
      await vi.waitFor(() => expect(mockFetchCalls).toHaveLength(1));

      expect(mockFetchCalls[0].url).toBe('https://hq.example.com/api/hooks/cc-event');
    });

    it('sends JSON body matching event', async () => {
      const event = makeEvent({ event: 'SessionStart' });
      sink.addEvent(event);
      await vi.waitFor(() => expect(mockFetchCalls).toHaveLength(1));

      const sentBody = JSON.parse(mockFetchCalls[0].options.body as string);
      expect(sentBody.event).toBe('SessionStart');
      expect(sentBody.session_id).toBe('sess-test');
      expect(sentBody.project).toBe('test-project');
    });

    it('includes Content-Type and HMAC signature headers', async () => {
      sink.addEvent(makeEvent());
      await vi.waitFor(() => expect(mockFetchCalls).toHaveLength(1));

      const headers = mockFetchCalls[0].options.headers as Record<string, string>;
      expect(headers['Content-Type']).toBe('application/json');
      expect(headers['X-CC-Hooks-Signature']).toMatch(/^sha256=mock-test-secret-token-\d+$/);
    });

    it('uses POST method', async () => {
      sink.addEvent(makeEvent());
      await vi.waitFor(() => expect(mockFetchCalls).toHaveLength(1));

      expect(mockFetchCalls[0].options.method).toBe('POST');
    });

    it('includes AbortSignal timeout', async () => {
      sink.addEvent(makeEvent());
      await vi.waitFor(() => expect(mockFetchCalls).toHaveLength(1));

      expect(mockFetchCalls[0].options.signal).toBeDefined();
    });

    it('no-ops when hookUrl is not set', () => {
      mockWebhookUrl = undefined;
      sink.addEvent(makeEvent());
      expect(mockFetchCalls).toHaveLength(0);
    });

    it('no-ops when hookToken is not set', () => {
      delete process.env.ORCHESTKIT_HOOK_TOKEN;
      sink.addEvent(makeEvent());
      expect(mockFetchCalls).toHaveLength(0);
    });

    it('handles fetch failure silently (fire-and-forget)', async () => {
      mockFetchResolve = false;
      sink.addEvent(makeEvent());

      // Wait for the catch to fire
      await new Promise(r => setTimeout(r, 50));

      expect(logMessages.some(m => m.includes('Forward failed'))).toBe(true);
    });

    it('logs success on successful POST', async () => {
      sink.addEvent(makeEvent());
      await new Promise(r => setTimeout(r, 50));

      expect(logMessages.some(m => m.includes('Forwarded PreToolUse'))).toBe(true);
    });

    it('sends multiple events independently', async () => {
      sink.addEvent(makeEvent({ event: 'PreToolUse' }));
      sink.addEvent(makeEvent({ event: 'PostToolUse' }));
      sink.addEvent(makeEvent({ event: 'SessionEnd' }));

      await vi.waitFor(() => expect(mockFetchCalls).toHaveLength(3));

      const events = mockFetchCalls.map(c => JSON.parse(c.options.body as string).event);
      expect(events).toContain('PreToolUse');
      expect(events).toContain('PostToolUse');
      expect(events).toContain('SessionEnd');
    });
  });
});

// Restore fetch after all tests
afterAll(() => {
  globalThis.fetch = originalFetch;
});
