// Generated by OrchestKit Claude Plugin
// Created: 2026-05-03

/**
 * Regression tests for safeMkdirSync — last-line defence against #1250
 * (`{"continue":true,"suppressOutput":true}` directory created at project root).
 */

import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { mkdtempSync, existsSync, rmSync, readdirSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { safeMkdirSync, looksLikePath } from '../../lib/safe-fs.js';

const LEAKED_JSON = '{"continue":true,"suppressOutput":true}';
const LEAKED_ARRAY = '[1,2]';

describe('looksLikePath', () => {
  it('rejects JSON-shaped strings', () => {
    expect(looksLikePath(LEAKED_JSON)).toBe(false);
    expect(looksLikePath(LEAKED_ARRAY)).toBe(false);
  });

  it('rejects empty / non-string values', () => {
    expect(looksLikePath('')).toBe(false);
    expect(looksLikePath(null as unknown as string)).toBe(false);
    expect(looksLikePath(undefined as unknown as string)).toBe(false);
    expect(looksLikePath(42 as unknown as string)).toBe(false);
  });

  it('rejects strings with null bytes', () => {
    expect(looksLikePath('/tmp/a\0b')).toBe(false);
  });

  it('accepts ordinary path strings', () => {
    expect(looksLikePath('/tmp/foo')).toBe(true);
    expect(looksLikePath('.')).toBe(true);
    expect(looksLikePath('relative/path')).toBe(true);
  });
});

describe('safeMkdirSync', () => {
  let scratch: string;
  let originalCwd: string;

  beforeEach(() => {
    originalCwd = process.cwd();
    scratch = mkdtempSync(join(tmpdir(), 'safe-fs-test-'));
    process.chdir(scratch);
  });

  afterEach(() => {
    process.chdir(originalCwd);
    rmSync(scratch, { recursive: true, force: true });
  });

  it('creates a normal directory', () => {
    const target = join(scratch, 'logs', 'audit');
    safeMkdirSync(target, { recursive: true });
    expect(existsSync(target)).toBe(true);
  });

  it('refuses to create a directory whose name looks like JSON', () => {
    safeMkdirSync(LEAKED_JSON, { recursive: true });
    expect(existsSync(join(scratch, LEAKED_JSON))).toBe(false);
    // Nothing else should have been created either
    expect(readdirSync(scratch)).toEqual([]);
  });

  it('refuses to create a JSON-prefixed nested path', () => {
    const bad = join(LEAKED_JSON, '.claude', 'logs');
    safeMkdirSync(bad, { recursive: true });
    expect(existsSync(join(scratch, LEAKED_JSON))).toBe(false);
  });

  it('returns undefined on rejection (does not throw)', () => {
    expect(() => safeMkdirSync(LEAKED_JSON, { recursive: true })).not.toThrow();
    expect(safeMkdirSync(LEAKED_JSON, { recursive: true })).toBeUndefined();
  });
});
