// Generated by OrchestKit Claude Plugin
// Created: 2026-06-12

/**
 * Tests for Session Identity (core helpers)
 *
 * Validates:
 * - hashColor determinism and palette membership
 * - parseIdentityOutput tolerance (fences, prose) and strictness (palette, length)
 * - mergeIdentityTitle 60-char budget
 * - buildGeneratorPrompt content
 */

import { mkdtempSync, mkdirSync, writeFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import {
  SESSION_COLOR_PALETTE,
  AI_TITLE_MAX,
  hashColor,
  parseIdentityOutput,
  mergeIdentityTitle,
  buildGeneratorPrompt,
  readEffectiveLanguage,
} from '../../lib/session-identity.js';

describe('hashColor', () => {
  it('is deterministic for the same session id', () => {
    expect(hashColor('abc-123')).toBe(hashColor('abc-123'));
  });

  it('always returns a palette member', () => {
    for (const id of ['a', 'session-1', '9601260e-d475-4c66-80aa-e0da7f885bbe', '']) {
      expect(SESSION_COLOR_PALETTE).toContain(hashColor(id));
    }
  });
});

describe('parseIdentityOutput', () => {
  it('parses strict JSON', () => {
    const out = parseIdentityOutput('{"title":"Fix auth middleware","color":"red"}');
    expect(out).toEqual({ title: 'Fix auth middleware', color: 'red' });
  });

  it('tolerates code fences and surrounding prose', () => {
    const raw = 'Sure! Here you go:\n```json\n{"title":"Docs crawl flywheel","color":"blue"}\n```\n';
    expect(parseIdentityOutput(raw)).toEqual({ title: 'Docs crawl flywheel', color: 'blue' });
  });

  it('normalizes color case and collapses title whitespace', () => {
    const out = parseIdentityOutput('{"title":"  Two\\n words  ","color":"CYAN"}');
    expect(out).toEqual({ title: 'Two words', color: 'cyan' });
  });

  it('rejects colors outside the /color palette', () => {
    expect(parseIdentityOutput('{"title":"Valid title","color":"magenta"}')).toBeNull();
    expect(parseIdentityOutput('{"title":"Valid title","color":"#ff0000"}')).toBeNull();
  });

  it('rejects missing or too-short titles', () => {
    expect(parseIdentityOutput('{"color":"red"}')).toBeNull();
    expect(parseIdentityOutput('{"title":"ab","color":"red"}')).toBeNull();
  });

  it('rejects non-JSON junk and empty output', () => {
    expect(parseIdentityOutput('')).toBeNull();
    expect(parseIdentityOutput('I cannot help with that.')).toBeNull();
    expect(parseIdentityOutput('{not json}')).toBeNull();
  });

  it('truncates overlong titles to AI_TITLE_MAX', () => {
    const long = 'x'.repeat(100);
    const out = parseIdentityOutput(`{"title":"${long}","color":"green"}`);
    expect(out?.title.length).toBe(AI_TITLE_MAX);
  });
});

describe('mergeIdentityTitle', () => {
  it('puts the AI topic before the branch title', () => {
    expect(mergeIdentityTitle('Fix auth middleware', 'feat/auth')).toBe(
      'Fix auth middleware · feat/auth',
    );
  });

  it('returns the AI title alone when there is no branch title', () => {
    expect(mergeIdentityTitle('Fix auth middleware', '')).toBe('Fix auth middleware');
  });

  it('caps the merged title at 60 chars', () => {
    const merged = mergeIdentityTitle('t'.repeat(50), 'b'.repeat(50));
    expect(merged.length).toBeLessThanOrEqual(60);
  });
});

describe('buildGeneratorPrompt', () => {
  it('includes the prompt excerpt, palette, and branch', () => {
    const p = buildGeneratorPrompt('fix the login bug\nplease', 'fix/login');
    expect(p).toContain('fix the login bug please');
    expect(p).toContain('Git branch: fix/login');
    for (const color of SESSION_COLOR_PALETTE) {
      expect(p).toContain(color);
    }
  });

  it('caps the excerpt length', () => {
    const p = buildGeneratorPrompt('y'.repeat(5000), '');
    expect(p.length).toBeLessThan(1500);
    expect(p).not.toContain('Git branch:');
  });

  // #2443 — respect the CC 2.1.176 `language` setting so the haiku title
  // matches CC's native localized session-list title.
  it('injects a language instruction for a non-English language', () => {
    const p = buildGeneratorPrompt('fix the login bug', 'fix/login', 'ja');
    expect(p).toContain('Write the title in this language: ja');
  });

  it('omits the language instruction for English / default', () => {
    expect(buildGeneratorPrompt('x', 'b', 'en')).not.toContain('Write the title in this language');
    expect(buildGeneratorPrompt('x', 'b')).not.toContain('Write the title in this language');
  });
});

describe('readEffectiveLanguage (#2443)', () => {
  // Isolate HOME so the user-settings fallback can't leak the real machine's
  // ~/.claude/settings.json into the default/malformed assertions.
  const savedHome = process.env.HOME;
  const savedUserProfile = process.env.USERPROFILE;
  let emptyHome: string;
  beforeEach(() => {
    emptyHome = mkdtempSync(join(tmpdir(), 'ork-home-'));
    process.env.HOME = emptyHome;
    process.env.USERPROFILE = emptyHome;
  });
  afterEach(() => {
    process.env.HOME = savedHome;
    process.env.USERPROFILE = savedUserProfile;
    rmSync(emptyHome, { recursive: true, force: true });
  });

  it('defaults to en when no projectDir / settings', () => {
    expect(readEffectiveLanguage(undefined)).toBe('en');
    expect(readEffectiveLanguage(join(tmpdir(), 'ork-no-such-dir-xyz'))).toBe('en');
  });

  it('reads language from project .claude/settings.json', () => {
    const dir = mkdtempSync(join(tmpdir(), 'ork-lang-'));
    try {
      mkdirSync(join(dir, '.claude'), { recursive: true });
      writeFileSync(join(dir, '.claude', 'settings.json'), JSON.stringify({ language: 'fr' }), 'utf8');
      expect(readEffectiveLanguage(dir)).toBe('fr');
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });

  it('defaults to en on malformed settings (fails open)', () => {
    const dir = mkdtempSync(join(tmpdir(), 'ork-lang-bad-'));
    try {
      mkdirSync(join(dir, '.claude'), { recursive: true });
      writeFileSync(join(dir, '.claude', 'settings.json'), '{not json', 'utf8');
      expect(readEffectiveLanguage(dir)).toBe('en');
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });
});
