// Generated by OrchestKit Claude Plugin
// Created: 2026-04-03

import { describe, it, expect, beforeEach, vi } from 'vitest';
import { mockCommonBasic } from '../fixtures/mock-common.js';

// Mock dependencies before importing
vi.mock('../../lib/common.js', () => mockCommonBasic({
  getSessionId: () => 'test-session-123',
  getCachedBranch: () => 'test-branch',
  logHook: () => {},
}));

vi.mock('../../lib/crypto.js', () => ({
  sanitizePayload: (obj: unknown) => obj,
  signPayload: (body: string, _secret: string) => `sha256=mock-${body.length}`,
}));

vi.mock('../../lib/orchestration-state.js', () => ({
  getWebhookUrl: () => 'https://example.com/api/hooks',
}));

vi.mock('../../lifecycle/usage-summary-reporter.js', () => ({
  getProjectSlug: () => 'test-project',
}));

import type { HookInput } from '../../types.js';
import type { TelemetrySink, TelemetryEvent } from '../../lib/telemetry.js';
import {
  registerSink,
  emit,
  flushAll,
  buildEvent,
  sinkCount,
  _resetSinksForTesting,
} from '../../lib/telemetry.js';
/** Minimal HookInput for testing */
function mockInput(overrides: Partial<HookInput> = {}): HookInput {
  return {
    hook_event: 'PreToolUse',
    session_id: 'sess-abc',
    tool_name: 'Bash',
    tool_input: { command: 'npm test' },
    project_dir: '/tmp/test-project',
    ...overrides,
  };
}

/** Test sink that records events */
class RecordingSink implements TelemetrySink {
  readonly name: string;
  readonly supportedEvents: string[];
  readonly events: TelemetryEvent[] = [];
  flushCalled = false;

  constructor(name = 'recorder', supportedEvents: string[] = []) {
    this.name = name;
    this.supportedEvents = supportedEvents;
  }

  addEvent(event: TelemetryEvent): void {
    this.events.push(event);
  }

  async flush(): Promise<void> {
    this.flushCalled = true;
  }
}

/** Sink that throws on addEvent */
class FailingSink implements TelemetrySink {
  readonly name = 'failing';
  readonly supportedEvents: string[] = [];

  addEvent(): void {
    throw new Error('Sink exploded');
  }

  async flush(): Promise<void> {
    throw new Error('Flush exploded');
  }
}

describe('Telemetry Emitter', () => {
  beforeEach(() => {
    _resetSinksForTesting();
  });

  describe('registerSink', () => {
    it('registers a sink', () => {
      registerSink(new RecordingSink());
      expect(sinkCount()).toBe(1);
    });

    it('deduplicates by name', () => {
      registerSink(new RecordingSink('same-name'));
      registerSink(new RecordingSink('same-name'));
      expect(sinkCount()).toBe(1);
    });

    it('allows multiple sinks with different names', () => {
      registerSink(new RecordingSink('sink-a'));
      registerSink(new RecordingSink('sink-b'));
      expect(sinkCount()).toBe(2);
    });
  });

  describe('buildEvent', () => {
    it('normalizes HookInput to TelemetryEvent', () => {
      const event = buildEvent(mockInput());
      expect(event.event).toBe('PreToolUse');
      expect(event.session_id).toBe('sess-abc');
      expect(event.project).toBe('test-project');
      expect(event.data.tool_name).toBe('Bash');
      expect(event.data.tool_input).toEqual({ command: 'npm test' });
      expect(event.metadata.source_channel).toBe('orchestkit-forwarder');
      expect(event.timestamp).toBeTruthy();
    });

    it('handles missing optional fields gracefully', () => {
      const event = buildEvent({ tool_input: {}, tool_name: '' } as any);
      expect(event.event).toBe('unknown');
      expect(event.data.tool_name).toBeUndefined();
      expect(event.data.agent_type).toBeUndefined();
    });
  });

  describe('emit', () => {
    it('fans out to all registered sinks', () => {
      const sink1 = new RecordingSink('s1');
      const sink2 = new RecordingSink('s2');
      registerSink(sink1);
      registerSink(sink2);

      emit(mockInput());

      expect(sink1.events).toHaveLength(1);
      expect(sink2.events).toHaveLength(1);
      expect(sink1.events[0].event).toBe('PreToolUse');
    });

    it('is a no-op with zero sinks (Grafana air-gapped pattern)', () => {
      // Should not throw
      emit(mockInput());
    });

    it('filters by supportedEvents', () => {
      const allSink = new RecordingSink('all', []);
      const sessionOnly = new RecordingSink('session', ['SessionEnd']);
      registerSink(allSink);
      registerSink(sessionOnly);

      emit(mockInput({ hook_event: 'PreToolUse' }));

      expect(allSink.events).toHaveLength(1);
      expect(sessionOnly.events).toHaveLength(0);
    });

    it('delivers SessionEnd to filtered sink', () => {
      const sessionOnly = new RecordingSink('session', ['SessionEnd']);
      registerSink(sessionOnly);

      emit(mockInput({ hook_event: 'SessionEnd' }));

      expect(sessionOnly.events).toHaveLength(1);
    });

    it('isolates sink failures — other sinks still receive events', () => {
      const before = new RecordingSink('before');
      const failing = new FailingSink();
      const after = new RecordingSink('after');

      registerSink(before);
      registerSink(failing);
      registerSink(after);

      // Should not throw
      emit(mockInput());

      expect(before.events).toHaveLength(1);
      expect(after.events).toHaveLength(1);
    });

    it('never throws even with bad input', () => {
      registerSink(new RecordingSink());
      // null input should not crash emit
      expect(() => emit(null as any)).not.toThrow();
    });
  });

  describe('flushAll', () => {
    it('calls flush() on all sinks', async () => {
      const sink1 = new RecordingSink('s1');
      const sink2 = new RecordingSink('s2');
      registerSink(sink1);
      registerSink(sink2);

      await flushAll();

      expect(sink1.flushCalled).toBe(true);
      expect(sink2.flushCalled).toBe(true);
    });

    it('continues flushing even if one sink fails', async () => {
      const failing = new FailingSink();
      const healthy = new RecordingSink('healthy');
      registerSink(failing);
      registerSink(healthy);

      await flushAll();

      expect(healthy.flushCalled).toBe(true);
    });

    it('does not throw with zero sinks', async () => {
      await expect(flushAll()).resolves.toBeUndefined();
    });
  });
});
