// Generated by OrchestKit Claude Plugin
// Created: 2026-05-20

/**
 * Registry-coverage gate (#1883 framework).
 *
 * Asserts two contracts:
 *   1. Every rule conforms to the schema (well-formed entries only).
 *   2. Every rule.id appears in the linter unit-test file at least twice
 *      (positive + negative test). The grep-based check is intentionally
 *      shallow — it catches "added a rule, forgot to test it" without
 *      requiring per-rule plumbing.
 */

import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

import { TOOL_INVOCATION_RULES } from '../../lib/tool-invocation-rules.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const LINTER_TEST_PATH = resolve(__dirname, '../pretool/tool-invocation-linter.test.ts');
const VALID_SEVERITIES = new Set(['warn', 'block', 'info']);

describe('tool-invocation-rules registry — schema contracts', () => {
  for (const rule of TOOL_INVOCATION_RULES) {
    describe(`rule "${rule.id}"`, () => {
      it('has a stable kebab-case id', () => {
        expect(rule.id).toMatch(/^[a-z0-9]+(-[a-z0-9]+)*$/);
      });
      it('has a non-empty tool_name', () => {
        expect(rule.tool_name).toBeTruthy();
        expect(typeof rule.tool_name).toBe('string');
      });
      it('has a function predicate', () => {
        expect(typeof rule.predicate).toBe('function');
      });
      it('has a valid severity (warn|block|info)', () => {
        expect(VALID_SEVERITIES.has(rule.severity)).toBe(true);
      });
      it('has a non-empty message ≤ 400 chars', () => {
        expect(rule.message).toBeTruthy();
        expect(rule.message.length).toBeGreaterThan(0);
        expect(rule.message.length).toBeLessThanOrEqual(400);
      });
      it('has a non-empty see pointer', () => {
        expect(rule.see).toBeTruthy();
        expect(rule.see.length).toBeGreaterThan(0);
      });
    });
  }

  it('has at least one rule (registry is not empty)', () => {
    expect(TOOL_INVOCATION_RULES.length).toBeGreaterThan(0);
  });

  it('every rule.id is unique', () => {
    const ids = TOOL_INVOCATION_RULES.map((r) => r.id);
    expect(new Set(ids).size).toBe(ids.length);
  });
});

describe('tool-invocation-rules registry — test coverage gate', () => {
  it('every rule.id appears in linter.test.ts at least twice', () => {
    const testSrc = readFileSync(LINTER_TEST_PATH, 'utf8');
    const offenders: { id: string; count: number }[] = [];

    for (const rule of TOOL_INVOCATION_RULES) {
      // Count occurrences of rule.id in the test file (positive + negative tests).
      const escaped = rule.id.replace(/[-/\\^$*+?.()|[\]{}]/g, '\\$&');
      const matches = testSrc.match(new RegExp(escaped, 'g'));
      const count = matches ? matches.length : 0;
      if (count < 2) offenders.push({ id: rule.id, count });
    }

    if (offenders.length > 0) {
      const lines = offenders.map(
        (o) => `  ${o.id}: only ${o.count} mention(s) in tool-invocation-linter.test.ts (need ≥ 2)`,
      );
      const msg = `${lines.join('\n')}\n  Add positive + negative tests referencing the rule id.`;
      throw new Error(`Registry coverage gate failed:\n${msg}`);
    }
  });
});
