// Generated by OrchestKit Claude Plugin
// Created: 2026-03-29

/**
 * Unit tests for readme-sync hook
 * Tests: readmeSync main hook, analyzeFileChange logic, findReadme logic
 */

import { describe, it, expect, vi, beforeEach } from 'vitest';

// ---------------------------------------------------------------------------
// Hoisted mocks
// ---------------------------------------------------------------------------
const { mockAppendFileSync } = vi.hoisted(() => ({
  mockAppendFileSync: vi.fn(),
}));

const { mockExistsSync, mockStatSync, mockMkdirSync } = vi.hoisted(() => ({
  mockExistsSync: vi.fn(() => false),
  mockStatSync: vi.fn(() => ({ mtime: new Date() })),
  mockMkdirSync: vi.fn(),
}));

// ---------------------------------------------------------------------------
// Module mocks
// ---------------------------------------------------------------------------
vi.mock('../../../lib/analytics-buffer.js', () => ({
  bufferWrite: vi.fn((filePath: string, content: string) => {
    mockAppendFileSync(filePath, content);
  }),
  flush: vi.fn(),
  pendingCount: vi.fn(() => 0),
  _resetForTesting: vi.fn(),
}));

vi.mock('../../../lib/common.js', () => ({
  logHook: vi.fn(),
  outputSilentSuccess: vi.fn(() => ({ continue: true, suppressOutput: true })),
  getProjectDir: vi.fn(() => '/mock/proj'),
  getField: vi.fn((input: Record<string, unknown>, path: string) => {
    const parts = path.split('.');
    let val: unknown = input;
    for (const p of parts) {
      if (val && typeof val === 'object') val = (val as Record<string, unknown>)[p];
      else return undefined;
    }
    return val;
  }),
}));

vi.mock('node:fs', () => ({
  existsSync: (...args: unknown[]) => mockExistsSync(...args),
  statSync: (...args: unknown[]) => mockStatSync(...args),
  mkdirSync: (...args: unknown[]) => mockMkdirSync(...args),
  readFileSync: vi.fn(() => ''),
}));

vi.mock('node:path', () => ({
  basename: vi.fn((p: string) => p.split('/').pop() || ''),
  dirname: vi.fn((p: string) => p.split('/').slice(0, -1).join('/')),
}));

// ---------------------------------------------------------------------------
// Imports (after mocks)
// ---------------------------------------------------------------------------
import { readmeSync } from '../../../posttool/write/readme-sync.js';
import { logHook } from '../../../lib/common.js';
import type { HookInput } from '../../../types.js';

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------
function makeInput(filePath: string, toolName = 'Write'): HookInput {
  return {
    tool_name: toolName,
    session_id: 'test-session',
    tool_input: { file_path: filePath, content: 'code' },
  };
}

// ===========================================================================
// TESTS
// ===========================================================================
describe('readme-sync', () => {
  beforeEach(() => {
    vi.clearAllMocks();
    mockExistsSync.mockReturnValue(false);
  });

  // =========================================================================
  // Guard clauses — early returns
  // =========================================================================
  describe('guard clauses', () => {
    it('returns silent success for non-Write tools', () => {
      // Act
      const result = readmeSync(makeInput('/mock/proj/src/app.ts', 'Read'));

      // Assert
      expect(result).toEqual({ continue: true, suppressOutput: true });
    });

    it('returns silent success when file_path is empty', () => {
      // Act
      const result = readmeSync(makeInput(''));

      // Assert
      expect(result).toEqual({ continue: true, suppressOutput: true });
    });

    it.each([
      '/mock/proj/.claude/config.json',
      '/mock/proj/node_modules/pkg/index.js',
      '/mock/proj/.git/HEAD',
      '/mock/proj/dist/bundle.js',
      '/mock/proj/package-lock.lock',
      '/mock/proj/app.log',
    ])('skips internal path: %s', (filePath) => {
      // Act
      const result = readmeSync(makeInput(filePath));

      // Assert
      expect(result).toEqual({ continue: true, suppressOutput: true });
    });

    it.each([
      '/mock/proj/src/__tests__/app.test.ts',
      '/mock/proj/tests/spec/foo.spec.js',
      '/mock/proj/test/unit/bar.ts',
    ])('skips test files: %s', (filePath) => {
      // Act
      const result = readmeSync(makeInput(filePath));

      // Assert
      expect(result).toEqual({ continue: true, suppressOutput: true });
    });
  });

  // =========================================================================
  // File change analysis — config files
  // =========================================================================
  describe('config file changes', () => {
    it('detects pyproject.toml as python-config', () => {
      // Arrange
      mockExistsSync.mockReturnValue(false); // no README

      // Act
      const result = readmeSync(makeInput('/mock/proj/pyproject.toml'));

      // Assert
      expect(result.continue).toBe(true);
      expect(result.hookSpecificOutput?.additionalContext).toContain('python-config');
    });

    it('detects Dockerfile as docker change', () => {
      // Arrange
      mockExistsSync.mockReturnValue(false);

      // Act
      const result = readmeSync(makeInput('/mock/proj/Dockerfile'));

      // Assert
      expect(result.hookSpecificOutput?.additionalContext).toContain('docker');
    });

    it('detects .env.example as env change', () => {
      // Arrange
      mockExistsSync.mockReturnValue(false);

      // Act
      const result = readmeSync(makeInput('/mock/proj/.env.example'));

      // Assert
      expect(result.hookSpecificOutput?.additionalContext).toContain('env');
    });

    it('detects docker-compose.yml as docker change', () => {
      // Arrange
      mockExistsSync.mockReturnValue(false);

      // Act
      const result = readmeSync(makeInput('/mock/proj/docker-compose.yml'));

      // Assert
      expect(result.hookSpecificOutput?.additionalContext).toContain('docker');
    });
  });

  // =========================================================================
  // File change analysis — route/config/entry/cli patterns
  // =========================================================================
  describe('path-based detection', () => {
    it('detects API route files', () => {
      // Arrange
      mockExistsSync.mockReturnValue(false);

      // Act
      const result = readmeSync(makeInput('/mock/proj/src/api/users.ts'));

      // Assert
      expect(result.hookSpecificOutput?.additionalContext).toContain('api');
    });

    it('detects config directory changes', () => {
      // Arrange
      mockExistsSync.mockReturnValue(false);

      // Act
      const result = readmeSync(makeInput('/mock/proj/src/config/database.ts'));

      // Assert
      expect(result.hookSpecificOutput?.additionalContext).toContain('config');
    });

    it('detects main entry points', () => {
      // Arrange — depth must be <= 4: 'src/main.py' splits to 2 parts
      mockExistsSync.mockReturnValue(false);

      // Act
      const result = readmeSync(makeInput('src/main.py'));

      // Assert
      expect(result.hookSpecificOutput?.additionalContext).toContain('entry-point');
    });

    it('skips deep entry points (depth > 4)', () => {
      // Arrange
      mockExistsSync.mockReturnValue(false);

      // Act
      const result = readmeSync(makeInput('/mock/proj/src/a/b/c/d/index.ts'));

      // Assert
      // depth = 8 > 4, so not detected as entry-point; but may match exports check
      // Since existsSync returns false for the file, exports check will skip
      expect(result).toEqual({ continue: true, suppressOutput: true });
    });

    it('detects CLI scripts', () => {
      // Arrange
      mockExistsSync.mockReturnValue(false);

      // Act
      const result = readmeSync(makeInput('/mock/proj/bin/deploy.sh'));

      // Assert
      expect(result.hookSpecificOutput?.additionalContext).toContain('cli');
    });
  });

  // =========================================================================
  // README presence and staleness
  // =========================================================================
  describe('README context messages', () => {
    it('suggests creating README when none found', () => {
      // Arrange
      mockExistsSync.mockReturnValue(false);

      // Act
      const result = readmeSync(makeInput('/mock/proj/Dockerfile'));

      // Assert
      expect(result.hookSpecificOutput?.additionalContext).toContain('no README.md found');
    });

    it('includes section suggestion when README exists', () => {
      // Arrange — README.md exists at first call (findReadme), file exists too
      mockExistsSync.mockImplementation((p: unknown) => {
        const path = String(p);
        if (path.includes('README')) return true;
        return false;
      });

      // Act
      const result = readmeSync(makeInput('/mock/proj/Dockerfile'));

      // Assert
      const ctx = result.hookSpecificOutput?.additionalContext as string;
      expect(ctx).toContain('Docker / Deployment');
      expect(ctx).toContain('docker');
    });

    it('appends staleness warning when README is old', () => {
      // Arrange
      const oldDate = new Date(Date.now() - 60 * 86400 * 1000); // 60 days ago
      mockExistsSync.mockImplementation((p: unknown) => {
        const path = String(p);
        return path.includes('README');
      });
      mockStatSync.mockReturnValue({ mtime: oldDate } as ReturnType<typeof import('node:fs').statSync>);

      // Act
      const result = readmeSync(makeInput('/mock/proj/Dockerfile'));

      // Assert
      const ctx = result.hookSpecificOutput?.additionalContext as string;
      expect(ctx).toContain('days ago');
    });
  });

  // =========================================================================
  // Logging
  // =========================================================================
  describe('logging', () => {
    it('logs to readme-sync log file via bufferWrite', () => {
      // Arrange
      mockExistsSync.mockReturnValue(false);

      // Act
      readmeSync(makeInput('/mock/proj/Dockerfile'));

      // Assert
      expect(mockAppendFileSync).toHaveBeenCalledTimes(1);
      expect(String(mockAppendFileSync.mock.calls[0][0])).toContain('readme-sync.log');
    });

    it('calls logHook with change type', () => {
      // Arrange
      mockExistsSync.mockReturnValue(false);

      // Act
      readmeSync(makeInput('/mock/proj/Dockerfile'));

      // Assert
      expect(logHook).toHaveBeenCalledWith(
        'readme-sync',
        expect.stringContaining('docker'),
      );
    });
  });

  // =========================================================================
  // No analysis match
  // =========================================================================
  describe('unrecognized files', () => {
    it('returns silent success for unrecognized file types', () => {
      // Act
      const result = readmeSync(makeInput('/mock/proj/src/utils/helpers.ts'));

      // Assert
      expect(result).toEqual({ continue: true, suppressOutput: true });
    });
  });

  // =========================================================================
  // Context message truncation
  // =========================================================================
  describe('truncation', () => {
    it('truncates context message over 200 chars', () => {
      // Arrange — README exists with a very old mtime to create a long message
      const oldDate = new Date(Date.now() - 365 * 86400 * 1000);
      mockExistsSync.mockImplementation((p: unknown) => {
        const path = String(p);
        return path.includes('README');
      });
      mockStatSync.mockReturnValue({ mtime: oldDate } as ReturnType<typeof import('node:fs').statSync>);

      // Act — use a setup.py to trigger python-config with long suggestion
      const result = readmeSync(makeInput('/mock/proj/setup.py'));

      // Assert — either truncated or within limit
      const ctx = result.hookSpecificOutput?.additionalContext as string;
      expect(ctx.length).toBeLessThanOrEqual(200);
    });
  });
});
