// Generated by OrchestKit Claude Plugin
// Created: 2026-03-26

/**
 * Unit tests for task-progress-initializer TaskCreated hook
 *
 * Tests the CC 2.1.84 TaskCreated handler that:
 * 1. Detects [N/M] numbered task patterns
 * 2. Initializes progress state for task-progress-tracker
 * 3. Skips non-numbered tasks
 *
 * @since CC 2.1.84
 */

import { describe, test, expect, beforeEach, vi } from 'vitest';

// Mock fs and path before imports
vi.mock('node:fs', () => ({
  existsSync: vi.fn(() => false),
  readFileSync: vi.fn(() => '{}'),
  mkdirSync: vi.fn(),
}));

vi.mock('../../lib/common.js', () => ({
  outputSilentSuccess: vi.fn(() => ({ continue: true, suppressOutput: true })),
  logHook: vi.fn(),
}));

vi.mock('../../lib/atomic-write.js', () => ({
  atomicWriteSync: vi.fn(),
}));

vi.mock('../../lib/paths.js', () => ({
  getLogDir: vi.fn(() => '/tmp/test-logs'),
}));

import { taskProgressInitializer } from '../../task-created/task-progress-initializer.js';
import { outputSilentSuccess } from '../../lib/common.js';
import { existsSync, readFileSync } from 'node:fs';
import { atomicWriteSync } from '../../lib/atomic-write.js';
import type { HookInput } from '../../types.js';

// =============================================================================
// Helpers
// =============================================================================

function createTaskInput(overrides: Partial<HookInput> = {}): HookInput {
  return {
    tool_name: '',
    session_id: 'test-session-123',
    project_dir: '/test/project',
    tool_input: {},
    task_id: 'task-abc',
    task_subject: '[1/5] Implement auth flow',
    ...overrides,
  };
}

function mockExistingState(state: Record<string, unknown>): void {
  vi.mocked(existsSync).mockReturnValue(true);
  vi.mocked(readFileSync).mockReturnValue(JSON.stringify(state));
}

// =============================================================================
// Tests
// =============================================================================

describe('task-progress-initializer', () => {
  beforeEach(() => {
    vi.clearAllMocks();
    vi.mocked(existsSync).mockReturnValue(false);
  });

  describe('basic behavior', () => {
    test('returns silent success for numbered tasks', () => {
      const input = createTaskInput();
      taskProgressInitializer(input);
      // Should call outputSilentSuccess (it always returns silent)
      expect(outputSilentSuccess).toHaveBeenCalled();
    });

    test('returns silent success for non-numbered tasks', () => {
      const input = createTaskInput({ task_subject: 'Fix authentication bug' });
      taskProgressInitializer(input);
      expect(outputSilentSuccess).toHaveBeenCalled();
    });

    test('returns silent success when task_subject is empty', () => {
      const input = createTaskInput({ task_subject: '' });
      taskProgressInitializer(input);
      expect(outputSilentSuccess).toHaveBeenCalled();
    });
  });

  describe('numbered task detection', () => {
    test('detects [1/5] pattern and saves state', () => {
      const input = createTaskInput({ task_subject: '[1/5] Build auth module' });
      taskProgressInitializer(input);

      expect(atomicWriteSync).toHaveBeenCalled();
      const savedState = JSON.parse(vi.mocked(atomicWriteSync).mock.calls[0][1] as string);
      expect(savedState.total).toBe(5);
    });

    test('detects [3/10] pattern', () => {
      const input = createTaskInput({ task_subject: '[3/10] Run integration tests' });
      taskProgressInitializer(input);

      expect(atomicWriteSync).toHaveBeenCalled();
      const savedState = JSON.parse(vi.mocked(atomicWriteSync).mock.calls[0][1] as string);
      expect(savedState.total).toBe(10);
    });

    test('ignores tasks without numbered prefix', () => {
      const input = createTaskInput({ task_subject: 'Fix authentication bug' });
      taskProgressInitializer(input);
      expect(atomicWriteSync).not.toHaveBeenCalled();
    });

    test('ignores numbered patterns not at start', () => {
      const input = createTaskInput({ task_subject: 'Task [1/5] in middle' });
      taskProgressInitializer(input);
      expect(atomicWriteSync).not.toHaveBeenCalled();
    });

    test('ignores [1/1] (total < 2)', () => {
      const input = createTaskInput({ task_subject: '[1/1] Single task' });
      taskProgressInitializer(input);
      expect(atomicWriteSync).not.toHaveBeenCalled();
    });
  });

  describe('state management', () => {
    test('initializes state with correct total', () => {
      const input = createTaskInput({ task_subject: '[1/7] Phase one' });
      taskProgressInitializer(input);

      const savedState = JSON.parse(vi.mocked(atomicWriteSync).mock.calls[0][1] as string);
      expect(savedState).toEqual(expect.objectContaining({
        total: 7,
        completed: 0,
        task_ids: [],
        session_id: 'test-session-123',
      }));
    });

    test('updates total when new batch is larger', () => {
      mockExistingState({
        total: 5,
        completed: 2,
        task_ids: ['t1', 't2'],
        session_id: 'test-session-123',
      });

      const input = createTaskInput({ task_subject: '[1/10] Bigger batch' });
      taskProgressInitializer(input);

      expect(atomicWriteSync).toHaveBeenCalled();
      const savedState = JSON.parse(vi.mocked(atomicWriteSync).mock.calls[0][1] as string);
      expect(savedState.total).toBe(10);
    });

    test('does not downgrade total when new batch is smaller', () => {
      mockExistingState({
        total: 10,
        completed: 5,
        task_ids: ['t1', 't2', 't3', 't4', 't5'],
        session_id: 'test-session-123',
      });

      const input = createTaskInput({ task_subject: '[1/3] Smaller batch' });
      taskProgressInitializer(input);

      // Should NOT write — total 3 < existing total 10
      expect(atomicWriteSync).not.toHaveBeenCalled();
    });

    test('resets state when session changes', () => {
      mockExistingState({
        total: 5,
        completed: 3,
        task_ids: ['t1', 't2', 't3'],
        session_id: 'old-session',
      });

      const input = createTaskInput({
        task_subject: '[1/4] New session task',
        session_id: 'new-session',
      });
      taskProgressInitializer(input);

      expect(atomicWriteSync).toHaveBeenCalled();
      const savedState = JSON.parse(vi.mocked(atomicWriteSync).mock.calls[0][1] as string);
      expect(savedState.total).toBe(4);
      expect(savedState.completed).toBe(0);
      expect(savedState.session_id).toBe('new-session');
    });

    test('handles corrupted state file gracefully', () => {
      vi.mocked(existsSync).mockReturnValue(true);
      vi.mocked(readFileSync).mockReturnValue('NOT VALID JSON');

      const input = createTaskInput({ task_subject: '[1/5] After corruption' });

      // Should not throw
      expect(() => taskProgressInitializer(input)).not.toThrow();
      expect(atomicWriteSync).toHaveBeenCalled();
    });

    test('handles state with missing task_ids array', () => {
      vi.mocked(existsSync).mockReturnValue(true);
      vi.mocked(readFileSync).mockReturnValue(JSON.stringify({ total: 3, completed: 1 }));

      const input = createTaskInput({ task_subject: '[1/5] Missing array' });

      expect(() => taskProgressInitializer(input)).not.toThrow();
      expect(atomicWriteSync).toHaveBeenCalled();
    });
  });

  describe('edge cases', () => {
    test('handles [0/5] (zero index) pattern', () => {
      const input = createTaskInput({ task_subject: '[0/5] Zero-indexed task' });
      taskProgressInitializer(input);

      expect(atomicWriteSync).toHaveBeenCalled();
      const savedState = JSON.parse(vi.mocked(atomicWriteSync).mock.calls[0][1] as string);
      expect(savedState.total).toBe(5);
    });

    test('handles large batch numbers', () => {
      const input = createTaskInput({ task_subject: '[1/100] Large batch' });
      taskProgressInitializer(input);

      const savedState = JSON.parse(vi.mocked(atomicWriteSync).mock.calls[0][1] as string);
      expect(savedState.total).toBe(100);
    });

    test('empty session_id defaults to empty string', () => {
      const input = createTaskInput({
        task_subject: '[1/3] No session',
        session_id: '',
      });
      taskProgressInitializer(input);

      const savedState = JSON.parse(vi.mocked(atomicWriteSync).mock.calls[0][1] as string);
      expect(savedState.session_id).toBe('');
    });
  });
});
