name: 'Run Tests'
description: 'Standardized test execution with setup and dynamic discovery'

inputs:
  test-category:
    description: 'Test category for naming (e.g., unit, security, integration)'
    required: true
  test-dir:
    description: 'Directory containing test scripts'
    required: true
  node-version:
    description: 'Node.js version'
    required: false
    default: '22'
  needs-plugins:
    description: 'Download built plugins artifact'
    required: false
    default: 'true'
  ci-setup-flags:
    description: 'Extra flags for ci-setup.sh (e.g., --with-shellcheck)'
    required: false
    default: ''
  run-ci-setup:
    description: 'Whether to run bin/ci-setup.sh'
    required: false
    default: 'true'
  verbose:
    description: 'Enable verbose test output'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Download built plugins
      if: inputs.needs-plugins == 'true'
      uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0  # v5
      with:
        name: built-plugins
        path: plugins/

    - name: Setup environment
      uses: ./.github/actions/setup
      with:
        node-version: ${{ inputs.node-version }}
        build-plugins: 'false'
        run-ci-setup: ${{ inputs.run-ci-setup }}
        ci-setup-flags: ${{ inputs.ci-setup-flags }}

    - name: Run ${{ inputs.test-category }} tests
      shell: bash
      run: |
        export CLAUDE_PROJECT_DIR="${{ github.workspace }}"

        # Check if test directory exists
        if [[ ! -d "${{ inputs.test-dir }}" ]]; then
          echo "ERROR: Test directory not found: ${{ inputs.test-dir }}"
          exit 1
        fi

        # Run tests using discovery script
        VERBOSE_FLAG=""
        if [[ "${{ inputs.verbose }}" == "true" ]]; then
          VERBOSE_FLAG="--verbose"
        fi

        bash scripts/ci/run-tests.sh "${{ inputs.test-dir }}" $VERBOSE_FLAG
