// Generated by OrchestKit Claude Plugin
// Created: 2026-05-20

/**
 * Tool-Invocation Linter — PreToolUse Hook
 *
 * Runs a registry of `ToolInvocationRule`s against every PreToolUse
 * invocation and surfaces non-blocking advisories when a rule matches.
 * One hook, N rules — adding a defense is a registry entry, not a PR.
 *
 * Always returns `continue: true`; severity `warn` and `info` produce
 * additionalContext only. Severity `block` is reserved for future use
 * (no current rule needs it); when added, the dispatcher this hook
 * runs under will honour `continue: false` per the existing block path.
 *
 * @hook PreToolUse[Agent] (today) — extensible to other matchers later
 * @see  #1883 — seed rule for the framework
 */

import type { HookInput, HookResult, HookContext } from '../types.js';
import { outputSilentSuccess, outputAllowWithContext } from '../lib/common.js';
import { NOOP_CTX } from '../lib/context.js';
import {
  TOOL_INVOCATION_RULES,
  safelyMatches,
  type ToolInvocationRule,
} from '../lib/tool-invocation-rules.js';
import { getMemoryRules } from '../lib/memory-lint.js';

const HOOK_NAME = 'tool-invocation-linter';

/** Format a matched rule as a one-line advisory. */
function formatAdvisory(rule: ToolInvocationRule): string {
  const tag = rule.severity === 'warn' ? '⚠️' : rule.severity === 'block' ? '🚫' : 'ℹ️';
  const src = rule.source ? ` [${rule.source}]` : '';
  return `${tag} [${rule.id}] ${rule.message} (see: ${rule.see})${src}`;
}

export function toolInvocationLinter(
  input: HookInput,
  ctx: HookContext = NOOP_CTX,
): HookResult {
  const toolName = input.tool_name;
  if (!toolName) return outputSilentSuccess();

  const toolInput = (input.tool_input as Record<string, unknown> | undefined) ?? {};

  // Merge memory-sourced rules (#1901). The static registry is canonical and
  // wins on `id` collision; memory rules are advisory-only (warn/info).
  const staticIds = new Set(TOOL_INVOCATION_RULES.map((r) => r.id));
  const memoryRules = getMemoryRules(input.project_dir).filter((r) => !staticIds.has(r.id));

  // Filter to rules that apply to this tool — preserves O(rules) but skips
  // predicate evaluation for unrelated tools.
  const applicable = [...TOOL_INVOCATION_RULES, ...memoryRules].filter((r) => r.tool_name === toolName);
  if (applicable.length === 0) return outputSilentSuccess();

  const matches = applicable.filter((r) => safelyMatches(r, toolInput));
  if (matches.length === 0) return outputSilentSuccess();

  // Future: severity 'block' short-circuits with continue:false. v1 has no
  // such rule; gate the path here for forward compat.
  const blocking = matches.find((m) => m.severity === 'block');
  if (blocking) {
    ctx.log(HOOK_NAME, `BLOCKING match: ${blocking.id}`, 'warn');
    return {
      continue: false,
      stopReason: formatAdvisory(blocking),
    };
  }

  const advisory = matches.map(formatAdvisory).join(' | ');
  ctx.log(HOOK_NAME, `Matched ${matches.length} rule(s): ${matches.map((m) => m.id).join(', ')}`, 'debug');
  return outputAllowWithContext(advisory);
}

export default toolInvocationLinter;
