#!/bin/bash
# Generated by OrchestKit Claude Plugin
# Created: 2026-09-11

# Test: hooks.json hook-entry schema keys (#4060)
#
# CC silently ignores unknown keys on a hooks.<Event>[] entry, so a condition
# written at group level is dead on arrival: hooks.json shipped two matcher
# group "if" keys (PreToolUse[7], PermissionRequest[0]) that CC 2.1.268
# reported unknown and ignored on every session start. This suite pins the
# gate that prevents the class from returning:
#   - the real hooks.json carries only documented matcher-group keys
#     (allowlist: matcher, hooks) - asserted independently of the validator
#   - the validator (scripts/validate-registry.mjs) PASSES on the real file
#   - the validator FAILS on a fixture carrying the historical "if" key and
#     names the event, the index, and the key (negative control, #4060 shape)
#   - the validator FAILS on a fixture carrying any other unknown key
#
# The negative controls run the SAME validator the closure gate runs, against
# a temp fixture, so a validator regression cannot pass this suite green.
# Every grep runs against a FILE, never a pipe or here-string: unbounded
# validator output through grep -q SIGPIPEs a producer and races fail-open
# under pipefail (#603, ork#3348 instances 1-3).

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
HOOKS_JSON="$REPO_ROOT/src/hooks/hooks.json"
VALIDATOR="$REPO_ROOT/src/hooks/scripts/validate-registry.mjs"

FAILED=0
CHECKED=0

if [[ ! -f "$HOOKS_JSON" ]]; then
  echo "FAIL: hooks.json missing: $HOOKS_JSON"
  exit 1
fi
if [[ ! -f "$VALIDATOR" ]]; then
  echo "FAIL: validator missing: $VALIDATOR"
  exit 1
fi

TMP="$(mktemp -d "${TMPDIR:-/tmp}/hooks-schema-keys.XXXXXX")"
trap 'rm -rf "$TMP"' EXIT
OUT="$TMP/validator-output.txt"

# 1. Independent allowlist check on the REAL file, not routed through the
# validator: if the validator's own parser ever goes blind, this still fails.
allowlist_errors="$(node -e '
  const d = JSON.parse(require("fs").readFileSync(process.argv[1], "utf8"));
  const ALLOWED = new Set(["matcher", "hooks"]);
  const errs = [];
  for (const [event, groups] of Object.entries(d.hooks || {})) {
    groups.forEach((g, i) => {
      if (!g || typeof g !== "object") return;
      for (const k of Object.keys(g)) {
        if (!ALLOWED.has(k)) errs.push(`hooks.${event}[${i}] unknown key "${k}"`);
      }
    });
  }
  console.log(errs.join("\n"));
' "$HOOKS_JSON")"
CHECKED=$((CHECKED + 1))
if [[ -z "$allowlist_errors" ]]; then
  echo "PASS: real hooks.json has only documented matcher-group keys (matcher, hooks)"
else
  echo "FAIL: real hooks.json carries unknown matcher-group keys:"
  echo "$allowlist_errors" | sed 's/^/    /'
  FAILED=$((FAILED + 1))
fi

# 2. Positive control: the same validator the closure gate runs must PASS on
# the real file (and its schema section must not report anything).
node "$VALIDATOR" > "$OUT" 2>&1 && rc=0 || rc=$?
CHECKED=$((CHECKED + 1))
if [[ "$rc" -eq 0 ]] && grep -Fq "Result: PASS" "$OUT"; then
  echo "PASS: validator passes on real hooks.json"
else
  echo "FAIL: validator failed on real hooks.json (exit $rc)"
  head -15 "$OUT" | sed 's/^/    /'
  FAILED=$((FAILED + 1))
fi
CHECKED=$((CHECKED + 1))
if grep -Fq "SCHEMA KEYS" "$OUT"; then
  echo "FAIL: validator reports SCHEMA KEYS on the real hooks.json"
  grep "SCHEMA KEYS" "$OUT" | sed 's/^/    /'
  FAILED=$((FAILED + 1))
else
  echo "PASS: no SCHEMA KEYS failures on the real hooks.json"
fi

# 3. Negative control, #4060 shape: the exact "if" key CC reported, injected
# at the exact group (PreToolUse[7]) the issue names. Must FAIL, and the
# failure must name event, index, and key.
node -e '
  const fs = require("fs");
  const d = JSON.parse(fs.readFileSync(process.argv[1], "utf8"));
  d.hooks.PreToolUse[7].if = "AskUserQuestion(*)";
  fs.writeFileSync(process.argv[2], JSON.stringify(d, null, 2));
' "$HOOKS_JSON" "$TMP/if-key.json"
node "$VALIDATOR" "$TMP/if-key.json" > "$OUT" 2>&1 && rc=0 || rc=$?
CHECKED=$((CHECKED + 1))
if [[ "$rc" -eq 1 ]] && grep -Fq "Result: FAIL" "$OUT"; then
  echo "PASS: fixture with historical if key fails validation"
else
  echo "FAIL: validator did not fail on the #4060-shaped fixture (exit $rc)"
  head -15 "$OUT" | sed 's/^/    /'
  FAILED=$((FAILED + 1))
fi
CHECKED=$((CHECKED + 1))
if grep -Fq 'hooks.PreToolUse[7] carries unknown key(s) "if"' "$OUT"; then
  echo "PASS: failure names the if key at PreToolUse[7]"
else
  echo "FAIL: SCHEMA KEYS failure missing the named event/index/key"
  grep "SCHEMA KEYS" "$OUT" | sed 's/^/    /' || echo "    (no SCHEMA KEYS line at all)"
  FAILED=$((FAILED + 1))
fi

# 4. Negative control, generic unknown key: any group-level key outside the
# allowlist must fail, not just "if" specifically.
node -e '
  const fs = require("fs");
  const d = JSON.parse(fs.readFileSync(process.argv[1], "utf8"));
  const pr = d.hooks.PermissionRequest.findIndex(g => g.matcher === "Bash");
  d.hooks.PermissionRequest[pr].conditions = ["Bash(git push*)"];
  fs.writeFileSync(process.argv[2], JSON.stringify(d, null, 2));
' "$HOOKS_JSON" "$TMP/generic-key.json"
node "$VALIDATOR" "$TMP/generic-key.json" > "$OUT" 2>&1 && rc=0 || rc=$?
CHECKED=$((CHECKED + 1))
if [[ "$rc" -eq 1 ]] && grep -Fq "Result: FAIL" "$OUT" && grep -Eq "PermissionRequest\[[0-9]+\] carries unknown key" "$OUT"; then
  echo "PASS: fixture with generic unknown key fails validation, naming the entry"
else
  echo "FAIL: validator did not fail on the generic-unknown-key fixture (exit $rc)"
  head -15 "$OUT" | sed 's/^/    /'
  FAILED=$((FAILED + 1))
fi

echo ""
if [[ "$FAILED" -gt 0 ]]; then
  echo "Result: FAIL ($FAILED of $CHECKED checks failed)"
  exit 1
fi
echo "Result: PASS ($CHECKED checks)"
