#!/usr/bin/env bash
# Generated by OrchestKit Claude Plugin
# Created: 2026-06-23

# Tests the auto-memory index budget check in
# src/skills/doctor/references/memory-health.md (ork:doctor Category 4).
#
# Extracts the VERBATIM bash snippet from the doc and runs it against fixtures
# via the ORK_MEM_INDEX override — so the doc stays the source of truth and the
# test re-validates the actual artifact. Covers every branch matching CC's
# native "first 200 lines OR 25 KB, whichever first" cap: byte cap, line cap,
# long-line, healthy, empty, missing.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
DOC="$REPO_ROOT/src/skills/doctor/references/memory-health.md"

RED=$'\033[0;31m'; GREEN=$'\033[0;32m'; NC=$'\033[0m'
PASS=0; FAIL=0
pass() { echo "  ${GREEN}✓${NC} $1"; PASS=$((PASS + 1)); }
fail() { echo "  ${RED}✗${NC} $1"; FAIL=$((FAIL + 1)); }

echo "════════════════════════════════════════════════════════════════"
echo "  Auto-memory index budget check (ork:doctor Cat 4)"
echo "════════════════════════════════════════════════════════════════"

# ── Extract the verbatim snippet from the doc ───────────────────────────────
SNIP="$(mktemp)"
awk '/## Auto-Memory Index Budget/{f=1} f&&/```bash/{c=1;next} f&&/```/{if(c)exit} c' "$DOC" > "$SNIP"
if ! grep -q 'ORK_MEM_INDEX' "$SNIP"; then
  fail "snippet missing ORK_MEM_INDEX override — not testable"
  rm -f "$SNIP"; exit 1
fi
pass "extracted snippet from memory-health.md ($(wc -l < "$SNIP" | tr -d ' ') lines)"

run() { ORK_MEM_INDEX="$1" bash "$SNIP" 2>&1; }
assert() { # name, output, expected-substring
  if echo "$2" | grep -qF "$3"; then pass "$1"; else fail "$1 — got: ${2:-<empty>}"; fi
}
assert_empty() { if [ -z "$2" ]; then pass "$1"; else fail "$1 — got: $2"; fi; }

# ── Fixtures ────────────────────────────────────────────────────────────────
T="$(mktemp -d)"
printf -- '- [a](b.md) — short hook\n- [c](d.md) — another\n' > "$T/healthy.md"
head -c 30000 /dev/zero | tr '\0' x > "$T/overbytes.md"                 # > 25 KB
for _ in $(seq 1 250); do echo "- [a](b.md) — h"; done > "$T/overlines.md"  # > 200 lines, < 25 KB
printf -- '- [a](b.md) — %s\n' "$(head -c 250 /dev/zero | tr '\0' z)" > "$T/longline.md"  # 1 line > 200 chars
: > "$T/empty.md"

# ── Assertions ──────────────────────────────────────────────────────────────
assert       "healthy index            → OK"          "$(run "$T/healthy.md")"   "OK:"
assert       "over 25 KB               → WARN bytes"  "$(run "$T/overbytes.md")" "B >"
assert       "over 200 lines (< 25 KB) → WARN lines"  "$(run "$T/overlines.md")" "lines >"
assert       "index line > 200 chars   → WARN chars"  "$(run "$T/longline.md")"  "chars"
assert       "empty file               → OK"          "$(run "$T/empty.md")"     "OK:"
assert_empty "missing file             → silent"      "$(run "$T/nope.md")"

rm -rf "$T" "$SNIP"
echo "════════════════════════════════════════════════════════════════"
echo "  Total: $((PASS + FAIL))  |  Passed: ${GREEN}${PASS}${NC}  |  Failed: ${RED}${FAIL}${NC}"
echo "════════════════════════════════════════════════════════════════"
[ "$FAIL" -eq 0 ]
