// Generated by OrchestKit Claude Plugin
// Created: 2026-06-11

/**
 * Spawn Intent Logger — PreToolUse[Task] Hook
 *
 * Logs the Agent tool's `description`/`prompt` summary to the spawn log.
 * This MUST happen at PreToolUse: the SubagentStart payload carries only
 * {session_id, transcript_path, cwd, agent_id, agent_type, hook_event_name}
 * (live-captured on CC 2.1.173, 2026-06-11) — no description, no prompt —
 * which is why every spawn-log entry shipped with `description: ""` and
 * delegation-fit audits were blind (#2371 follow-up).
 *
 * Entries are tagged `source: "pretool"` to distinguish them from the
 * SubagentStart entries written by subagent-validator (`source: "start"`,
 * which carry `agent_id` — CC provides no field to correlate the two).
 *
 * Non-blocking, append-only, no reads — safe for the PreToolUse hot path.
 *
 * @hook PreToolUse[Task]
 */

import { join } from 'node:path';
import type { HookInput, HookResult, HookContext } from '../../types.js';
import { outputSilentSuccess, getProjectDir } from '../../lib/common.js';
import { bufferWrite } from '../../lib/analytics-buffer.js';
import { classifySpawnTarget } from '../../lib/agent-registry.js';
import { NOOP_CTX } from '../../lib/context.js';

const HOOK_NAME = 'spawn-intent-logger';

/** Max chars persisted per description. */
export const SPAWN_DESCRIPTION_MAX = 200;

/**
 * Derive a one-line task summary: explicit Agent-tool `description` first,
 * `task_description` next (context-stager parity), else the first non-empty
 * line of the prompt.
 */
export function deriveSpawnDescription(input: HookInput): string {
  const toolInput = input.tool_input || {};
  const explicit =
    (toolInput.description as string) || (toolInput.task_description as string) || '';
  if (explicit.trim()) return explicit.trim().slice(0, SPAWN_DESCRIPTION_MAX);
  const prompt = typeof toolInput.prompt === 'string' ? toolInput.prompt : '';
  const firstLine = prompt
    .split('\n')
    .map((line) => line.trim())
    .find((line) => line.length > 0);
  return (firstLine || '').slice(0, SPAWN_DESCRIPTION_MAX);
}

export function spawnIntentLogger(input: HookInput, ctx: HookContext = NOOP_CTX): HookResult {
  const toolInput = input.tool_input || {};
  // M170/#3129: a spawn has a TYPE (subagent_type, defaulting to
  // general-purpose when omitted) and optionally a NAME (the `name` param).
  // CC's SubagentStart payload puts the NAME in agent_type for named spawns,
  // shadowing the real type — so this pretool row is the only place the
  // (type, name) pair is ever observable. Record both, never conflate.
  const rawType = (toolInput.subagent_type as string) || '';
  const agentName = (toolInput.name as string) || '';
  const subagentType = rawType || (agentName ? 'general-purpose' : '');

  // Guard at top: only Task/Agent invocations carry spawn intent.
  if (!subagentType) {
    return outputSilentSuccess();
  }

  // Whether the target actually resolves. Recorded alongside the type so the
  // invalid-spawn RATE is queryable with the tooling that already reads this
  // stream (audit-activation correlates subagent_type against the agent
  // inventory). That measurement is what lets agent-registry-validator move
  // from ask to deny on evidence instead of on a guess.
  let verdict: ReturnType<typeof classifySpawnTarget> | null = null;
  try {
    verdict = classifySpawnTarget(subagentType);
  } catch {
    // Registry unreadable — record the spawn without a verdict rather than
    // losing the row. silent: telemetry
    verdict = null;
  }
  const suggestion =
    verdict && (verdict.kind === 'bare' || verdict.kind === 'unknown') ? verdict.suggestion : null;

  const entry = {
    timestamp: new Date().toISOString(),
    source: 'pretool' as const,
    subagent_type: subagentType,
    ...(agentName ? { agent_name: agentName } : {}),
    description: deriveSpawnDescription(input),
    session_id: input.session_id,
    ...(input.tool_use_id ? { tool_use_id: input.tool_use_id } : {}),
    // 'skip' (other plugins, placeholders) carries no signal, so it is omitted
    // rather than recorded as a fourth state nobody can act on.
    ...(verdict && verdict.kind !== 'skip' ? { spawn_verdict: verdict.kind } : {}),
    ...(suggestion ? { spawn_suggestion: suggestion } : {}),
  };

  try {
    const trackingLog = join(getProjectDir(), '.claude', 'logs', 'subagent-spawns.jsonl');
    bufferWrite(trackingLog, `${JSON.stringify(entry)}\n`);
  } catch {
    // Best-effort telemetry — never interfere with the dispatch.
  }

  ctx.log(HOOK_NAME, `Spawn intent: ${subagentType} — ${entry.description.slice(0, 60)}`);
  return outputSilentSuccess();
}
