// Generated by OrchestKit Claude Plugin
// Created: 2026-02-18

/**
 * Task Agent Advisor — PreToolUse[Task] Hook
 *
 * Suggests curated ork agents when ad-hoc subagent_type names are used.
 * Analytics shows 250+ ad-hoc names being spawned instead of curated agents.
 * This hook nudges users toward the right agent via additionalContext.
 *
 * Also nudges general-purpose/untyped spawns that merely RUN tests/build/lint
 * back toward Bash — deterministic commands don't need an LLM subagent (one
 * observed swarm burned ~1.35M tokens running test batches through agents).
 *
 * Mostly advisory (additionalContext). ONE branch enforces: a `general-purpose`
 * spawn whose task clearly matches a specialist domain returns `permissionDecision:
 * "ask"` so CC surfaces the specialist as an active choice instead of an ignorable
 * note. Still `continue: true` — never a hard `deny`.
 *
 * @hook PreToolUse[Task]
 * @see https://github.com/yonatangross/orchestkit/issues/706
 */

import type { HookInput, HookResult , HookContext} from '../../types.js';
import { outputSilentSuccess, outputAllowWithContext, outputAsk } from '../../lib/common.js';
import { NOOP_CTX } from '../../lib/context.js';

const HOOK_NAME = 'task-agent-advisor';

/**
 * Ad-hoc names that should be replaced with curated ork agents.
 * Keys are lowercase for case-insensitive matching.
 * Exported so tests can cross-check every value against src/agents/.
 */
export const ORK_AGENT_SYNONYMS: Record<string, string> = {
  'frontend-dev': 'ork:frontend-ui-developer',
  'frontend-engineer': 'ork:frontend-ui-developer',
  'frontend-fixer': 'ork:frontend-ui-developer',
  'frontend-eng': 'ork:frontend-ui-developer',
  'backend-dev': 'ork:backend-system-architect',
  'backend-engineer': 'ork:backend-system-architect',
  'backend-fixer': 'ork:backend-system-architect',
  'backend-eng': 'ork:backend-system-architect',
  'security-fixer': 'ork:security-auditor',
  'security-engineer': 'ork:security-auditor',
  'code-reviewer': 'ork:code-quality-reviewer',
  'quality-reviewer': 'ork:code-quality-reviewer',
  'test-writer': 'ork:test-generator',
  'unit-tester': 'ork:test-generator',
};

/**
 * Wrong-cased built-in names that should use the correct casing.
 * These are valid built-ins — not ork agents — just mis-cased.
 */
const BUILTIN_CASING_FIXES: Record<string, string> = {
  'explore': 'Explore',
  'explorer': 'Explore',
  'explore-agent': 'Explore',
  'generalpurpose': 'general-purpose',
  // Mis-casings like `General-Purpose` lowercase to this key. Correct-cased
  // `general-purpose` never reaches here — the exact-match nudge branch
  // returns first — so this only ever fires for wrong casings.
  'general-purpose': 'general-purpose',
};

/** Built-in names that are already correct (exact casing per CC Feb 2026 spec) — never suggest replacing these. */
const VALID_BUILTINS = new Set(['Explore', 'Plan', 'general-purpose', 'Bash', 'statusline-setup']);

/**
 * Domain-shaped prompts dispatched as `general-purpose` get a specialist
 * nudge. Telemetry (424 spawns, 2026-06-11): 17% of real spawns were
 * general-purpose while ork specialists sat at 10% — the advisor previously
 * whitelisted general-purpose and could never suggest otherwise.
 * Order matters: first match wins, so narrower domains come first.
 * Advisory only — general-purpose remains correct for genuinely mixed tasks.
 * Exported so tests can cross-check every agent against src/agents/.
 */
export const SPECIALIST_DOMAINS: ReadonlyArray<{ agent: string; pattern: RegExp }> = [
  { agent: 'ork:security-auditor', pattern: /\b(vulnerabilit|security (audit|review|scan)|owasp|cve-\d|secrets? (scan|leak)|injection attack)/i },
  { agent: 'ork:debug-investigator', pattern: /\b(root.?cause|stack.?trace|debug (the|this|a|an)\b|investigate (the |this |a |an )?(failure|error|crash|bug|regression)|why (does|is|did) .{0,40}(fail|crash|break|error))/i },
  { agent: 'ork:test-generator', pattern: /\b((write|generate|add|create) (unit |integration |e2e )?tests?\b|coverage gaps?|test suite for)/i },
  { agent: 'ork:code-quality-reviewer', pattern: /\b(code review|review (this|the|my) (code|pr|pull request|diff|changes?))\b/i },
  { agent: 'ork:database-engineer', pattern: /\b(schema migration|alembic|pgvector|database (schema|index|migration)|(optimize|slow) (sql|quer))/i },
  { agent: 'ork:ci-cd-engineer', pattern: /\b(github actions|ci (pipeline|workflow|failure)|\.github\/workflows|gitlab.ci)/i },
  { agent: 'ork:web-research-analyst', pattern: /\b(web research|search (the web|online)|competitor analysis|market (research|landscape))/i },
  { agent: 'ork:frontend-ui-developer', pattern: /\b(react (component|hook)|\.tsx\b|tailwind|css (layout|grid|flex)|frontend (component|page|ui))/i },
  { agent: 'ork:backend-system-architect', pattern: /\b((rest|graphql) api|api endpoints?|microservice|fastapi|backend (service|architecture))/i },
];

/** Bound the prompt scan so regex work stays inside the PreToolUse budget. */
const NUDGE_SCAN_MAX_CHARS = 2000;

/** Find a specialist whose domain matches a general-purpose task's text. */
export function matchSpecialistDomain(description: string, prompt: string): string | null {
  const text = `${description}\n${prompt.slice(0, NUDGE_SCAN_MAX_CHARS)}`;
  const match = SPECIALIST_DOMAINS.find((domain) => domain.pattern.test(text));
  return match ? match.agent : null;
}

/**
 * Deterministic-command detector. A `general-purpose` (or untyped) spawn whose task
 * merely RUNS tests/build/lint belongs in Bash, not an LLM subagent: running a suite
 * needs zero reasoning, yet each general-purpose agent loads ~400k+ tokens just to
 * report pass/fail. Observed 2026-06-21: three such agents burned ~1.35M tokens / wave.
 *
 * Two arms: an explicit run/runner phrase (`run … tests`, `pytest`), OR a bare test-noun
 * task (`dashboard tests`) — but NOT when the task carries a reasoning/authoring verb
 * (write/fix/debug/explore/audit/coverage…), which is legitimate agent work (writing
 * tests → ork:test-generator; debugging a failure → ork:debug-investigator). Suffixes
 * are bounded so `fix(ing)` suppresses but `fixture`/`address` do not. Exported for tests.
 */
export const RUN_CMD_PATTERN =
  /\b(run|execute|kick off)\b.{0,30}\b(tests?|test suite|build|lint|typecheck|ci)\b|\b(npm test|pytest|vitest|jest|go test|cargo test|npm run build)\b/i;
export const TEST_NOUN_PATTERN = /\btests?\b|\btest suite\b|\bspecs?\b/i;
export const REASONING_VERB_PATTERN =
  /\b(?:writ\w*|wrote|generat\w*|creat\w*|updat\w*|debug\w*|investigat\w*|analy[sz]\w*|review\w*|explain\w*|root.?cause|fail\w*|coverage|refactor\w*|explor\w*|understand\w*|audit\w*|document\w*|flak\w*|design\w*)\b|\b(?:add(?:s|ed|ing)?|fix(?:es|ed|ing)?|why)\b/i;

/** True when a task merely RUNS a deterministic command (→ Bash, not an LLM subagent). */
export function isDeterministicRunTask(description: string, prompt: string): boolean {
  const text = `${description}\n${prompt.slice(0, NUDGE_SCAN_MAX_CHARS)}`;
  if (REASONING_VERB_PATTERN.test(text)) return false;
  return RUN_CMD_PATTERN.test(text) || TEST_NOUN_PATTERN.test(text);
}

export function taskAgentAdvisor(input: HookInput, ctx: HookContext = NOOP_CTX): HookResult {
  const toolInput = input.tool_input || {};
  const agentType = (toolInput.subagent_type as string) || '';

  // Deterministic-command guard: a general-purpose (or untyped) spawn whose task is to
  // RUN tests/build/lint should run in Bash, not an LLM agent. Checked BEFORE the
  // empty-type early-return so untyped spawns (which default to general-purpose) are
  // covered too. Advisory only — never blocks.
  if (agentType === 'general-purpose' || agentType === '') {
    const description = (toolInput.description as string) || '';
    const prompt = (toolInput.prompt as string) || '';
    if (isDeterministicRunTask(description, prompt)) {
      ctx.log(HOOK_NAME, 'deterministic test/build/lint task on general-purpose — nudging to Bash');
      return outputAllowWithContext(
        'Running tests/build/lint is deterministic — run it in Bash in this loop, not an LLM agent ' +
          '(each general-purpose agent burns ~400k+ tokens for a pass/fail). ' +
          'Parallelize at the runner: `pytest -n auto`, `vitest --shard`. ' +
          'Spawn `ork:debug-investigator` only to fix the FAILING subset.',
      );
    }
  }

  if (!agentType) {
    return outputSilentSuccess();
  }

  const normalizedName = agentType.toLowerCase().trim();

  // general-purpose with a clearly domain-shaped task → specialist nudge.
  if (agentType === 'general-purpose') {
    const description = (toolInput.description as string) || '';
    const prompt = (toolInput.prompt as string) || '';
    const specialist = matchSpecialistDomain(description, prompt);
    if (specialist) {
      ctx.log(HOOK_NAME, `general-purpose task matches ${specialist} domain — asking to redirect`);
      // ENFORCE (not just whisper): the advisory note was provably ignored
      // (telemetry: 14% specialist vs 74% generic). `ask` turns it into an
      // active permission decision — CC surfaces the specialist as a real
      // choice and redirects on confirm. The domain regexes are deliberately
      // narrow, so genuinely multi-domain tasks don't match and never reach
      // here; if a match is a false positive, the user simply approves
      // general-purpose. Never a hard `deny` — keeps the human in the loop.
      return outputAsk(
        `This task matches \`${specialist}\`'s domain — prefer it over \`general-purpose\` ` +
          `(curated system prompt + scoped tools spawn the right specialist). ` +
          `Approve \`general-purpose\` only if the task genuinely spans multiple domains.`,
      );
    }
    return outputSilentSuccess();
  }

  // Skip already-correct built-in names
  if (VALID_BUILTINS.has(agentType)) {
    return outputSilentSuccess();
  }

  // Check ork agent synonyms first
  const orkSuggestion = ORK_AGENT_SYNONYMS[normalizedName];
  if (orkSuggestion) {
    ctx.log(HOOK_NAME, `Suggesting "${orkSuggestion}" instead of ad-hoc "${agentType}"`);
    return outputAllowWithContext(
      `Consider using \`${orkSuggestion}\` instead of \`${agentType}\` — it includes a curated system prompt for this task type.`,
    );
  }

  // Check built-in casing fixes
  const casingFix = BUILTIN_CASING_FIXES[normalizedName];
  if (casingFix) {
    ctx.log(HOOK_NAME, `Casing fix: "${agentType}" -> "${casingFix}"`);
    return outputAllowWithContext(
      `\`${casingFix}\` is the correct built-in name — \`${agentType}\` is wrong-cased and may not resolve correctly (CC 2.1.45 spec).`,
    );
  }

  return outputSilentSuccess();
}
