// Generated by OrchestKit Claude Plugin
// Created: 2026-07-24

/**
 * Workflow AgentType Advisor — PreToolUse[Workflow] Hook
 *
 * The single biggest generic-spawn bucket is Workflow-internal: agent() stages
 * default to the generic workflow subagent (3,559/30d spawns, 49% of all
 * traffic in the 2026-07 cross-account audit; M170). The Task-side advisor
 * cannot see these — Workflow spawns never pass through PreToolUse[Task].
 *
 * This hook scans the inline `script` for agent() call sites and, when none
 * of them set opts.agentType, injects an advisory reminding the author of the
 * specialist catalog mapping (mirror of
 * skills/chain-patterns/references/dynamic-workflow-patterns.md §agentType).
 *
 * Advisory ONLY — always continue:true, always permissionDecision:"allow".
 * Mixed/glue stages are legitimately generic, so this never blocks and stays
 * silent when at least one stage is already typed (author knows the option).
 *
 * @hook PreToolUse[Workflow]
 * @see https://github.com/yonatangross/orchestkit/issues/3126
 */

import type { HookContext, HookInput, HookResult } from '../../types.js';
import { outputAllowWithContext, outputSilentSuccess } from '../../lib/common.js';
import { NOOP_CTX } from '../../lib/context.js';
import { explainSpawnTarget } from '../../lib/agent-registry.js';

const HOOK_NAME = 'workflow-agenttype-advisor';

/** Stage-shape → specialist mapping, kept in sync with dynamic-workflow-patterns.md. */
export const STAGE_MAP: ReadonlyArray<readonly [string, string]> = [
  ['security produce/verify stages', 'ork:security-auditor'],
  ['test generation / coverage / repair', 'ork:test-generator'],
  ['code-review dimensions over a diff', 'ork:code-quality-reviewer'],
  ['web/competitive research fan-out', 'ork:web-research-analyst'],
  ['backend/API/schema design', 'ork:backend-system-architect'],
  ['frontend component work', 'ork:frontend-ui-developer'],
];

/**
 * Count bare agent( call sites in a workflow script.
 * Word-boundary guard excludes .agent( / myagent( / "agent(" in strings well
 * enough for an advisory (false positives only produce a harmless nudge).
 */
export function countAgentCalls(script: string): number {
  const matches = script.match(/(?<![\w.])agent\s*\(/g);
  return matches ? matches.length : 0;
}

/**
 * Every agentType value in a workflow script.
 *
 * Covers the object-literal forms an author actually writes:
 *   agentType: 'ork:x'   agentType: "ork:x"   agentType:`ork:x`
 * A computed value (agentType: someVar) yields no literal and is skipped —
 * this is an advisory, and a name we cannot read is not a name we can fault.
 */
export function extractAgentTypes(script: string): string[] {
  const out: string[] = [];
  const re = /agentType\s*:\s*['"`]([^'"`]+)['"`]/g;
  let m: RegExpExecArray | null = re.exec(script);
  while (m !== null) {
    out.push(m[1]);
    m = re.exec(script);
  }
  return out;
}

export function workflowAgentTypeAdvisor(
  input: HookInput,
  _ctx: HookContext = NOOP_CTX,
): HookResult {
  if (input.tool_name !== 'Workflow') return outputSilentSuccess();

  const toolInput = (input.tool_input ?? {}) as Record<string, unknown>;
  const script = typeof toolInput.script === 'string' ? toolInput.script : '';

  // Named/scriptPath/resume runs carry no inline script — nothing to scan.
  if (!script) return outputSilentSuccess();

  const agentCalls = countAgentCalls(script);
  if (agentCalls === 0) return outputSilentSuccess();

  // Validate the VALUES before deciding anything else.
  //
  // This used to be `if (script.includes('agentType')) return silent`, on the
  // theory that an author who reached for the catalog once needs no nudge.
  // That muted the hook on any script mentioning agentType anywhere, so three
  // valid stages plus one invalid produced total silence — and the invalid one
  // then died at dispatch as a generic "parallel[N] failed" with no line naming
  // the cause (#3279). The message two blocks below has always said "bare names
  // fail to resolve"; the hook simply never checked.
  const invalid = extractAgentTypes(script)
    .map((value) => ({ value, reason: explainSpawnTarget(value) }))
    .filter((r): r is { value: string; reason: string } => r.reason !== null);

  if (invalid.length > 0) {
    const lines = invalid.map((r) => `  - ${r.reason}`).join('\n');
    return outputAllowWithContext(
      `[${HOOK_NAME}] ${invalid.length} workflow stage(s) name an agent that does not resolve:\n${lines}\n` +
        `The stage will fail at dispatch and the failure will not say why (#3279).`,
    );
  }

  // At least one stage is typed and every typed value resolves — nothing to say.
  if (script.includes('agentType')) return outputSilentSuccess();

  const table = STAGE_MAP.map(([shape, agent]) => `  ${shape} -> ${agent}`).join('\n');
  return outputAllowWithContext(
    `[${HOOK_NAME}] This script has ${agentCalls} agent() stage(s), none typed. ` +
      `Untyped stages run the generic workflow subagent — the largest generic-spawn bucket (M170). ` +
      `For stages with an OBVIOUS specialist owner, set opts.agentType:\n${table}\n` +
      `Mixed/cross-domain/glue stages: omit agentType — generic IS correct there. ` +
      `Use namespaced names (ork:x); bare names fail to resolve (#2371).`,
  );
}
