#!/usr/bin/env bash
# Generate env-names.json from .env.tpl op:// lines
# Extracts VAR names only (left-hand side), never values.
# Called at build time; output is committed.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_FILE="${SCRIPT_DIR}/../configs/env-names.json"

# Default to platform checkout if not specified
ENV_TPL="${ENV_TPL:-${SCRIPT_DIR}/../../../.env.tpl}"

# Extract VAR names from op:// lines
# Format: VAR="op://..." or VAR='op://...'
# We only capture the VAR name, never the value.
NAMES=""
if [ -f "$ENV_TPL" ]; then
  # silent: grep-no-match - file may lack op:// lines, exit 1 is expected
  set +e
  NAMES=$(grep -E '^([A-Z_][A-Z0-9_]*)=["\x27]op://' "$ENV_TPL" | sed 's/^\([A-Z_][A-Z0-9_]*\)=.*/\1/' | sort -u)
  set -e
fi

# Build JSON array
if [ -n "$NAMES" ]; then
  # Convert lines to JSON array
  JSON_NAMES=$(printf '%s\n' "$NAMES" | jq -R . | jq -s .)
else
  JSON_NAMES="[]"
fi

# Write config
cat > "$CONFIG_FILE" << EOF
{
  "names": $JSON_NAMES,
  "description": "Env var names from .env.tpl op:// lines. Generated by scripts/gen-env-names.sh. Names only, never values."
}
EOF

echo "Generated $CONFIG_FILE with $(echo "$JSON_NAMES" | jq 'length') names"
